Repository doctrine/orm, pull requests merged in 2018-03, with the labels that each got.

#7048 Remove redundant php-docs
  lib/Doctrine/ORM/Cache/Lock.php
  lib/Doctrine/ORM/Cache/Logging/CacheLoggerChain.php
  lib/Doctrine/ORM/Cache/Logging/StatisticsCacheLogger.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Cache/Region/DefaultMultiGetRegion.php
  lib/Doctrine/ORM/Mapping/CacheMetadata.php
  lib/Doctrine/ORM/Mapping/ClassMetadataBuildingContext.php
  lib/Doctrine/ORM/Mapping/ColumnMetadata.php
  lib/Doctrine/ORM/Mapping/DiscriminatorColumnMetadata.php
  lib/Doctrine/ORM/Mapping/Driver/Annotation/Binder/MappedSuperClassMetadataBinder.php
  lib/Doctrine/ORM/Mapping/EmbeddedClassMetadata.php
  lib/Doctrine/ORM/Mapping/EntityClassMetadata.php
  lib/Doctrine/ORM/Mapping/FetchMode.php
  lib/Doctrine/ORM/Mapping/FieldMetadata.php
  lib/Doctrine/ORM/Mapping/GeneratorType.php
  lib/Doctrine/ORM/Mapping/InheritanceType.php
  lib/Doctrine/ORM/Mapping/JoinColumnMetadata.php
  lib/Doctrine/ORM/Mapping/JoinTableMetadata.php
  lib/Doctrine/ORM/Mapping/LocalColumnMetadata.php
  lib/Doctrine/ORM/Mapping/ManyToManyAssociationMetadata.php
  lib/Doctrine/ORM/Mapping/ManyToOneAssociationMetadata.php
  lib/Doctrine/ORM/Mapping/MappedSuperClassMetadata.php
  lib/Doctrine/ORM/Mapping/OneToManyAssociationMetadata.php
  lib/Doctrine/ORM/Mapping/OneToOneAssociationMetadata.php
  lib/Doctrine/ORM/Mapping/RootClassMetadata.php
  lib/Doctrine/ORM/Mapping/SubClassMetadata.php
  lib/Doctrine/ORM/Mapping/TableMetadata.php
  lib/Doctrine/ORM/Mapping/TableOwner.php
  lib/Doctrine/ORM/Mapping/ToManyAssociationMetadata.php
  lib/Doctrine/ORM/Mapping/ToOneAssociationMetadata.php
  lib/Doctrine/ORM/Mapping/TransientMetadata.php
  lib/Doctrine/ORM/Mapping/ValueGeneratorMetadata.php
  lib/Doctrine/ORM/Mapping/VersionFieldMetadata.php
  lib/Doctrine/ORM/Persisters/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Persisters/Collection/CollectionPersister.php
  lib/Doctrine/ORM/PessimisticLockException.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/AST/BetweenExpression.php
  lib/Doctrine/ORM/Query/AST/Functions/ConcatFunction.php
  lib/Doctrine/ORM/Query/AST/GroupByClause.php
  lib/Doctrine/ORM/Query/AST/HavingClause.php
  lib/Doctrine/ORM/Query/Filter/SQLFilter.php
  lib/Doctrine/ORM/Query/QueryExpressionVisitor.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php
Labels: Improvement

#7107 Update README & CONTRIBUTING for 3.0 changes and workflow
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: Documentation

#7110 Drop tools/sandbox
  tools/sandbox/Entities/Address.php
  tools/sandbox/Entities/User.php
  tools/sandbox/bootstrap.php
  tools/sandbox/doctrine
  tools/sandbox/doctrine.php
  tools/sandbox/index.php
  tools/sandbox/xml/Entities.Address.dcm.xml
  tools/sandbox/xml/Entities.User.dcm.xml
Labels: Improvement

#7111 Nitpicks on `CONTRIBUTING.md`
  CONTRIBUTING.md
  README.md
Labels: Documentation

#7114 Remove tools from PHPCs
  .travis.yml
  phpcs.xml.dist
Labels: Improvement

#7121 Update Scrutinizer config to use our CS setup
  .scrutinizer.yml
Labels: CI

#7132 Fixes a typo
  lib/Doctrine/ORM/EntityManagerAware.php
Labels: Documentation

#6902 Documentation about getters/setters to DTOs and Value Objects
  docs/en/tutorials/getting-started.rst
Labels: Documentation, WIP

#7137 Removing leftover sentence in `getting-started.rst`
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#7139 Fix typo in upgrade notes
  UPGRADE.md
Labels: Documentation

#7150 Redundant condition to check if a query is cacheable
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Improvement

#7154 Fix getting started syntax issue causing rendering glitches
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#7158 Proposed corrected typo in demo code.
  docs/en/tutorials/composite-primary-keys.rst
Labels: Documentation

#7163 Add constructor types to SqlWalker and TreeWalker
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Query/TreeWalker.php
Labels: Improvement
