Repository doctrine/orm, pull requests merged in 2018-07, with the labels that each got.

#7285 Removed outdated entity passed phpdoc for EntityManager::flush
  lib/Doctrine/ORM/EntityManager.php
Labels: Documentation

#7276 Add UPGRADE note for EntityRepository::count()
  UPGRADE.md
Labels: Documentation

#7290 Fix compatibility with DBAL 2.8 (doctrine/dbal#3157)
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
Labels: Improvement

#7292 Use a more concrete, less confusing example
  docs/en/reference/inheritance-mapping.rst
Labels: Documentation

#7287 Streamline documentation code block type hints for readability
  docs/en/reference/second-level-cache.rst
Labels: Documentation

#7291 [2.6] Fix for #7068: EntityManager::find() with pessimistic lock should check for transaction
  lib/Doctrine/ORM/EntityManager.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7068Test.php
Labels: Bug

#7075 Fix for #7068: `EntityManager::find()` with pessimistic lock should check for transaction
  lib/Doctrine/ORM/EntityManager.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7068Test.php
Labels: Bug

#7288 Fix of variable typo in cache usage example
  docs/en/reference/second-level-cache.rst
Labels: Documentation

#7283 Add a polyfill for ctype
  composer.json
Labels: Bug

#7281 Sync 2.7 with 2.6
  UPGRADE.md
  docs/en/reference/working-with-objects.rst
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Id/AbstractIdGenerator.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Query/Lexer.php
  tests/Doctrine/Tests/Models/GH7141/GH7141Article.php
  tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.GH7141.GH7141Article.dcm.xml
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
Labels: Bug

#7295 [DOC] Fix links to API doc for 2nd level cache
  docs/en/reference/second-level-cache.rst
Labels: Documentation

#7301 Fix: Consistently format inversedBy and mappedBy attributes
  docs/en/reference/inheritance-mapping.rst
  docs/en/reference/unitofwork-associations.rst
Labels: Documentation

#7302 Fix: Attributes vs. annotations
  docs/en/reference/association-mapping.rst
Labels: Documentation

#7296 Fix #7286: StringPrimary no longer accepts aggregate functions as argument
  lib/Doctrine/ORM/Query/Parser.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7286Test.php
  tests/Doctrine/Tests/ORM/Query/LanguageRecognitionTest.php
Labels: BC Break, Bug

#7313 typo fix in getting started guide
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#7327 Fix inaccurate description of the `ORMException` interface
  lib/Doctrine/ORM/Exception/ORMException.php
Labels: Documentation
