Repository doctrine/orm, pull requests merged in 2018-09, with the labels that each got.

#7382 Update homepage
  composer.json
Labels: Documentation

#7381 Update homepage
  composer.json
Labels: Documentation

#7388 #7359 Added test for filter disable, refactored code and test
  tests/Doctrine/Tests/ORM/Query/FilterCollectionTest.php
Labels: Improvement

#7378 Typo fix
  docs/en/cookbook/aggregate-fields.rst
Labels: Documentation

#7345 Correct DOMDocument constructor in test
  tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
Labels: Improvement

#7363 Fix compatibility with phan
  lib/Doctrine/ORM/Query/Expr.php
  lib/Doctrine/ORM/Query/Expr/Base.php
Labels: Improvement

#7401 [docs] Fix docblock in `inheritance-mapping.rst`
  docs/en/reference/inheritance-mapping.rst
Labels: Documentation

#7260 Fix the handling of circular references in the commit order calculator
  lib/Doctrine/ORM/Internal/CommitOrderCalculator.php
  tests/Doctrine/Tests/ORM/CommitOrderCalculatorTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7259Test.php
Labels: Bug

#7377 Fix query andX doctype
  lib/Doctrine/ORM/Query/Expr.php
Labels: Documentation, Pick to master

#7367 Fix for BC break in 2.6.2 when calling EM::find() with LockMode::OPTIMISTIC outside of a TX
  lib/Doctrine/ORM/EntityManager.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7366Test.php
Labels: Bug, Regression

#7397 Update getting-started.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#7404 Add tidelift badge and links to the doctrine/orm readme.
  README.md
Labels: Documentation
