Repository doctrine/orm, pull requests merged in 2018-08, with the labels that each got.

#7326 Fix remaining usages of deprecated ClassLoader and Inflector from doctrine/common
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Tools/ConvertDoctrine1Schema.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
Labels: Bug

#7330 Drop UuidGenerator
  docs/en/reference/annotations-reference.rst
  docs/en/reference/basic-mapping.rst
  doctrine-mapping.xsd
  lib/Doctrine/ORM/Annotation/GeneratedValue.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/GeneratorType.php
  lib/Doctrine/ORM/Sequencing/UuidGenerator.php
  tests/Doctrine/Tests/Models/DDC3293/DDC3293User.php
  tests/Doctrine/Tests/Models/DDC3293/DDC3293UserPrefixed.php
  tests/Doctrine/Tests/ORM/Functional/UUIDGeneratorTest.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC3293.DDC3293User.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC3293.DDC3293UserPrefixed.dcm.xml
Labels: BC Break

#7331 #2351 [DDC-1702] Fix EBNF of InExpression (StateFieldPath -> Arithmetic)
  docs/en/reference/dql-doctrine-query-language.rst
  lib/Doctrine/ORM/Query/AST/InExpression.php
Labels: Documentation

#7333 Fix #2935 [DDC-2236] Add note that Paginator might screw aggreg. queries
  docs/en/tutorials/pagination.rst
Labels: Documentation

#7335 Correct method names and broken link in docs
  docs/en/reference/caching.rst
Labels: Documentation

#7337 small fix - `as` in lowercase
  docs/en/cookbook/resolve-target-entity-listener.rst
  docs/en/cookbook/validation-of-entities.rst
Labels: Improvement

#7340 Fix config template for PHPUnit >= 7.2
  phpunit.xml.dist
Labels: Improvement

#7360 Document getPartialReference() properly
  lib/Doctrine/ORM/EntityManagerInterface.php
Labels: Documentation

#7229 Added `UNIQUE INDEX` to generated SQL schema
  docs/en/reference/association-mapping.rst
Labels: Documentation

#7373 Remove remnants of yaml from documentation
  docs/en/sidebar.rst
Labels: Documentation

#7380 Add .doctrine-project.json to root of the project.
  .doctrine-project.json
  composer.json
Labels: Improvement
