Repository doctrine/orm, pull requests merged in 2018-12, with the labels that each got.

#7497 Drop dependency on doctrine/common
  UPGRADE.md
  composer.json
  composer.lock
  lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
  lib/Doctrine/ORM/Tools/Setup.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Tools/SetupTest.php
Labels: BC Break, Improvement

#7494 Do not allow cache clearing with APCu
  UPGRADE.md
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ClearCacheMetadataCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ClearCacheQueryCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ClearCacheResultCommandTest.php
Labels: BC Break, Improvement

#7507 fix typos in security.rst
  docs/en/reference/security.rst
Labels: Documentation

#7473 Incremental CS checks in 2.x branches
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  phpcs.xml.dist
Labels: CI, Improvement

#7521 Update chat link from Gitter to Slack.
  docs/en/index.rst
Labels: Documentation

#7519 #7518 Fixed type mismatch between `EntityRepository#__construct()` and its documented constructor arguments
  lib/Doctrine/ORM/EntityRepository.php
Labels: Documentation, Improvement

#7526 Add support metadata
  composer.json
Labels: Documentation

#7530 Documentation error fix
  docs/en/cookbook/dql-user-defined-functions.rst
Labels: Documentation

#7528 Fix #7527: prevent `UnitOfWork` lookup for DBAL types specified in `Doctrine\ORM\Query#setParameter()`
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/Parameter.php
  tests/Doctrine/Performance/EntityManagerFactory.php
  tests/Doctrine/Performance/Query/QueryBoundParameterProcessingBench.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/ORM/QueryBuilderTest.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Bug, Regression
