Repository doctrine/orm, pull requests merged in 2018-11, with the labels that each got.

#7457 Drop automatic discriminator map discovery
  UPGRADE.md
  docs/en/reference/inheritance-mapping.rst
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: BC Break, Improvement

#7374 Deprecation message in documentation for YAML
  docs/en/reference/yaml-mapping.rst
  docs/en/tutorials/getting-started.rst
Labels: Deprecation, Documentation

#7423 Update association-mapping.rst
  docs/en/reference/association-mapping.rst
Labels: Documentation

#7412 Some formatting improvements
  docs/en/tutorials/getting-started.rst
Labels: Documentation, Improvement

#7444 Fixed URLs of doctrine-mapping.xsd in docs
  docs/en/reference/events.rst
  docs/en/reference/second-level-cache.rst
  docs/en/reference/xml-mapping.rst
  docs/en/tutorials/composite-primary-keys.rst
  docs/en/tutorials/extra-lazy-associations.rst
  docs/en/tutorials/getting-started.rst
  docs/en/tutorials/working-with-indexed-associations.rst
  lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
  tests/Doctrine/Tests/ORM/Functional/xml/Doctrine.Tests.Models.OrnementalOrphanRemoval.Person.dcm.xml
  tests/Doctrine/Tests/ORM/Functional/xml/Doctrine.Tests.Models.OrnementalOrphanRemoval.PhoneNumber.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/CatNoId.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/DDC2429Book.orm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/DDC2429Novel.orm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.CMS.CmsAddress.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.CMS.CmsUser.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Cache.City.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Company.CompanyContract.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Company.CompanyFixContract.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Company.CompanyFlexContract.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Company.CompanyFlexUltraContract.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Company.CompanyPerson.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC117.DDC117Translation.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC1476.DDC1476EntityWithDefaultFieldType.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC2825.ExplicitSchemaAndTable.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC2825.SchemaAndTableInTableName.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC3293.DDC3293Address.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC3293.DDC3293User.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC3293.DDC3293UserPrefixed.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC3579.DDC3579Admin.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC3579.DDC3579User.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC5934.DDC5934BaseContract.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC5934.DDC5934Contract.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC869.DDC869ChequePayment.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC869.DDC869CreditCardPayment.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC869.DDC869Payment.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC889.DDC889Class.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC889.DDC889Entity.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC889.DDC889SuperClass.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC964.DDC964Admin.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC964.DDC964Guest.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC964.DDC964User.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.GH7141.GH7141Article.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Generic.SerializationModel.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.ValueObjects.Name.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.ValueObjects.Person.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.Animal.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.CTI.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.Comment.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.DDC1170Entity.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.DDC807Entity.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.SingleTableEntityIncompleteDiscriminatorColumnMapping.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.SingleTableEntityNoDiscriminatorColumnMapping.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.User.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.XMLSLC.dcm.xml
  tests/Doctrine/Tests/ORM/Tools/Export/XmlClassMetadataExporterTest.php
  tests/Doctrine/Tests/ORM/Tools/Export/xml/Doctrine.Tests.ORM.Tools.Export.User.dcm.xml
  tools/sandbox/xml/Entities.Address.dcm.xml
  tools/sandbox/xml/Entities.User.dcm.xml
Labels: Documentation, Improvement

#7471 Fix parameter value processing for objects with unloaded metadata
  lib/Doctrine/ORM/AbstractQuery.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: Bug

#7474 Remove unecessary need for if statment
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
Labels: Improvement

#7441 $hydrationMode throughout can be a string as well as int (for custom modes)
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/Query.php
Labels: Bug, Documentation

#7472 fix incorrect phpdoc typehint
  lib/Doctrine/ORM/QueryBuilder.php
Labels: Documentation

#7317 [XML] Fix default value of many-to-many order-by to ASC
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  tests/Doctrine/Tests/Models/GH7316/GH7316Article.php
  tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.GH7316.GH7316Article.dcm.xml
Labels: Bug

#6830 fix applying column options on foreign key columns
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Tools/SchemaToolTest.php
Labels: Bug

#7483 Fixed a minor syntax issue
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation

#7484 remove unneded docs
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/QueryBuilder.php
Labels: Documentation, Improvement

#7491 Remove dead code
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Improvement

#7488 Update DBAL 3.x version from 2018-04-17 to 2018-11-26
  composer.json
  composer.lock
  lib/Doctrine/ORM/Mapping/MappingException.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  tests/Doctrine/Tests/ORM/Tools/Console/ConsoleRunnerTest.php
Labels: Improvement
