Repository doctrine/orm, pull requests merged in 2019-11, with the labels that each got.

#7884 [Documentation] Advanced field value... - missing entity alias
  docs/en/cookbook/advanced-field-value-conversion-using-custom-mapping-types.rst
Labels: Documentation

#7889 Use quoted collation declaration when available, fixes test suite when running against DBAL 2.10+
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/MySqlSchemaToolTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2182Test.php
Labels: Bug, CI

#7613 Add headlines for direct references to DQL examples
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation, Improvement

#7647 Add readOnly attribute to annotation example
  docs/en/reference/annotations-reference.rst
Labels: Documentation, Improvement

#7828 Fix for TransientMetadata on joined subclass
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7824Test.php
Labels: Bug, Pick to master

#7869 UnitOfWork::clear() misses $eagerLoadingEntities
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7869Test.php
Labels: Bug

#7865 #7837 paginate with custom identifier types even with enabled DQL query cache
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php
Labels: Bug

#7684 only replace '_id' at end of columnName
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7684Test.php
Labels: Bug

#7861 Delete statements will not be created using `clear`
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7761Test.php
  tests/Doctrine/Tests/ORM/PersistentCollectionTest.php
Labels: Bug, Regression

#7863 Paginator: Skip limit subquery if not required
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1685Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7829Test.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginatorTest.php
Labels: Improvement

#7701 Split and deprecate AbstractQuery#useResultCache()
  UPGRADE.md
  lib/Doctrine/ORM/AbstractQuery.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: Deprecation

#7710 Prettified arrays in tool command orm:mapping:describe
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
Labels: Improvement

#7904 Make sure composer files are valid
  .travis.yml
  composer.lock
Labels: CI

#7905 [Paginator] Fix type conversion during hydration of pagination limit subquery
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  tests/Doctrine/Tests/ORM/Functional/PaginationTest.php
Labels: Bug, Regression

#7908 Fix BC-break on underscore naming strategy
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  tests/Doctrine/Tests/ORM/Mapping/NamingStrategyTest.php
Labels: BC Break, Bug

#7079 fix getJoinTableName for sqlite with schema attribute
  lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7079Test.php
Labels: Bug

#7909 Add deprecation messages
  UPGRADE.md
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  tests/Doctrine/Tests/Mapping/UnderscoreNamingStrategyTest.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
Labels: Deprecation

#7911 Be explicit about which Doctrine package in message
  UPGRADE.md
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateEntitiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateRepositoriesCommand.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/EntityRepositoryGenerator.php
  lib/Doctrine/ORM/Tools/Export/ClassMetadataExporter.php
  lib/Doctrine/ORM/Tools/Export/Driver/AbstractExporter.php
  tests/Doctrine/Tests/Mapping/UnderscoreNamingStrategyTest.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Mapping/Symfony/YamlDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/YamlMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/GenerateRepositoriesCommandTest.php
Labels: Deprecation

#7914 Add branch 2.8 to docs
  .doctrine-project.json
  README.md
Labels: Documentation
