Repository doctrine/orm, pull requests merged in 2019-01, with the labels that each got.

#7551 [2.6] Migrate repository name doctrine/doctrine2 -> doctrine/orm
  CONTRIBUTING.md
  README.md
  SECURITY.md
  UPGRADE.md
  docs/en/changelog/migration_2_5.rst
  docs/en/index.rst
  docs/en/reference/limitations-and-known-issues.rst
  tests/Doctrine/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/README.markdown
Labels: Documentation, Improvement

#7558 Allow all datetime types to be used as version
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  tests/Doctrine/Tests/ORM/Functional/Locking/OptimisticTest.php
Labels: Improvement

#7557 Change Stackoverflow tag to doctrine-orm
  docs/en/index.rst
Labels: Documentation

#7559 Change Stackoverflow tag to doctrine-orm
  docs/en/index.rst
Labels: Documentation

#7571 Fix typo in inheritance mappings docs
  docs/en/reference/inheritance-mapping.rst
Labels: Documentation

#7572 Remove codeigniter Framework example
  docs/en/cookbook/integrating-with-codeigniter.rst
  docs/en/index.rst
  docs/en/toc.rst
Labels: Documentation

#7578 Remove codeigniter Framework example (master)
  docs/en/cookbook/integrating-with-codeigniter.rst
  docs/en/sidebar.rst
Labels: Documentation

#7577 Fix of single link to dbal docs in advanced-configuration.rst
  docs/en/reference/advanced-configuration.rst
Labels: Documentation
