Repository doctrine/orm, pull requests merged in 2019-09, with the labels that each got.

#7785 Fix "access array offset on value of type null" PHP 7.4 notices
  .travis.yml
  composer.json
  composer.lock
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Tools/Export/Driver/YamlExporter.php
  phpunit.xml.dist
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/AbstractEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: Improvement

#7818 Add note into docs about not using SimpleAnnotationReader
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#7821 Bug: #7820 paginator ignores dbal type conversions in identifiers
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Query/ResultSetMapping.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/Tools/Pagination/WhereInWalker.php
  lib/Doctrine/ORM/Utility/PersisterHelper.php
  tests/Doctrine/Tests/Models/ValueConversionType/OwningManyToOneCompositeIdForeignKeyEntity.php
  tests/Doctrine/Tests/Models/ValueConversionType/OwningManyToOneIdForeignKeyEntity.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php
  tests/Doctrine/Tests/ORM/Hydration/ResultSetMappingTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginationTestCase.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/WhereInWalkerTest.php
Labels: Bug, Pick to master

#7610 Change APC to OPcache in improving-performance.rst
  docs/en/reference/improving-performance.rst
Labels: Documentation

#7672 Added cross-links to relevant documentation
  docs/en/reference/caching.rst
  docs/en/reference/improving-performance.rst
Labels: Documentation

#7490 Fix broken link
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Documentation

#7322 JoinedSubclassPersister pass identifier types on delete
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  tests/Doctrine/Tests/ORM/Functional/GH5988Test.php
Labels: Bug, Pick to master

#7838 Fix the name of ClassMetadata in documentation
  docs/en/reference/filters.rst
Labels: Documentation

#7742 Start i var from 1 instead of 0
  docs/en/reference/batch-processing.rst
Labels: Documentation
