Repository doctrine/orm, pull requests merged in 2019-12, with the labels that each got.

#7934 Fix Trying to access array offset on value of type null
  lib/Doctrine/ORM/Query/Parser.php
  tests/Doctrine/Tests/ORM/Query/ParserTest.php
Labels: Bug

#7928 Deprecate EntityRepository#clear()
  lib/Doctrine/ORM/EntityRepository.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
Labels: Deprecation

#7948 Add stage that runs before Test to allow fast failures on Sqlite/phpcs
  .travis.yml
Labels: CI, Improvement

#7941 Allow DQL functions to specify return type
  lib/Doctrine/ORM/Query/AST/Functions/AbsFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/CountFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/FunctionNode.php
  lib/Doctrine/ORM/Query/AST/Functions/LengthFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/SqrtFunction.php
  lib/Doctrine/ORM/Query/AST/TypedExpression.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7941Test.php
Labels: Improvement

#7937 Revert SchemaTool change to check for foreign key support
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2138Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7841Test.php
Labels: Bug, Regression

#7956 Ignore Doctrine\Common\Persistence\ObjectManagerDecorator deprecation
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
  tests/Doctrine/Tests/VerifyDeprecations.php
Labels: CI, Deprecation

#7875 Whilelist existing assets we know about from metadata in SchemaTool::getUpdateSchemaSql()
  UPGRADE.md
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7875Test.php
Labels: BC Break, Bug

#7957 Fix version information
  build.properties
  build.properties.dev
  build.xml
  composer.json
  composer.lock
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  tests/Doctrine/Tests/ORM/Tools/Console/ConsoleRunnerTest.php
  tests/Doctrine/Tests/ORM/Tools/SetupTest.php
Labels: Bug, Deprecation
