Repository doctrine/orm, pull requests merged in 2019-08, with the labels that each got.

#7794 Fix test compatibility with DBAL 2.10.x-dev
  .travis.yml
  tests/Doctrine/Tests/ORM/Tools/SchemaToolTest.php
Labels: CI, Pick to master

#7761 Do not modify UOW on PersistentCollection::clear() when owner has DEFFERED_EXPLICIT change tracking policy
  lib/Doctrine/ORM/PersistentCollection.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7761Test.php
  tests/Doctrine/Tests/ORM/PersistentCollectionTest.php
Labels: Bug, Pick to master

#7750 Fix incorrect return of null values in L2C
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7735Test.php
Labels: Bug, Pick to master

#7766 Respect collection orderBy meta when matching()
  lib/Doctrine/ORM/PersistentCollection.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7767Test.php
Labels: Bug

#7737 Fix MEMBER_OF comparison when using criteria in query builder
  docs/en/reference/working-with-associations.rst
  lib/Doctrine/ORM/Query/QueryExpressionVisitor.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7737Test.php
  tests/Doctrine/Tests/ORM/Query/QueryExpressionVisitorTest.php
Labels: Bug, Missing Tests

#7791 Fix preFlush event documentation stating incorrectly that flush can be called safely
  docs/en/reference/events.rst
Labels: Documentation

#7778 Guard L2C regions against corrupted data
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Region/DefaultMultiGetRegion.php
  lib/Doctrine/ORM/Cache/Region/DefaultRegion.php
  tests/Doctrine/Tests/ORM/Cache/DefaultQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/MultiGetRegionTest.php
Labels: Bug

#7799 Many to many association builder
  lib/Doctrine/ORM/Mapping/Builder/AssociationMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ManyToManyAssociationMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ManyToOneAssociationMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/OneToManyAssociationMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/OneToOneAssociationMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ToManyAssociationMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ToOneAssociationMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  tests/Doctrine/Tests/Models/DDC964/DDC964Admin.php
  tests/Doctrine/Tests/Models/GeoNames/City.php
  tests/Doctrine/Tests/ORM/Functional/AdvancedAssociationTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.GH7141.GH7141Article.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.GH7316.GH7316Article.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Quote.User.dcm.xml
  tests/Doctrine/Tests/ORM/Tools/SchemaToolTest.php
Labels: Improvement, New Feature, WIP
