Repository doctrine/orm, pull requests merged in 2019-10, with the labels that each got.

#7768 EntityManagerHelper can't accept an array of paths
  docs/en/reference/tools.rst
Labels: Documentation

#7764 #7763 escape quotes in field comments
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
Labels: Bug

#7671 Added missing "the"
  docs/en/reference/unitofwork.rst
Labels: Documentation

#7667 Fixes example One-To-One, Self-referencing
  docs/en/reference/association-mapping.rst
Labels: Documentation

#7443 Added doc about exception in Query#getOneOrNullResult()
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation

#7727 [doc] Finish incomplete definition of class UTCDateTimeType
  docs/en/cookbook/working-with-datetime.rst
Labels: Documentation

#7298 Add a missing type in Query::getFirstResult PHPDoc
  lib/Doctrine/ORM/Query.php
Labels: Documentation

#7850 Don't merge PersistentCollection orderBy with criteria in matching()
  lib/Doctrine/ORM/PersistentCollection.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7836Test.php
Labels: Bug

#7849 Mention SQL logger impact on batch processing
  docs/en/reference/batch-processing.rst
Labels: Documentation

#7851 Remove not used variable $reflFieldValue in ObjectHydrator
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
Labels: Improvement

#7856 Fix underscore naming strategy behaviour with numbers
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  tests/Doctrine/Tests/ORM/Mapping/NamingStrategyTest.php
Labels: Bug

#7871 AbstractQuery::getSingleScalarResult() throws exception when no result
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Documentation

#7876 Fix compat of commands with Symfony 5
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/CollectionRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/EntityRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertMappingCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateEntitiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateRepositoriesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
Labels: Improvement

#7880 Update documentation to recommend DQL over QueryBuilder when possible
  docs/en/reference/faq.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/working-with-objects.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#7669 fix: information about units in DATE_ADD, DATE_SUB
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation
