Repository doctrine/orm, pull requests merged in 2020-08, with the labels that each got.

#8223 Change preferred cache driver for metadata and query caches
  docs/en/reference/improving-performance.rst
Labels: Documentation

#8188 Add support for ORDER BY CASE
  lib/Doctrine/ORM/Query/Parser.php
  tests/Doctrine/Tests/ORM/Functional/AdvancedDqlQueryTest.php
Labels: New Feature

#8236 Use more accurate terminology
  docs/en/reference/inheritance-mapping.rst
Labels: Documentation

#8234 Fix for bug #8229 (id column from parent class renamed in child class)
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8229Test.php
Labels: Bug
