Repository doctrine/orm, pull requests merged in 2020-09, with the labels that each got.

#8028 Improve formatting
  docs/en/reference/events.rst
Labels: Documentation

#8277 Fix OrderByItem parser to proceed with SimpleArithmetic expression before function
  lib/Doctrine/ORM/Query/Parser.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
Labels: Bug

#6747 Add Doctrine\ORM\Query\Expr::mod()
  lib/Doctrine/ORM/Query/Expr.php
  tests/Doctrine/Tests/ORM/Query/ExprTest.php
Labels: Improvement

#8279 Use inline literals over escaping
  docs/en/cookbook/dql-custom-walkers.rst
Labels: Documentation
