Repository doctrine/orm, pull requests merged in 2020-12, with the labels that each got.

#8372 Drop step that switches the release branch
  .github/workflows/release-on-milestone-closed.yml
Labels: CI

#8374 Fix invalid psalm annotation
  lib/Doctrine/ORM/EntityRepository.php
Labels: Bug

#8364 Use string literals for function signatures
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation

#8328 Infer `datetime_immutable` DBAL type for `\DateTimeImmutable` instance parameters
  lib/Doctrine/ORM/Query/ParameterTypeInferer.php
  tests/Doctrine/Tests/ORM/Query/ParameterTypeInfererTest.php
Labels: Bug

#8376 [GH-7486] Bugfix: failing when clearing empty cache is wrong semantics
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
Labels: Bug

#8386 Fix Psalm param
  lib/Doctrine/ORM/EntityManager.php
Labels: Bug

#8388 Use the ramsey/composer-install action to install dependencies
  .github/workflows/coding-standard.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
Labels: CI
