Repository doctrine/orm, pull requests merged in 2021-03, with the labels that each got.

#8381 [GH-6855] Prevent unsupported lifecycle callback mapping on embedded classes.
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Deprecation

#8545 remove some empty() use when safe
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
Labels: Improvement

#8547 Make phpdoc types correct
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Region/FileLockRegion.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/Export/Driver/YamlExporter.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Bug

#8556 Fix fieldMapping phpdoc
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Bug

#8564 Adding DIR to include statement to fix issue with pathing
  bin/doctrine
Labels: Bug
