Repository doctrine/orm, pull requests merged in 2021-08, with the labels that each got.

#8859 Drop tools/sandbox
  phpcs.xml.dist
  tools/sandbox/Entities/Address.php
  tools/sandbox/Entities/User.php
  tools/sandbox/bootstrap.php
  tools/sandbox/doctrine
  tools/sandbox/doctrine.php
  tools/sandbox/index.php
  tools/sandbox/xml/Entities.Address.dcm.xml
  tools/sandbox/xml/Entities.User.dcm.xml
  tools/sandbox/yaml/Entities.Address.dcm.yml
  tools/sandbox/yaml/Entities.User.dcm.yml
Labels: Backporting

#8872 Fix CI SA failures
  lib/Doctrine/ORM/Tools/Console/Command/GenerateProxiesCommand.php
  phpstan-baseline.neon
Labels: Bug

#8855 Failing test for GH8443
  lib/Doctrine/ORM/Query/SqlWalker.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8443Test.php
Labels: Failing Test

#8769 Make templating Psalm-specific
  lib/Doctrine/ORM/EntityManagerInterface.php
  tests/Doctrine/StaticAnalysis/get-metadata.php
Labels: Bug

#8852 Remove possibility to extend the doctrine mapping xml schema with anything
  UPGRADE.md
  doctrine-mapping.xsd
Labels: Backporting

#8883 Fix getting-started example by including cache
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#8889 doctrine/dbal v3 - Make sure that values passed to are not null
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
Labels: Improvement

#8892 Bump PHPStan to 0.12.94
  composer.json
Labels: Improvement

#8897 Redeclare `$_attributes` property in `Configuration` class.
  lib/Doctrine/ORM/Configuration.php
  phpcs.xml.dist
Labels: Improvement

#8894 Fix return types for PHP 8.1
  lib/Doctrine/ORM/Internal/Hydration/IterableResult.php
  lib/Doctrine/ORM/Query/TreeWalkerChainIterator.php
  lib/Doctrine/ORM/Tools/Console/MetadataFilter.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  tests/Doctrine/Tests/Mocks/HydratorMockStatement.php
  tests/Doctrine/Tests/Mocks/StatementArrayMock.php
  tests/Doctrine/Tests/Mocks/StatementMock.php
  tests/Doctrine/Tests/Models/CMS/CmsGroup.php
Labels: Bug

#8896 Don't pass null as parameter
  lib/Doctrine/ORM/Query/Parser.php
Labels: Bug

#8907 Update getAssociationTargetClass phpdoc
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Bug

#8915 Address Type deprecation messages
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC425Test.php
  tests/Doctrine/Tests/ORM/Query/ParameterTypeInfererTest.php
Labels: Improvement

#8895 Implement __serialize() and __unserialize()
  lib/Doctrine/ORM/Id/SequenceGenerator.php
Labels: Improvement

#8928 Add types to `EM::wrapInTransaction()`
  lib/Doctrine/ORM/EntityManagerInterface.php
Labels: Improvement

#8938 Bump Psalm to 4.9.3
  composer.json
  psalm-baseline.xml
Labels: Improvement

#8939 Remove calls to `Driver::getName()`
  tests/Doctrine/Tests/Mocks/DriverMock.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/DDC214Test.php
Labels: Improvement

#8943 Add missing EntityManagerInterface argument to callable that is being passed to `EM::wrapInTransaction()`
  lib/Doctrine/ORM/EntityManagerInterface.php
Labels: Bug

#8916 Check current class' discriminator map
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8914Test.php
Labels: Bug

#8949 Make mock layer compatible with DBAL 3
  phpcs.xml.dist
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinArrayHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinFullObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryArrayHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryFullObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryScalarHydrationPerformanceBench.php
  tests/Doctrine/Tests/Mocks/ArrayResultFactory.php
  tests/Doctrine/Tests/Mocks/ClassMetadataMock.php
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/Mocks/DatabasePlatformMock.php
  tests/Doctrine/Tests/Mocks/DriverConnectionMock.php
  tests/Doctrine/Tests/Mocks/DriverMock.php
  tests/Doctrine/Tests/Mocks/DriverResultMock.php
  tests/Doctrine/Tests/Mocks/ExceptionConverterMock.php
  tests/Doctrine/Tests/Mocks/ResultMock.php
  tests/Doctrine/Tests/Mocks/ResultStatement.php
  tests/Doctrine/Tests/Mocks/SchemaManagerMock.php
  tests/Doctrine/Tests/Mocks/SequenceMock.php
  tests/Doctrine/Tests/Mocks/StatementArrayMock.php
  tests/Doctrine/Tests/Mocks/StatementMock.php
  tests/Doctrine/Tests/Mocks/TaskMock.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3634Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6362Test.php
  tests/Doctrine/Tests/ORM/Hydration/ArrayHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ScalarHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/SimpleObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/SingleScalarHydratorTest.php
  tests/Doctrine/Tests/ORM/Id/SequenceGeneratorTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: Improvement

#8935 Remove calls to deprecated Connection methods
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  psalm-baseline.xml
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/DetachedEntityTest.php
  tests/Doctrine/Tests/ORM/Functional/IdentityMapTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToManyBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToManySelfReferentialAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneEagerLoadingTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneSelfReferentialAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneUnidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/SequenceEmulatedIdentityStrategyTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1654Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3634Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC422Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7875Test.php
  tests/Doctrine/Tests/ORM/Functional/TypeValueSqlTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/ManyToManyCompositeIdForeignKeyTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/ManyToManyCompositeIdTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/ManyToManyExtraLazyTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/ManyToManyTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/OneToManyCompositeIdForeignKeyTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/OneToManyCompositeIdTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/OneToManyExtraLazyTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/OneToManyTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/OneToOneCompositeIdForeignKeyTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/OneToOneCompositeIdTest.php
  tests/Doctrine/Tests/ORM/Functional/ValueConversionType/OneToOneTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Improvement

#8954 Fix references to deprecated `DBALException`
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php
  tests/Doctrine/Tests/ORM/Functional/SchemaValidatorTest.php
Labels: Improvement

#8941 Remove calls to `fixSchemaElementName()`
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: Improvement

#8946 Support for DBAL 3's platform classes
  lib/Doctrine/ORM/Internal/SQLResultCasing.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Tools/Pagination/CountOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  phpstan-dbal3.neon
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/Mocks/DatabasePlatformMock.php
  tests/Doctrine/Tests/ORM/Functional/DatabaseDriverTest.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/DDC214Test.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/MySqlSchemaToolTest.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/PostgreSqlSchemaToolTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1151Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1360Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1695Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2182Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC832Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC933Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7875Test.php
  tests/Doctrine/Tests/ORM/Functional/UUIDGeneratorTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/CountOutputWalkerTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Improvement

#8962 Stop swallowing exceptions
  tests/Doctrine/Tests/ORM/Functional/DefaultValuesTest.php
  tests/Doctrine/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Doctrine/Tests/ORM/Functional/Locking/OptimisticTest.php
  tests/Doctrine/Tests/ORM/Functional/NotifyPolicyTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneSelfReferentialAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OrderedJoinedTableInheritanceCollectionTest.php
  tests/Doctrine/Tests/ORM/Functional/SequenceEmulatedIdentityStrategyTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1690Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC440Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8499Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/Ticket2481Test.php
Labels: Improvement

#8961 Deprecate / remove TABLE id generator strategy
  UPGRADE.md
  docs/en/reference/annotations-reference.rst
  docs/en/reference/attributes-reference.rst
  docs/en/reference/basic-mapping.rst
  doctrine-mapping.xsd
  lib/Doctrine/ORM/Id/TableGenerator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ORM/Mapping/Exception/CannotGenerateIds.php
  lib/Doctrine/ORM/Mapping/Exception/TableGeneratorNotImplementedYet.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/Export/Driver/AbstractExporter.php
  phpstan-baseline.neon
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
Labels: BC Break, Deprecation

#7495 Added clarification of using change tracking policy on entities with embeddables
  docs/en/reference/change-tracking-policies.rst
Labels: Documentation
