Repository doctrine/orm, pull requests merged in 2021-07, with the labels that each got.

#8813 Deprecate all things related to DB-generated UUIDs
  UPGRADE.md
  docs/en/reference/annotations-reference.rst
  docs/en/reference/attributes-reference.rst
  docs/en/reference/basic-mapping.rst
  lib/Doctrine/ORM/Id/UuidGenerator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/UUIDGeneratorTest.php
Labels: Deprecation

#8806 Resurrect phpbench
  .github/workflows/phpbench.yml
  composer.json
  phpbench.json
Labels: Backporting, CI

#8814 Proposed corrected typo in demo code.
  docs/en/tutorials/composite-primary-keys.rst
Labels: Backporting, Documentation

#8823 Referenced new support for PHP8 attributes
  docs/en/index.rst
  docs/en/reference/basic-mapping.rst
  docs/en/sidebar.rst
  docs/en/toc.rst
Labels: Documentation

#8825 Backport Github issue and PR templates
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Support_Question.md
  .github/PULL_REQUEST_TEMPLATE/Failing_Test.md
  .github/PULL_REQUEST_TEMPLATE/Improvement.md
  .github/PULL_REQUEST_TEMPLATE/New_Feature.md
Labels: Backporting

#8830 Adding `fields` to Index
  docs/en/reference/attributes-reference.rst
Labels: Documentation

#8835 [docs] Fix sentence about how nullable types affecting column definit…
  docs/en/reference/basic-mapping.rst
Labels: Documentation

#8842 Add documentation for ToolEvents
  docs/en/reference/events.rst
Labels: Backporting, Documentation

#8845 [CS] Clean elses
  lib/Doctrine/ORM/Internal/Hydration/IterableResult.php
  tests/Doctrine/Tests/Mocks/StatementArrayMock.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Backporting, Improvement

#8846 Use $strict param in functions that have it
  lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/SqlExpressionVisitor.php
  lib/Doctrine/ORM/Query/Expr/Base.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/ConvertDoctrine1Schema.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
  lib/Doctrine/ORM/Tools/Pagination/CountOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
  tests/Doctrine/Tests/ORM/Functional/DatabaseDriverTestCase.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1690Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2602Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3192Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6141Test.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Backporting

#8837 Replace spl_object_hash() with spl_object_id()
  composer.json
  lib/Doctrine/ORM/Cache/Persister/Collection/NonStrictReadWriteCachedCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Collection/ReadWriteCachedCollectionPersister.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php
  lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php
  lib/Doctrine/ORM/Tools/DebugUnitOfWorkListener.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/Mocks/UnitOfWorkMock.php
  tests/Doctrine/Tests/ORM/ORMInvalidArgumentExceptionTest.php
Labels: Backporting

#8838 Remove expensive array ops
  lib/Doctrine/ORM/Cache/DefaultCollectionHydrator.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Backporting

#8851 Remove unused exceptions
  UPGRADE.md
  lib/Doctrine/ORM/ORMException.php
Labels: BC Break, Backporting

#8319 Fix variadic args in Expr
  UPGRADE.md
  lib/Doctrine/ORM/Query/Expr.php
  lib/Doctrine/ORM/QueryBuilder.php
  phpstan-baseline.neon
Labels: BC Break

#8860 Fix typo in "Working with Objects"
  docs/en/reference/working-with-objects.rst
Labels: Documentation
