Repository doctrine/orm, pull requests merged in 2021-02, with the labels that each got.

#8434 fixed entity generation for numeric values
  lib/Doctrine/ORM/Tools/EntityGenerator.php
Labels: Missing Tests

#8401 Identifier type is not set when many2many relations are deleted
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
Labels: Bug

#8487 Update QueryBuilder::setParameters docs
  docs/en/reference/query-builder.rst
Labels: Documentation

#8493 Relax assertion
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php
Labels: Bug

#8483 Fix single scalar hydrator memory leak on exception
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  tests/Doctrine/Tests/ORM/Hydration/AbstractHydratorTest.php
Labels: Bug

#8497 note deprecation of AbstractQuery::iterator
  UPGRADE.md
Labels: Documentation

#8453 Fixes parenthesis when \n is involved
  lib/Doctrine/ORM/Query/Expr/Composite.php
  tests/Doctrine/Tests/ORM/Functional/QueryBuilderParenthesis.php
Labels: Bug

#8495 Fix bug when using Result Cache with Query::toIterable
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
Labels: Bug

#8508 Proposed fix for #8499
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/OptimisticLockException.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8499Test.php
Labels: Bug
