Repository doctrine/orm, pull requests merged in 2021-04, with the labels that each got.

#8590 Fix phpdoc of ClassMetadataInfo::getIdentifierValues
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Bug

#8591 Return case insensitive check
  lib/Doctrine/ORM/Query/Expr/Composite.php
  tests/Doctrine/Tests/ORM/Functional/AdvancedAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryBuilderParenthesisTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC69Test.php
Labels: Regression

#8586 Additional psalm param typehint for orderBy argument in findBy method
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php
Labels: Bug

#8593 [GH-8592] Deprecated Named (Native) Queries in Metadata/EntityRepository
  docs/en/reference/annotations-reference.rst
  docs/en/reference/native-sql.rst
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/NativeQueryTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1404Test.php
Labels: Deprecation

#8552 Fix remaining warnings from the phpunit9 upgrade
  tests/Doctrine/Tests/DoctrineTestCase.php
  tests/Doctrine/Tests/ORM/Cache/CacheLoggerChainTest.php
  tests/Doctrine/Tests/ORM/Cache/FileLockRegionTest.php
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2359Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6464Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8061Test.php
  tests/Doctrine/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Doctrine/Tests/ORM/Internal/HydrationCompleteHandlerTest.php
  tests/Doctrine/Tests/ORM/LazyCriteriaCollectionTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Mapping/Reflection/ReflectionPropertiesGetterTest.php
  tests/Doctrine/Tests/ORM/PersistentCollectionTest.php
  tests/Doctrine/Tests/ORM/Repository/DefaultRepositoryFactoryTest.php
  tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginatorTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
  tests/Doctrine/Tests/ORM/Utility/HierarchyDiscriminatorResolverTest.php
  tests/Doctrine/Tests/PHPUnit8PolyfilledTestCase.php
  tests/Doctrine/Tests/PolyfillableTestCase.php
Labels: Improvement

#8605 Document actual return types
  composer.json
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php
  phpcs.xml.dist
Labels: Bug

#8604 Fix psalm param typehint for OneToManyAssociationBuilder::setOrderBy method
  lib/Doctrine/ORM/Mapping/Builder/OneToManyAssociationBuilder.php
Labels: Bug

#8617 Upgrade to doctrine/coding-standard 9
  composer.json
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/HydrationException.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/OneToManyAssociationBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ORM/Mapping/Reflection/ReflectionPropertiesGetter.php
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php
  lib/Doctrine/ORM/Persisters/SqlValueVisitor.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  lib/Doctrine/ORM/Query/Expr/Base.php
  lib/Doctrine/ORM/Query/Expr/Func.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/QueryException.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/TreeWalker.php
  lib/Doctrine/ORM/Query/TreeWalkerChainIterator.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/ConvertDoctrine1Schema.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/Export/Driver/AbstractExporter.php
  lib/Doctrine/ORM/Tools/Export/Driver/PhpExporter.php
  lib/Doctrine/ORM/Tools/Export/Driver/YamlExporter.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/ResolveTargetEntityListener.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  lib/Doctrine/ORM/UnitOfWork.php
  lib/Doctrine/ORM/Utility/HierarchyDiscriminatorResolver.php
  phpcs.xml.dist
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1884Test.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: Improvement

#8524 [GH-8327] Deprecate EntityManagerHelper for a provider abstraction.
  lib/Doctrine/ORM/Tools/Console/Command/AbstractEntityManagerCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/CollectionRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/EntityRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertMappingCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/EnsureProductionSettingsCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateEntitiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateRepositoriesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/InfoCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/CreateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/DropCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/ConnectionFromManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/HelperSetManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/SingleManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/UnknownManagerException.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ClearCacheCollectionRegionCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ClearCacheEntityRegionCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ClearCacheQueryRegionCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/EnsureProductionSettingsCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/GenerateRepositoriesCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/InfoCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/MappingDescribeCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/RunDqlCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/ConsoleRunnerTest.php
Labels: Deprecation

#8548 Adding details to types in PHPDoc
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/CacheConfiguration.php
  lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Logging/CacheLoggerChain.php
  lib/Doctrine/ORM/Cache/Logging/StatisticsCacheLogger.php
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Cache/Region/FileLockRegion.php
  lib/Doctrine/ORM/Cache/RegionsConfiguration.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Event/ListenersInvoker.php
  lib/Doctrine/ORM/Event/OnClassMetadataNotFoundEventArgs.php
  lib/Doctrine/ORM/Event/OnClearEventArgs.php
  lib/Doctrine/ORM/Event/OnFlushEventArgs.php
  lib/Doctrine/ORM/Internal/CommitOrderCalculator.php
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/EntityListenerBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ORM/Mapping/Reflection/ReflectionPropertiesGetter.php
  lib/Doctrine/ORM/OptimisticLockException.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/SqlExpressionVisitor.php
  lib/Doctrine/ORM/Persisters/SqlValueVisitor.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/AST/Functions/TrimFunction.php
  lib/Doctrine/ORM/Query/AST/OrderByClause.php
  lib/Doctrine/ORM/Query/Expr/Base.php
  lib/Doctrine/ORM/Query/Expr/OrderBy.php
  lib/Doctrine/ORM/Query/FilterCollection.php
  lib/Doctrine/ORM/Query/Parameter.php
  lib/Doctrine/ORM/Query/ParameterTypeInferer.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/QueryExpressionVisitor.php
  lib/Doctrine/ORM/Query/ResultSetMapping.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/EntityRepositoryGenerator.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
Labels: Improvement

#8544 Add type declarations where backwards-compatible
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/DefaultCache.php
  lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Cache/Persister/Entity/NonStrictReadWriteCachedEntityPersister.php
  lib/Doctrine/ORM/Cache/Region/FileLockRegion.php
  lib/Doctrine/ORM/Cache/TimestampQueryCacheValidator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Event/PreUpdateEventArgs.php
  lib/Doctrine/ORM/Internal/CommitOrderCalculator.php
  lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ORM/Mapping/Reflection/ReflectionPropertiesGetter.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/AST/Functions/TrimFunction.php
  lib/Doctrine/ORM/Query/Expr/Composite.php
  lib/Doctrine/ORM/Query/Filter/SQLFilter.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/ConvertDoctrine1Schema.php
  lib/Doctrine/ORM/Tools/DebugUnitOfWorkListener.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/EntityRepositoryGenerator.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/Tools/ResolveTargetEntityListener.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/UnitOfWork.php
  lib/Doctrine/ORM/Utility/IdentifierFlattener.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Improvement

#7608 Avoid unnecessary flush after processing first row
  docs/en/reference/batch-processing.rst
Labels: Documentation

#8654 Removed EntityManagerInteface::copy()
  UPGRADE.md
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
Labels: BC Break

#8201 Throw Exception when unable to locate identifier
  lib/Doctrine/ORM/EntityNotFoundException.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/EntityNotFoundExceptionTest.php
Labels: Improvement

#8659 Make tests independent
  tests/Doctrine/Tests/ORM/Functional/ExtraLazyCollectionTest.php
  tests/Doctrine/Tests/ORM/Functional/IdentityMapTest.php
Labels: Improvement
