Repository doctrine/orm, pull requests merged in 2021-06, with the labels that each got.

#8747 Use correct named argument syntax in docs
  docs/en/reference/attributes-reference.rst
Labels: Documentation

#8402 Resolving target entity in discriminator map omits fields from subtables
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Tools/ResolveTargetEntityListener.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3300Test.php
Labels: Bug

#8790 Backport docs batch
  LICENSE
  composer.json
  docs/en/cookbook/implementing-wakeup-or-clone.rst
  docs/en/reference/annotations-reference.rst
  docs/en/reference/association-mapping.rst
  docs/en/reference/attributes-reference.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/batch-processing.rst
  docs/en/reference/caching.rst
  docs/en/reference/dql-doctrine-query-language.rst
  docs/en/reference/inheritance-mapping.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/second-level-cache.rst
  docs/en/reference/transactions-and-concurrency.rst
  docs/en/reference/unitofwork-associations.rst
  docs/en/reference/working-with-associations.rst
  docs/en/reference/working-with-objects.rst
  docs/en/tutorials/getting-started.rst
  docs/en/tutorials/pagination.rst
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/LazyCriteriaCollection.php
  lib/Doctrine/ORM/Query/AST/InExpression.php
Labels: Backporting, Documentation

#8793 Backport slamdunk's work
  lib/Doctrine/ORM/Cache/DefaultCache.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Lock.php
  lib/Doctrine/ORM/Cache/Logging/CacheLogger.php
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/CollectionRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/EntityRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/InfoCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/CreateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/DropCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  tests/Doctrine/Tests/Models/Company/CompanyEvent.php
  tests/Doctrine/Tests/Models/DDC964/DDC964Guest.php
Labels: Backporting, Improvement

#8792 Backport malukenho's work
  lib/Doctrine/ORM/Cache/Lock.php
  lib/Doctrine/ORM/Cache/Logging/CacheLoggerChain.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php
  lib/Doctrine/ORM/Persisters/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Persisters/Collection/CollectionPersister.php
  lib/Doctrine/ORM/PessimisticLockException.php
  lib/Doctrine/ORM/Query/AST/BetweenExpression.php
  lib/Doctrine/ORM/Query/AST/Functions/ConcatFunction.php
  lib/Doctrine/ORM/Query/AST/GroupByClause.php
  lib/Doctrine/ORM/Query/AST/HavingClause.php
  lib/Doctrine/ORM/Query/Filter/SQLFilter.php
  lib/Doctrine/ORM/Query/QueryExpressionVisitor.php
  tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php
Labels: Backporting, Improvement

#8791 Backport docs batch 2
  docs/LICENSE.md
  docs/en/cookbook/advanced-field-value-conversion-using-custom-mapping-types.rst
  docs/en/cookbook/decorator-pattern.rst
  docs/en/cookbook/dql-custom-walkers.rst
  docs/en/cookbook/dql-user-defined-functions.rst
  docs/en/cookbook/implementing-arrayaccess-for-domain-objects.rst
  docs/en/cookbook/implementing-the-notify-changetracking-policy.rst
  docs/en/cookbook/implementing-wakeup-or-clone.rst
  docs/en/cookbook/working-with-datetime.rst
  docs/en/reference/advanced-configuration.rst
  docs/en/reference/architecture.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/caching.rst
  docs/en/reference/configuration.rst
  docs/en/reference/dql-doctrine-query-language.rst
  docs/en/reference/events.rst
  docs/en/reference/faq.rst
  docs/en/reference/improving-performance.rst
  docs/en/reference/inheritance-mapping.rst
  docs/en/reference/limitations-and-known-issues.rst
  docs/en/reference/second-level-cache.rst
  docs/en/reference/security.rst
  docs/en/reference/xml-mapping.rst
  docs/en/tutorials/composite-primary-keys.rst
  docs/en/tutorials/extra-lazy-associations.rst
  docs/en/tutorials/getting-started.rst
  docs/en/tutorials/working-with-indexed-associations.rst
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Persisters/Entity/SingleTablePersister.php
Labels: Backporting, Documentation

#8794 Fix deprecated DBAL calls
  composer.json
  lib/Doctrine/ORM/Id/SequenceGenerator.php
  lib/Doctrine/ORM/Id/TableGenerator.php
  lib/Doctrine/ORM/Id/UuidGenerator.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/Exec/MultiTableUpdateExecutor.php
  lib/Doctrine/ORM/Query/Exec/SingleTableDeleteUpdateExecutor.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/Mocks/StatementMock.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
  tests/Doctrine/Tests/ORM/Persisters/ManyToManyPersisterTest.php
Labels: Improvement

#8789 Use a more concrete, less confusing example
  docs/en/reference/inheritance-mapping.rst
Labels: Backporting, Documentation

#8795 Update session examples in docs
  docs/en/cookbook/entities-in-session.rst
Labels: Documentation

#8800 Fix exception not thrown by "getEntityIdentifier"
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Bug

#8799 Combine consecutive issets and unsets
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryCriteriaTest.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/ManyToManyBasicAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/PersistentCollectionCriteriaTest.php
Labels: Backporting, Improvement

#8798 Remove hack to access class scope inside closures
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3123Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3644Test.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: Backporting, Improvement

#8801 Ignore errors about missing ReturnTypeWillChange class
  .github/workflows/static-analysis.yml
  phpstan.neon
  psalm.xml
Labels: Bug

#8796 Migrate hydrators and queries to DBAL's new Result interface
  UPGRADE.md
  composer.json
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ScalarHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/SingleScalarHydrator.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  lib/Doctrine/ORM/Query/Exec/MultiTableDeleteExecutor.php
  lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php
  phpstan-baseline.neon
  psalm.xml
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinArrayHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinFullObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryArrayHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryFullObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryScalarHydrationPerformanceBench.php
  tests/Doctrine/Tests/Mocks/HydratorMockResult.php
  tests/Doctrine/Tests/Mocks/HydratorMockStatement.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6362Test.php
  tests/Doctrine/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ArrayHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/CustomHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ScalarHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/SimpleObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/SingleScalarHydratorTest.php
Labels: Improvement
