Repository doctrine/orm, pull requests merged in 2021-05, with the labels that each got.

#8651 Introduce PSR-6 for metadata caching
  composer.json
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManager.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/Locking/LockAgentWorker.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Deprecation, New Feature

#8673 Add hint for ->iterate() deprecation
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Documentation

#8672 Allow installing doctrine/cache 2.0
  UPGRADE.md
  composer.json
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ORM/Tools/Setup.php
  tests/Doctrine/Tests/ORM/Cache/AbstractRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionTest.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/HydrationCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Locking/LockAgentWorker.php
  tests/Doctrine/Tests/ORM/Functional/QueryCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2224Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC742Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/ORM/Tools/SetupTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Improvement

#8691 Check for use of deprecated API with Psalm
  psalm-baseline.xml
  psalm.xml
Labels: CI

#8700 Fix undefined index
  lib/Doctrine/ORM/Tools/ConvertDoctrine1Schema.php
Labels: Bug

#8701 Allow Symfony 6.0
  composer.json
Labels: CI

#8722 Fix metadata cache compatibility layer
  composer.json
  lib/Doctrine/ORM/Configuration.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
Labels: Bug

#8710 Handle generic parameters in UnitOfWork
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Bug

#8704 Update inheritance-mapping.rst
  docs/en/reference/inheritance-mapping.rst
Labels: Documentation

#8728 Remove flush($argument) from documentation as it's deprecated.
  docs/en/cookbook/implementing-the-notify-changetracking-policy.rst
  docs/en/reference/change-tracking-policies.rst
  docs/en/reference/partial-objects.rst
  docs/en/reference/unitofwork.rst
Labels: Documentation
