Repository doctrine/orm, pull requests merged in 2021-09, with the labels that each got.

#8996 Support for PSR-6 result caches
  .github/workflows/continuous-integration.yml
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/Exception/InvalidResultCacheDriver.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
  phpstan-dbal2.neon
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
  tests/Doctrine/Tests/ORM/Functional/HydrationCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Improvement

#9001 Remove Proxy from EntityManagerInterface contract
  lib/Doctrine/ORM/EntityManagerInterface.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Bug

#9004 Use PSR-6 for accessing the query cache
  lib/Doctrine/ORM/Query.php
  tests/Doctrine/Tests/ORM/Functional/QueryCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2224Test.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: Improvement, Deprecation

#9009 Document fluent interfaces
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Mapping/Builder/AssociationBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/FieldBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ManyToManyAssociationBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/OneToManyAssociationBuilder.php
  lib/Doctrine/ORM/NativeQuery.php
  lib/Doctrine/ORM/Query/Expr/Base.php
  lib/Doctrine/ORM/Query/Filter/SQLFilter.php
  lib/Doctrine/ORM/Query/ResultSetMapping.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/EntityRepositoryGenerator.php
Labels: Improvement

#9010 Fix ignoring custom types for PersistentCollection matching()
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  tests/Doctrine/Tests/ORM/Functional/PersistentCollectionCriteriaTest.php
Labels: Bug

#9017 Fix some typehints in QueryBuilder
  lib/Doctrine/ORM/QueryBuilder.php
Labels: Improvement

#9028 Don't presume one-to-one lookup returned an entity
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9027Test.php
Labels: Bug

#8435 Minor rewording
  docs/en/reference/events.rst
Labels: Documentation

#9050 fix: prevent TypeError in QueryBuilder joins
  lib/Doctrine/ORM/QueryBuilder.php
  tests/Doctrine/Tests/ORM/QueryBuilderTest.php
Labels: Bug

#9043 Update documentation regarding caching
  docs/en/reference/advanced-configuration.rst
  docs/en/reference/caching.rst
  docs/en/reference/improving-performance.rst
Labels: Documentation
