Repository doctrine/orm, pull requests merged in 2021-11, with the labels that each got.

#9166 Remove reverted bc break
  UPGRADE.md
Labels: Documentation

#9159 Merging Lifecycle Callbacks code samples for PHP + XML + YAML
  docs/en/reference/events.rst
Labels: Documentation

#9167 PHPStan 1.0.1
  composer.json
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Column.php
  lib/Doctrine/ORM/Query/Parser.php
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  tests/Doctrine/StaticAnalysis/get-metadata.php
Labels: Improvement

#9154 Fixing more links
  docs/en/reference/architecture.rst
  docs/en/reference/events.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#9160 Merging two ~identical lists on event types
  docs/en/reference/events.rst
Labels: Documentation

#9153 Infer type from field instead of column
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9109Test.php
Labels: Failing Test, Bug

#9168 Fix discriminatorColumn phpdoc
  lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Persisters/Entity/AbstractEntityInheritancePersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Persisters/Entity/SingleTablePersister.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
Labels: Bug

#9161 Adding Attributes code block
  docs/en/reference/events.rst
Labels: Documentation

#9195 Use `equal to` instead of `equal of` in `assertSqlGeneration()`
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
Labels: CI

#9198 Add a psalm type for field mapping
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  phpstan-baseline.neon
Labels: Bug

#9203 Drop support for DBAL 3.1
  composer.json
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Internal/SQLResultCasing.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Query/AST/Functions/LowerFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/SqrtFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/UpperFunction.php
  lib/Doctrine/ORM/Tools/Pagination/CountOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  phpstan-dbal2.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/DatabaseDriverTest.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/PostgreSqlSchemaToolTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1151Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1360Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2012Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7875Test.php
  tests/Doctrine/Tests/ORM/Functional/UUIDGeneratorTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/CountOutputWalkerTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Improvement

#9212 Suppress Psalm's ReservedWord errors
  psalm.xml
Labels: CI
