Repository doctrine/orm, pull requests merged in 2021-10, with the labels that each got.

#9056 Remove calls to `ForeignKeyConstraint::getColumns()`
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
Labels: Improvement

#9006 Add PHP 8.1 to CI
  .github/workflows/continuous-integration.yml
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7941Test.php
Labels: CI

#9045 Remove TABLE and UUID strategies
  UPGRADE.md
  lib/Doctrine/ORM/Id/TableGenerator.php
  lib/Doctrine/ORM/Id/UuidGenerator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/Export/Driver/AbstractExporter.php
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/Functional/UUIDGeneratorTest.php
  tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
Labels: BC Break

#9057 Add PHP 8.1 to CI
  .github/workflows/continuous-integration.yml
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7941Test.php
Labels: CI

#9058 Run PHP 8.1 CI with stable dependencies
  .github/workflows/continuous-integration.yml
Labels: CI

#9046 Deprecate isIdGeneratorTable and isIdentifierUuid
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Deprecation

#9061 Revert to older automatic releases
  .github/workflows/release-on-milestone-closed.yml
Labels: CI

#9070 Remove `Query::iterate()`
  UPGRADE.md
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/IterableResult.php
  lib/Doctrine/ORM/Query.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC309Test.php
  tests/Doctrine/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ArrayHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: BC Break

#9069 Remove support for DBAL 2
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  composer.json
  docs/en/reference/tools.rst
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/SQLResultCasing.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertMappingCommand.php
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  phpcs.xml.dist
  phpstan-dbal2.neon
  phpstan.neon
  psalm.xml
  tests/Doctrine/Tests/Mocks/ArrayResultFactory.php
  tests/Doctrine/Tests/Mocks/CacheRegionMock.php
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/Mocks/DatabasePlatformMock.php
  tests/Doctrine/Tests/Mocks/DriverConnectionMock.php
  tests/Doctrine/Tests/Mocks/DriverMock.php
  tests/Doctrine/Tests/Mocks/DriverResultMock.php
  tests/Doctrine/Tests/Mocks/ResultMock.php
  tests/Doctrine/Tests/Mocks/ResultStatement.php
  tests/Doctrine/Tests/Mocks/StatementMock.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1734Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7875Test.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Improvement

#9072 Deprecate `AbstractHydrator::hydrateRow()`
  UPGRADE.md
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  psalm.xml
Labels: Deprecation

#9074 Deprecate `ensureProductionSettings()`
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Tools/Console/Command/EnsureProductionSettingsCommand.php
  psalm.xml
Labels: Deprecation

#9076 Remove AbstractHydrator::hydrateRow()
  UPGRADE.md
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  psalm.xml
Labels: BC Break

#9084 Update phpdoc comment - association-mapping.rst
  docs/en/reference/association-mapping.rst
Labels: Documentation

#9079 Add integer cast in setMaxResults methods of Query and QueryBuilder
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/QueryBuilder.php
  psalm.xml
Labels: Bug

#9090 Add integer cast in setFirstResult methods of Query and QueryBuilder
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/QueryBuilder.php
Labels: Bug

#9143 Document BC break
  UPGRADE.md
Labels: Documentation
