Repository doctrine/orm, pull requests merged in 2022-05, with the labels that each got.

#9703 Update ClassMetadataInfo::table definition
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9707 Remove some ConnectionMock methods
  lib/Doctrine/ORM/Id/SequenceGenerator.php
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/ORM/Id/SequenceGeneratorTest.php
Labels: Test Suite

#9705 Remove support for Type::canRequireSQLConversion()
  UPGRADE.md
  docs/en/cookbook/advanced-field-value-conversion-using-custom-mapping-types.rst
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  lib/Doctrine/ORM/Persisters/Entity/AbstractEntityInheritancePersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  psalm-baseline.xml
  tests/Doctrine/Tests/DbalTypes/NegativeToPositiveType.php
  tests/Doctrine/Tests/DbalTypes/UpperCaseStringType.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2012Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2224Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC5684Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8061Test.php
  tests/Doctrine/Tests/ORM/Functional/TypeValueSqlTest.php
Labels: BC Break

#9706 Remove unused OrmTestCase::getTestEntityManager() parameters
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Test Suite

#9704 Reference ClassMetadataInfo less and less
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/ConvertDoctrine1Schema.php
  lib/Doctrine/ORM/Tools/DisconnectedClassMetadataFactory.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  psalm-baseline.xml
Labels: Deprecation

#9709 Remove non-API DriverConnectionMock methods
  tests/Doctrine/Tests/Mocks/DriverConnectionMock.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Test Suite

#9715 Remove some mock classes
  tests/Doctrine/Performance/ArrayResultFactory.php
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinArrayHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinFullObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryArrayHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryFullObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryScalarHydrationPerformanceBench.php
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/Mocks/DriverConnectionMock.php
  tests/Doctrine/Tests/Mocks/DriverMock.php
  tests/Doctrine/Tests/Mocks/StatementMock.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6362Test.php
  tests/Doctrine/Tests/ORM/Hydration/ArrayHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/HydrationTestCase.php
  tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ScalarColumnHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ScalarHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/SimpleObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/SingleScalarHydratorTest.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Test Suite

#9718 Psalm 4.23, PHPStan 1.6.3
  composer.json
  psalm-baseline.xml
Labels: Static Analysis

#9716 Remove DatabasePlatformMock
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/Mocks/DatabasePlatformMock.php
  tests/Doctrine/Tests/ORM/Id/SequenceGeneratorTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginatorTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Test Suite

#9717 Remove ConnectionMock::delete()
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
Labels: Test Suite

#9722 Remove DriverResultMock
  tests/Doctrine/Performance/EntityManagerFactory.php
  tests/Doctrine/Tests/Mocks/DriverResultMock.php
Labels: Test Suite

#9655 Allow setting column options like `charset` and `collation` on `JoinTable`, `JoinColumn` and `InverseJoinColumn`
  docs/en/reference/attributes-reference.rst
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/InverseJoinColumn.php
  lib/Doctrine/ORM/Mapping/JoinColumn.php
  lib/Doctrine/ORM/Mapping/JoinTable.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6823Test.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeReaderTest.php
Labels: New Feature

#9713 Remove last references to ClassMetadataInfo
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Tools/DisconnectedClassMetadataFactory.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  phpstan-baseline.neon
  tests/Doctrine/Tests/ORM/Tools/Console/MetadataFilterTest.php
Labels: BC Break

#9723 Allow doctrine/deprecations 1.0
  composer.json
Labels: Improvement

#9724 Remove ConnectionMock
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
  tests/Doctrine/Tests/ORM/Persisters/ManyToManyPersisterTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginatorTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Test Suite

#9728 Test MySQL DDL using explicit table options
  ci/github/phpunit/mysqli.xml
  ci/github/phpunit/pdo_mysql.xml
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/MySqlSchemaToolTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2182Test.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Test Suite

#9730 Forward compatibility with DBAL 4
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/DbalTypes/CustomIdObjectType.php
  tests/Doctrine/Tests/DbalTypes/Rot13Type.php
  tests/Doctrine/Tests/ORM/Functional/GH5988Test.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/DDC214Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2012Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2224Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC5684Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH5804Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8061Test.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Improvement

#9734 Build with DBAL 4@dev on SQLite
  .github/workflows/continuous-integration.yml
Labels: CI

#9742 Run static analysis with DBAL 4@dev
  .github/workflows/static-analysis.yml
  composer.json
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Query/AST/Functions/DateAddFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/DateSubFunction.php
  phpstan-baseline.neon
  phpstan-dbal4.neon
  psalm.xml
Labels: Static Analysis

#9746 Better phpdoc tests
  tests/Doctrine/Tests/ORM/Mapping/NamingStrategyTest.php
Labels: Static Analysis

#9747 Deprecate omitting second argument to joinColumnName()
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/DefaultNamingStrategy.php
  lib/Doctrine/ORM/Mapping/NamingStrategy.php
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
Labels: Deprecation

#9749 Omit version number in README
  README.md
Labels: Documentation

#9751 Update Psalm baseline
  psalm-baseline.xml
Labels: Static Analysis

#9741 Make UnderscoreNamingStrategy number-aware only
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/NamingStrategyTest.php
  tests/Doctrine/Tests/ORM/Mapping/UnderscoreNamingStrategyTest.php
Labels: BC Break

#9756 Document types as they are passed
  lib/Doctrine/ORM/Mapping/NamingStrategy.php
  psalm.xml
Labels: Static Analysis

#9769 Add use statement
  docs/en/reference/php-mapping.rst
Labels: Documentation

#9755 Require new argument to joinColumnName()
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/DefaultNamingStrategy.php
  lib/Doctrine/ORM/Mapping/NamingStrategy.php
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: BC Break

#9779 Document callable as possible
  lib/Doctrine/ORM/Configuration.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9780 Kill call_user_func(_array)
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Mapping/Reflection/ReflectionPropertiesGetter.php
  lib/Doctrine/ORM/Query/Parser.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3634Test.php
Labels: Improvement

#9785 PHPStan 1.7.0
  composer.json
  phpstan-dbal2.neon
  phpstan-persistence2.neon
  phpstan.neon
Labels: Static Analysis

#9777 Make phpdoc more precise for AbstractQuery
  UPGRADE.md
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/AST/Functions/FunctionNode.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
Labels: Deprecation

#9790 MockTreeWalker should be an SqlWalker
  tests/Doctrine/Tests/Mocks/MockTreeWalker.php
  tests/Doctrine/Tests/Mocks/NullSqlWalker.php
  tests/Doctrine/Tests/ORM/Query/LanguageRecognitionTest.php
Labels: Test Suite

#9789 Move duplicate fixture into dedicated file
  tests/Doctrine/Tests/Mocks/CustomTreeWalkerJoin.php
  tests/Doctrine/Tests/ORM/Query/CustomTreeWalkersJoinTest.php
  tests/Doctrine/Tests/ORM/Query/CustomTreeWalkersTest.php
Labels: Test Suite

#9791 Deprecate calling setters without arguments
  UPGRADE.md
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Event/OnClassMetadataNotFoundEventArgs.php
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
Labels: Deprecation

#9778 Precise phpdoc of getRootEntities
  lib/Doctrine/ORM/Query/Expr/From.php
  lib/Doctrine/ORM/QueryBuilder.php
Labels: Static Analysis

#9796 Add missing import
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
Labels: Test Suite

#9798 Made setters parameters mandatory
  UPGRADE.md
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Event/OnClassMetadataNotFoundEventArgs.php
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: BC Break
