Repository doctrine/orm, pull requests merged in 2022-08, with the labels that each got.

#9945 Deprecate QueryBuilder APIs exposing its internal state
  UPGRADE.md
  lib/Doctrine/ORM/QueryBuilder.php
  psalm.xml
Labels: Deprecation

#9950 Fix DBAL 4 compatibility
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/AST/Functions/TrimFunction.php
  lib/Doctrine/ORM/Query/ParameterTypeInferer.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Performance/Mock/NonLoadingPersister.php
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Doctrine/Tests/Mocks/CompatibilityType.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9335Test.php
  tests/Doctrine/Tests/ORM/Query/ParameterTypeInfererTest.php
Labels: Bug, BC Break

#9925 Require PHP 8.1
  .github/workflows/continuous-integration.yml
  .github/workflows/phpbench.yml
  composer.json
  phpcs.xml.dist
Labels: Improvement

#9954 Remove obsolete PHP version checks
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  tests/Doctrine/Tests/Mocks/CompatibilityType.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php
  tests/Doctrine/Tests/ORM/Query/ParameterTypeInfererTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: Improvement

#9936 Support native enum hydration when using `NEW` operator
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  tests/Doctrine/Tests/Models/DataTransferObjects/DtoWithArrayOfEnums.php
  tests/Doctrine/Tests/Models/DataTransferObjects/DtoWithEnum.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: New Feature

#9956 Flag properties as readonly if possible
  lib/Doctrine/ORM/Cache/DefaultCache.php
  lib/Doctrine/ORM/Cache/DefaultCollectionHydrator.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Region/DefaultRegion.php
  lib/Doctrine/ORM/Cache/Region/FileLockRegion.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php
  lib/Doctrine/ORM/Mapping/ReflectionEmbeddedProperty.php
  lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php
  lib/Doctrine/ORM/Mapping/ReflectionReadonlyProperty.php
  lib/Doctrine/ORM/Query/Filter/SQLFilter.php
  lib/Doctrine/ORM/Query/FilterCollection.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Query/TreeWalkerAdapter.php
  lib/Doctrine/ORM/Query/TreeWalkerChain.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/Console/Command/AbstractEntityManagerCommand.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/ConnectionFromManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/SingleManagerProvider.php
  lib/Doctrine/ORM/Tools/DebugUnitOfWorkListener.php
  lib/Doctrine/ORM/Tools/Event/GenerateSchemaEventArgs.php
  lib/Doctrine/ORM/Tools/Event/GenerateSchemaTableEventArgs.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  lib/Doctrine/ORM/UnitOfWork.php
  lib/Doctrine/ORM/Utility/IdentifierFlattener.php
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Doctrine/Tests/DbalExtensions/SqlLogger.php
  tests/Doctrine/Tests/Mocks/ConcurrentRegionMock.php
  tests/Doctrine/Tests/ORM/Cache/FileLockRegionTest.php
Labels: Improvement

#9959 Use intersection types in tests
  phpcs.xml.dist
  tests/Doctrine/Tests/ORM/Cache/CacheLoggerChainTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheFactoryTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/CollectionPersisterTestCase.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/ReadWriteCachedCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/EntityPersisterTestCase.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Doctrine/Tests/ORM/Internal/HydrationCompleteHandlerTest.php
  tests/Doctrine/Tests/ORM/LazyCriteriaCollectionTest.php
  tests/Doctrine/Tests/ORM/Repository/DefaultRepositoryFactoryTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginatorTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Test Suite

#9957 Drop unmaintained Symfony versions
  composer.json
Labels: Improvement

#9953 Resolve QueryBuilder deprecations
  UPGRADE.md
  lib/Doctrine/ORM/Internal/QueryType.php
  lib/Doctrine/ORM/QueryBuilder.php
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/QueryBuilderTest.php
Labels: BC Break

#9964 Psalm 4.26.0 & build failures with DBAL 3.4.0
  composer.json
  phpstan-baseline.neon
  phpstan-dbal2.neon
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#9965 Improve phpdoc for ClassMetadataInfo
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  psalm-baseline.xml
Labels: Static Analysis

#9969 Address DBAL 3.4 deprecations
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  psalm.xml
Labels: Improvement

#9968 Stabilize the DBAL dependency
  composer.json
Labels: Improvement

#9963 Flag QueryType as internal
  lib/Doctrine/ORM/Internal/QueryType.php
Labels: Documentation

#9972 Remove calls to deprecated `Type::getName()`
  psalm.xml
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2984Test.php
Labels: Test Suite

#9971 Update branch metadata
  .doctrine-project.json
  README.md
Labels: Documentation

#9962 Add types to ProxyFactory
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  psalm-baseline.xml
Labels: BC Break

#9974 Update Psalm config
  psalm.xml
Labels: Static Analysis

#9979 Update documentation to not use deprecated method
  docs/en/reference/events.rst
Labels: Documentation

#9980 Undeprecate LifecycleEventArgs
  UPGRADE.md
  docs/en/cookbook/strategy-cookbook-introduction.rst
  docs/en/reference/events.rst
  lib/Doctrine/ORM/Event/LifecycleEventArgs.php
  psalm.xml
  tests/Doctrine/Tests/Models/Company/CompanyFlexUltraContractListener.php
  tests/Doctrine/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Doctrine/Tests/ORM/Functional/PostLoadEventTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2602Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3033Test.php
Labels: Deprecation

#9977 Backport type fixes for EntityListenerResolver
  lib/Doctrine/ORM/Event/ListenersInvoker.php
  lib/Doctrine/ORM/Mapping/EntityListenerResolver.php
  psalm-baseline.xml
Labels: Static Analysis

#9978 Add types to `Node::dispatch()`
  lib/Doctrine/ORM/Query/AST/AggregateExpression.php
  lib/Doctrine/ORM/Query/AST/ArithmeticExpression.php
  lib/Doctrine/ORM/Query/AST/ArithmeticFactor.php
  lib/Doctrine/ORM/Query/AST/ArithmeticTerm.php
  lib/Doctrine/ORM/Query/AST/BetweenExpression.php
  lib/Doctrine/ORM/Query/AST/CoalesceExpression.php
  lib/Doctrine/ORM/Query/AST/CollectionMemberExpression.php
  lib/Doctrine/ORM/Query/AST/ComparisonExpression.php
  lib/Doctrine/ORM/Query/AST/ConditionalExpression.php
  lib/Doctrine/ORM/Query/AST/ConditionalFactor.php
  lib/Doctrine/ORM/Query/AST/ConditionalPrimary.php
  lib/Doctrine/ORM/Query/AST/ConditionalTerm.php
  lib/Doctrine/ORM/Query/AST/DeleteClause.php
  lib/Doctrine/ORM/Query/AST/DeleteStatement.php
  lib/Doctrine/ORM/Query/AST/EmptyCollectionComparisonExpression.php
  lib/Doctrine/ORM/Query/AST/ExistsExpression.php
  lib/Doctrine/ORM/Query/AST/FromClause.php
  lib/Doctrine/ORM/Query/AST/Functions/FunctionNode.php
  lib/Doctrine/ORM/Query/AST/GeneralCaseExpression.php
  lib/Doctrine/ORM/Query/AST/GroupByClause.php
  lib/Doctrine/ORM/Query/AST/HavingClause.php
  lib/Doctrine/ORM/Query/AST/IdentificationVariableDeclaration.php
  lib/Doctrine/ORM/Query/AST/InExpression.php
  lib/Doctrine/ORM/Query/AST/IndexBy.php
  lib/Doctrine/ORM/Query/AST/InputParameter.php
  lib/Doctrine/ORM/Query/AST/InstanceOfExpression.php
  lib/Doctrine/ORM/Query/AST/Join.php
  lib/Doctrine/ORM/Query/AST/JoinAssociationDeclaration.php
  lib/Doctrine/ORM/Query/AST/JoinClassPathExpression.php
  lib/Doctrine/ORM/Query/AST/JoinVariableDeclaration.php
  lib/Doctrine/ORM/Query/AST/LikeExpression.php
  lib/Doctrine/ORM/Query/AST/Literal.php
  lib/Doctrine/ORM/Query/AST/NewObjectExpression.php
  lib/Doctrine/ORM/Query/AST/Node.php
  lib/Doctrine/ORM/Query/AST/NullComparisonExpression.php
  lib/Doctrine/ORM/Query/AST/NullIfExpression.php
  lib/Doctrine/ORM/Query/AST/OrderByClause.php
  lib/Doctrine/ORM/Query/AST/OrderByItem.php
  lib/Doctrine/ORM/Query/AST/ParenthesisExpression.php
  lib/Doctrine/ORM/Query/AST/PathExpression.php
  lib/Doctrine/ORM/Query/AST/QuantifiedExpression.php
  lib/Doctrine/ORM/Query/AST/RangeVariableDeclaration.php
  lib/Doctrine/ORM/Query/AST/SelectClause.php
  lib/Doctrine/ORM/Query/AST/SelectExpression.php
  lib/Doctrine/ORM/Query/AST/SelectStatement.php
  lib/Doctrine/ORM/Query/AST/SimpleArithmeticExpression.php
  lib/Doctrine/ORM/Query/AST/SimpleCaseExpression.php
  lib/Doctrine/ORM/Query/AST/SimpleSelectClause.php
  lib/Doctrine/ORM/Query/AST/SimpleSelectExpression.php
  lib/Doctrine/ORM/Query/AST/SimpleWhenClause.php
  lib/Doctrine/ORM/Query/AST/Subselect.php
  lib/Doctrine/ORM/Query/AST/SubselectFromClause.php
  lib/Doctrine/ORM/Query/AST/UpdateClause.php
  lib/Doctrine/ORM/Query/AST/UpdateItem.php
  lib/Doctrine/ORM/Query/AST/UpdateStatement.php
  lib/Doctrine/ORM/Query/AST/WhenClause.php
  lib/Doctrine/ORM/Query/AST/WhereClause.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: BC Break, Static Analysis

#9976 Add types to EntityListenerResolver
  lib/Doctrine/ORM/Event/ListenersInvoker.php
  lib/Doctrine/ORM/Mapping/DefaultEntityListenerResolver.php
  lib/Doctrine/ORM/Mapping/EntityListenerResolver.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/EntityListenerResolverTest.php
Labels: BC Break

#9848 Improve orphan removal documentation - recommend using cascade=persist
  docs/en/reference/working-with-associations.rst
Labels: Documentation

#9994 Update query-builder.rst
  docs/en/reference/query-builder.rst
Labels: Documentation

#10006 Fix build
  composer.json
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Tools/Setup.php
  phpstan-baseline.neon
  phpstan-dbal2.neon
  phpstan-persistence2.neon
  phpstan.neon
  psalm-baseline.xml
Labels: Static Analysis, Test Suite

#10008 Fail gracefully if EM could not be constructed in tests
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Test Suite

#10002 Make paginator covariant
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  tests/Doctrine/StaticAnalysis/Tools/Pagination/paginator-covariant.php
Labels: Static Analysis

#10020 Bump Ubuntu version and shared workflows
  .github/workflows/coding-standard.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/phpbench.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI
