Repository doctrine/orm, pull requests merged in 2022-03, with the labels that each got.

#9552 Use literal types for `JOIN_TYPE_*` constants
  lib/Doctrine/ORM/Query/AST/Join.php
  lib/Doctrine/ORM/Query/SqlWalker.php
Labels: Static Analysis

#9557 Parser: SimpleArithmeticExpression should return ArithmeticTerm
  lib/Doctrine/ORM/Query/Parser.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9019 validate schema command: allow to debug missing schema updates list
  docs/en/reference/tools.rst
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ValidateSchemaCommandTest.php
Labels: Improvement

#9563 Remove reference to removed class
  docs/en/reference/advanced-configuration.rst
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/ClassTableInheritanceSecondTest.php
  tests/Doctrine/Tests/ORM/Functional/FlushEventTest.php
  tests/Doctrine/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Doctrine/Tests/ORM/Functional/ManyToManyBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToManyBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryBuilderParenthesisTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1163Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1193Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC168Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC211Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC258Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC345Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC371Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC422Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC425Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC444Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC599Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC719Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC812Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC837Test.php
Labels: Documentation

#9555 Adding PHP attributes
  docs/en/reference/basic-mapping.rst
Labels: Documentation

#9574 Make sure MemcachedAdapter is supported before tring to use it
  lib/Doctrine/ORM/Tools/Setup.php
Labels: Bug

#9577 Baseline Psalm errors caused by DBAL 3.3.3
  psalm-baseline.xml
Labels: Static Analysis

#9578 Leverage `MemcachedAdapter::isSupported()`
  lib/Doctrine/ORM/ORMSetup.php
Labels: Improvement

#9585 Hunt down latest
  README.md
  SECURITY.md
  UPGRADE.md
  docs/en/cookbook/dql-user-defined-functions.rst
  docs/en/cookbook/implementing-wakeup-or-clone.rst
  docs/en/reference/architecture.rst
  docs/en/reference/configuration.rst
  docs/en/reference/dql-doctrine-query-language.rst
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Documentation

#9587 Implement colocated mapping driver
  UPGRADE.md
  composer.json
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Improvement

#9580 Add test to reproduce #9579
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9579Test.php
Labels: Bug

#9589 Fix type errors with XML export on PHP 8.1
  lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
Labels: Bug

#9592 Deprecate or throw on namespace alias usage
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManager.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2256Test.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: Deprecation

#9565 Fix type on `SqlWalker::walkPathExpression()`
  lib/Doctrine/ORM/Query/AST/JoinAssociationPathExpression.php
  lib/Doctrine/ORM/Query/AST/PathExpression.php
  lib/Doctrine/ORM/Query/QueryException.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Query/TreeWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  psalm-baseline.xml
Labels: Static Analysis

#9597 Remove support for entity namespace aliases
  UPGRADE.md
  docs/en/reference/dql-doctrine-query-language.rst
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Exception/UnknownEntityNamespace.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Query/Lexer.php
  lib/Doctrine/ORM/Query/Parser.php
  phpstan-baseline.neon
  psalm.xml
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/NewOperatorTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2256Test.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Query/LanguageRecognitionTest.php
  tests/Doctrine/Tests/ORM/Query/LexerTest.php
  tests/Doctrine/Tests/ORM/Query/ParserTest.php
Labels: BC Break

#9598 Use correct syntax for external links
  docs/en/reference/events.rst
Labels: Documentation

#9604 Indicate what feature is deprecated
  lib/Doctrine/ORM/Exception/NotSupported.php
  lib/Doctrine/ORM/Id/UuidGenerator.php
Labels: Improvement

#9607 PHPStan 1.5.0
  composer.json
  phpstan-baseline.neon
Labels: Static Analysis

#9611 Remove "Description of" PHPDoc
  lib/Doctrine/ORM/Query/AST/AggregateExpression.php
  lib/Doctrine/ORM/Query/AST/InputParameter.php
  lib/Doctrine/ORM/Query/QueryException.php
Labels: Documentation

#9612 Skip tests requiring ObjectManagerAware
  phpstan-persistence3.neon
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2231Test.php
Labels: Test Suite

#9614 Remove support for `ObjectManagerAware`
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2231Test.php
Labels: BC Break

#9616 Support enums as default values
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/Models/Enums/CardWithDefault.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: New Feature
