Repository doctrine/orm, pull requests merged in 2022-04, with the labels that each got.

#9623 explicitly use the non-deprecated ORMException
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Bug

#9620 Add native types to ResultSetMapping
  lib/Doctrine/ORM/Query/ResultSetMapping.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: BC Break, Static Analysis

#9621 Fix types on ResultSetMapping
  lib/Doctrine/ORM/Query/ResultSetMapping.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9497 Add support for array of enums
  lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php
  tests/Doctrine/Tests/Models/Enums/Scale.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: New Feature

#9566 Fix types on `walkLiteral()` and `walkLikeExpression()`
  lib/Doctrine/ORM/Query/AST/LikeExpression.php
  lib/Doctrine/ORM/Query/AST/Literal.php
  lib/Doctrine/ORM/Query/QueryException.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Query/TreeWalker.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9533 Deprecate custom `ObjectRepository` implementations
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Exception/InvalidEntityRepository.php
  lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php
  lib/Doctrine/ORM/Repository/RepositoryFactory.php
  psalm-baseline.xml
  tests/Doctrine/Performance/Hydration/SimpleHydrationBench.php
  tests/Doctrine/Performance/Hydration/SingleTableInheritanceHydrationPerformanceBench.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/CustomRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
Labels: Deprecation

#9629 Support Enum IDs and search by Enum fields
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/UnitOfWork.php
  lib/Doctrine/ORM/Utility/IdentifierFlattener.php
  tests/Doctrine/Tests/Models/Enums/TypedCardEnumCompositeId.php
  tests/Doctrine/Tests/Models/Enums/TypedCardEnumId.php
  tests/Doctrine/Tests/ORM/Utility/IdentifierFlattenerEnumIdTest.php
Labels: New Feature

#7196 Document exception-splitting-related BC-breaks
  UPGRADE.md
Labels: Documentation, BC Break

#9636 Use correct charset/collation from column/table defaults when creating relationships
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6823Test.php
Labels: Bug

#9641 Deprecate console helper
  UPGRADE.md
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/HelperSetManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/Helper/EntityManagerHelper.php
  psalm.xml
Labels: Deprecation

#9646 Improve exception message
  UPGRADE.md
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/DefaultCache.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2084Test.php
Labels: Improvement, Deprecation

#9648 Fix static analysis for Persistence 2.5
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/EntityRepository.php
Labels: Static Analysis

#9633 Leverage generic persistence event classes
  lib/Doctrine/ORM/Event/LifecycleEventArgs.php
  lib/Doctrine/ORM/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/ORM/Event/OnClassMetadataNotFoundEventArgs.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/EventListener/CacheMetadataListener.php
Labels: Static Analysis

#9649 Fix test file/class names
  tests/Doctrine/Tests/ORM/Functional/InsertableUpdatableTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1458Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7684Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/Ticket4646InstanceOfWithMultipleParametersTest.php
Labels: Test Suite

#9640 Remove console helper
  UPGRADE.md
  lib/Doctrine/ORM/Tools/Console/Command/AbstractEntityManagerCommand.php
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/HelperSetManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/Helper/EntityManagerHelper.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/InfoCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/ConsoleRunnerTest.php
Labels: BC Break

#9658 Fix IdentifierFlattenerEnumIdTest
  tests/Doctrine/Tests/ORM/Utility/IdentifierFlattenerEnumIdTest.php
Labels: Test Suite

#9663 ScalarColumnHydrator: prevent early-bail on falsy values
  lib/Doctrine/ORM/Internal/Hydration/ScalarColumnHydrator.php
  tests/Doctrine/Tests/Mocks/DriverResultMock.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9230Test.php
Labels: Bug

#9661 Deprecate the doctrine binary
  UPGRADE.md
  bin/doctrine-pear.php
  bin/doctrine.php
  docs/en/reference/advanced-configuration.rst
  docs/en/reference/configuration.rst
  docs/en/reference/tools.rst
  docs/en/tutorials/getting-started.rst
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
Labels: Documentation, Deprecation

#9671 Conditionally extend the old `AnnotationDriver` class
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/CompatibilityAnnotationDriver.php
  phpcs.xml.dist
  phpstan-persistence2.neon
  tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php
Labels: Bug

#9665 Drop support for persistence 2
  .github/workflows/static-analysis.yml
  composer.json
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/PersistentObjectTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: BC Break

#9662 Remove the doctrine binary
  UPGRADE.md
  bin/doctrine
  bin/doctrine-pear.php
  bin/doctrine.bat
  bin/doctrine.php
  composer.json
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
Labels: BC Break

#9675 Fix type on ClassMetadata discriminatorMap
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9676 Fix HydrationException::invalidDiscriminatorValue parameter type
  lib/Doctrine/ORM/Internal/Hydration/HydrationException.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9677 Document ORM drivers only really load ORM metadata
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/DatabaseDriverTestCase.php
Labels: Static Analysis

#6728 Validate XML mapping against XSD file
  composer.json
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  lib/Doctrine/ORM/ORMSetup.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC889.DDC889Class.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC889.DDC889Entity.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC889.DDC889SuperClass.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.UserIncorrectAttributes.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.UserMissingAttributes.dcm.xml
Labels: Improvement

#9682 PHPStan 1.6.0
  composer.json
  phpstan-dbal2.neon
  phpstan-persistence2.neon
  phpstan.neon
Labels: Static Analysis

#9683 Remove dynamic property declarations
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/Locking/LockTest.php
  tests/Doctrine/Tests/ORM/Functional/ReferenceProxyTest.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/DBAL483Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1163Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1193Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1301Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1885Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2519Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC522Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC69Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/Ticket2481Test.php
  tests/Doctrine/Tests/ORM/Mapping/Symfony/AbstractDriverTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Test Suite

#9679 Drop SymfonyStyle[listing] for sqls
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
Labels: Bug

#9688 PHPStan 1.6.1
  composer.json
  phpstan-dbal2.neon
  phpstan-persistence2.neon
  phpstan.neon
Labels: Static Analysis

#9691 Reference ClassMetadaInfo less
  docs/en/cookbook/sql-table-prefixes.rst
  docs/en/reference/metadata-drivers.rst
  docs/en/reference/php-mapping.rst
  docs/en/reference/tools.rst
Labels: Documentation

#9692 Use ClassMetadata over ClassMetadataInfo in tests
  tests/Doctrine/Tests/Models/CMS/CmsAddress.php
  tests/Doctrine/Tests/Models/CMS/CmsUser.php
  tests/Doctrine/Tests/Models/Cache/City.php
  tests/Doctrine/Tests/Models/Company/CompanyContract.php
  tests/Doctrine/Tests/Models/Company/CompanyFixContract.php
  tests/Doctrine/Tests/Models/Company/CompanyFlexContract.php
  tests/Doctrine/Tests/Models/Company/CompanyFlexUltraContract.php
  tests/Doctrine/Tests/Models/Company/CompanyPerson.php
  tests/Doctrine/Tests/Models/DDC1476/DDC1476EntityWithDefaultFieldType.php
  tests/Doctrine/Tests/Models/DDC3579/DDC3579User.php
  tests/Doctrine/Tests/Models/DDC869/DDC869ChequePayment.php
  tests/Doctrine/Tests/Models/DDC869/DDC869CreditCardPayment.php
  tests/Doctrine/Tests/Models/DDC869/DDC869Payment.php
  tests/Doctrine/Tests/Models/DDC889/DDC889Class.php
  tests/Doctrine/Tests/Models/DDC889/DDC889Entity.php
  tests/Doctrine/Tests/Models/DDC889/DDC889SuperClass.php
  tests/Doctrine/Tests/Models/DDC964/DDC964Admin.php
  tests/Doctrine/Tests/Models/DDC964/DDC964Guest.php
  tests/Doctrine/Tests/Models/DDC964/DDC964User.php
  tests/Doctrine/Tests/Models/Enums/Card.php
  tests/Doctrine/Tests/Models/Enums/CardWithNullable.php
  tests/Doctrine/Tests/Models/Enums/Scale.php
  tests/Doctrine/Tests/Models/TypedProperties/UserTyped.php
  tests/Doctrine/Tests/Models/Upsertable/Insertable.php
  tests/Doctrine/Tests/Models/Upsertable/Updatable.php
  tests/Doctrine/Tests/ORM/Functional/DatabaseDriverTest.php
  tests/Doctrine/Tests/ORM/Functional/DatabaseDriverTestCase.php
  tests/Doctrine/Tests/ORM/Functional/ExtraLazyCollectionTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1301Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2387Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2415Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3103Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6682Test.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/FieldBuilderTest.php
  tests/Doctrine/Tests/ORM/Mapping/PHPMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Cache.City.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Company.CompanyContract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC1476.DDC1476EntityWithDefaultFieldType.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC3579.DDC3579User.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC869.DDC869Payment.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC889.DDC889Class.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC889.DDC889SuperClass.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC964.DDC964User.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.TypedProperties.UserTyped.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Upsertable.Insertable.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Upsertable.Updatable.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.Animal.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.Comment.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.DDC1170Entity.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.DDC807Entity.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.PHPSLC.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.User.php
  tests/Doctrine/Tests/ORM/Tools/Export/AbstractClassMetadataExporterTest.php
  tests/Doctrine/Tests/ORM/Tools/Export/XmlClassMetadataExporterTest.php
  tests/Doctrine/Tests/ORM/Tools/Export/php/Doctrine.Tests.ORM.Tools.Export.User.php
  tests/Doctrine/Tests/ORM/Tools/SchemaToolTest.php
Labels: Test Suite

#9698 use valid link syntax
  docs/en/reference/events.rst
Labels: Documentation

#9699 Add missing use statement
  docs/en/reference/events.rst
Labels: Documentation
