Repository doctrine/orm, pull requests merged in 2022-09, with the labels that each got.

#9995 Fix EnumType not being hydrated with HYDRATE_ARRAY
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php
  tests/Doctrine/Tests/ORM/Hydration/ArrayHydratorTest.php
Labels: Bug

#10033 PHPStan 1.8.5, Psalm 4.27.0
  composer.json
  phpstan-baseline.neon
  phpstan-dbal2.neon
  phpstan-persistence2.neon
  phpstan.neon
  psalm-baseline.xml
Labels: Static Analysis

#9983 Add phpdoc for ClassMetadataInfo::discriminatorColumn property
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
Labels: Static Analysis

#10052 Add types to mapping builders
  lib/Doctrine/ORM/Mapping/Builder/AssociationBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/EmbeddedBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/EntityListenerBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/FieldBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/ManyToManyAssociationBuilder.php
  lib/Doctrine/ORM/Mapping/Builder/OneToManyAssociationBuilder.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataBuilderTest.php
Labels: BC Break

#10045 Deprecate `Doctrine\ORM\Proxy\Proxy` and decouple a bit more from `Doctrine\Common\Proxy`
  UPGRADE.md
  docs/en/cookbook/accessing-private-properties-of-the-same-class-from-different-instance.rst
  docs/en/reference/advanced-configuration.rst
  docs/en/reference/unitofwork.rst
  docs/en/tutorials/getting-started.rst
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Proxy/Proxy.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpcs.xml.dist
  tests/Doctrine/Performance/LazyLoading/ProxyInitializationTimeBench.php
  tests/Doctrine/Performance/LazyLoading/ProxyInstantiationTimeBench.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/ClassTableInheritanceTest.php
  tests/Doctrine/Tests/ORM/Functional/DefaultValuesTest.php
  tests/Doctrine/Tests/ORM/Functional/DetachedEntityTest.php
  tests/Doctrine/Tests/ORM/Functional/MappedSuperclassTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToManyBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneEagerLoadingTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneSelfReferentialAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Functional/ReferenceProxyTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/SingleTableInheritanceTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1163Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1193Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1228Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1452Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1690Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1734Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2230Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2231Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2306Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC237Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2494Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2519Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC371Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC522Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC531Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC633Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC736Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC881Test.php
  tests/Doctrine/Tests/ORM/Proxy/ProxyFactoryTest.php
Labels: Deprecation

#10041 Fix ArrayHydration of enums
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: Bug, Waiting feedback

#10053 Add types to PersisterHelper
  lib/Doctrine/ORM/Utility/PersisterHelper.php
Labels: BC Break

#10058 Fix using enums with the QueryBuilder
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: Bug, Regression

#10072 Remove return type override
  lib/Doctrine/ORM/Persisters/SqlValueVisitor.php
Labels: Static Analysis

#10048 Migrate QueryBuilder / ClassMetadataInfo
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/QueryBuilder.php
  psalm-baseline.xml
Labels: BC Break

#10080 Address changes from doctrine/collections 1.8.0
  lib/Doctrine/ORM/LazyCriteriaCollection.php
  lib/Doctrine/ORM/PersistentCollection.php
  psalm.xml
Labels: Static Analysis
