Repository doctrine/orm, pull requests merged in 2022-01, with the labels that each got.

#9315 Psalm 4.17.0
  composer.json
  psalm-baseline.xml
Labels: CI

#9317 Run PHP CodeSniffer on PHP 8.1
  .github/workflows/coding-standard.yml
Labels: CI

#9318 Document PHPUnit mocks with intersection types
  tests/Doctrine/Tests/ORM/Cache/CacheLoggerChainTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheFactoryTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/AbstractCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/AbstractEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Doctrine/Tests/ORM/Internal/HydrationCompleteHandlerTest.php
  tests/Doctrine/Tests/ORM/LazyCriteriaCollectionTest.php
  tests/Doctrine/Tests/ORM/Repository/DefaultRepositoryFactoryTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginatorTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Improvement

#9319 Document LockMode enums
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Improvement

#9314 Run static analysis with language level PHP 8.1
  lib/Doctrine/ORM/LazyCriteriaCollection.php
  lib/Doctrine/ORM/PersistentCollection.php
  phpstan-baseline.neon
  phpstan-params.neon
  psalm.xml
Labels: CI

#9293 Enable PHPCS rules for PHP 8.0
  phpcs.xml.dist
  tests/Doctrine/StaticAnalysis/get-metadata.php
  tests/Doctrine/Tests/DoctrineTestCase.php
  tests/Doctrine/Tests/Mocks/CacheRegionMock.php
  tests/Doctrine/Tests/Mocks/ConnectionMock.php
  tests/Doctrine/Tests/Mocks/EntityPersisterMock.php
  tests/Doctrine/Tests/Models/DDC3711/DDC3711EntityA.php
  tests/Doctrine/Tests/Models/ECommerce/ECommerceShipping.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2895Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC5684Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6303Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH5762Test.php
  tests/Doctrine/Tests/ORM/Hydration/SingleScalarHydratorTest.php
  tests/Doctrine/Tests/ORM/ORMInvalidArgumentExceptionTest.php
  tests/Doctrine/Tests/ORM/Query/ParameterTypeInfererTest.php
  tests/Doctrine/Tests/ORM/Query/QueryExpressionVisitorTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/WhereInWalkerTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Improvement

#9324 Enable some previously disabled PHPCS rules
  phpcs.xml.dist
Labels: CI

#9292 Add types to entity manager
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Doctrine/Tests/Mocks/EntityManagerMock.php
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
Labels: BC Break

#9329 Add types to `UnitOfWork`
  lib/Doctrine/ORM/UnitOfWork.php
  psalm-baseline.xml
  tests/Doctrine/Performance/Mock/NonProxyLoadingUnitOfWork.php
  tests/Doctrine/Tests/Mocks/UnitOfWorkMock.php
Labels: Improvement, BC Break

#9327 Added runtime deprecation to `UnitOfWork::commit()` and `clear()`
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Deprecation

#9309 [GH-9277] deprecate php driver
  UPGRADE.md
  docs/en/reference/php-mapping.rst
  lib/Doctrine/ORM/Mapping/Driver/PHPDriver.php
Labels: Deprecation

#9308 [GH-9277] remove deprecated `PHPDriver`
  UPGRADE.md
  docs/en/reference/php-mapping.rst
  lib/Doctrine/ORM/Mapping/Driver/PHPDriver.php
  tests/Doctrine/Tests/Models/Cache/City.php
  tests/Doctrine/Tests/ORM/Mapping/PHPMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.CMS.CmsAddress.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.CMS.CmsUser.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Cache.City.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Company.CompanyContract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Company.CompanyFixContract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Company.CompanyFlexContract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Company.CompanyFlexUltraContract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Company.CompanyPerson.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC1476.DDC1476EntityWithDefaultFieldType.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC2825.ExplicitSchemaAndTable.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC2825.SchemaAndTableInTableName.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC3579.DDC3579Admin.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC3579.DDC3579User.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC5934.DDC5934BaseContract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC5934.DDC5934Contract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC869.DDC869ChequePayment.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC869.DDC869CreditCardPayment.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC869.DDC869Payment.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC889.DDC889Class.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC889.DDC889Entity.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC889.DDC889SuperClass.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC964.DDC964Admin.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC964.DDC964Guest.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC964.DDC964User.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.TypedProperties.UserTyped.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.Animal.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.Comment.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.DDC1170Entity.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.DDC807Entity.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.PHPSLC.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.ReservedWordInTableColumn.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.ORM.Mapping.User.php
Labels: BC Break

#9304 Add support for PHP 8.1 enums.
  docs/en/reference/basic-mapping.rst
  doctrine-mapping.xsd
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Column.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php
  phpcs.xml.dist
  phpstan-baseline.neon
  tests/Doctrine/Tests/Models/Enums/Card.php
  tests/Doctrine/Tests/Models/Enums/Suit.php
  tests/Doctrine/Tests/Models/Enums/TypedCard.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.Enums.Card.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Enums.Card.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/yaml/Doctrine.Tests.Models.Enums.Card.dcm.yml
Labels: New Feature

#9339 Fix field mapping typing
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Bug

#9275 Fix type errors in `AbstractQuery` and `QueryBuilder`
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/QueryBuilder.php
  psalm-baseline.xml
Labels: Improvement

#9340 Use the readonly annotation
  lib/Doctrine/ORM/Cache/AssociationCacheEntry.php
  lib/Doctrine/ORM/Cache/CacheKey.php
  lib/Doctrine/ORM/Cache/CollectionCacheEntry.php
  lib/Doctrine/ORM/Cache/CollectionCacheKey.php
  lib/Doctrine/ORM/Cache/EntityCacheEntry.php
  lib/Doctrine/ORM/Cache/EntityCacheKey.php
  lib/Doctrine/ORM/Cache/QueryCacheEntry.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Cache/TimestampCacheEntry.php
  lib/Doctrine/ORM/Query/Parser.php
Labels: Improvement

#9341 PHPStan 1.3.3, Psalm 4.18.1
  composer.json
  psalm-baseline.xml
Labels: CI

#9326 Add support for custom types with requireSQLConversion and ResultSetMappingBuilder::generateSelectClause()
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  tests/Doctrine/Tests/ORM/Functional/NativeQueryTest.php
Labels: New Feature

#9322 PSR-6 second level cache
  UPGRADE.md
  docs/en/reference/second-level-cache.rst
  lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
  lib/Doctrine/ORM/Cache/Region/DefaultMultiGetRegion.php
  lib/Doctrine/ORM/Cache/Region/DefaultRegion.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/CollectionRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/EntityRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryRegionCommand.php
  phpstan-baseline.neon
  phpstan-dbal2.neon
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/Cache/AbstractRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheFactoryTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionLegacyTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/FileLockRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/MultiGetRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/AbstractCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/AbstractEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheConcurrentTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC7969Test.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Improvement, Deprecation

#9348 Remove support for Doctrine Cache in second level cache
  UPGRADE.md
  lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
  lib/Doctrine/ORM/Cache/Region/DefaultMultiGetRegion.php
  lib/Doctrine/ORM/Cache/Region/DefaultRegion.php
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionLegacyTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/MultiGetRegionTest.php
Labels: BC Break

#9316 Support readonly properties for read operations
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/ReflectionReadonlyProperty.php
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/Models/ReadonlyProperties/Author.php
  tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php
  tests/Doctrine/Tests/Models/ReadonlyProperties/SimpleBook.php
  tests/Doctrine/Tests/ORM/Functional/ReadonlyPropertiesTest.php
  tests/Doctrine/Tests/ORM/Mapping/ReflectionReadonlyPropertyTest.php
Labels: Improvement

#9349 Update Psalm baseline for Persistence 2.3
  psalm-baseline.xml
Labels: CI

#9268 Fix WhereInWalker description to better describe the behaviour of this class
  lib/Doctrine/ORM/Tools/Pagination/WhereInWalker.php
Labels: Documentation

#9312 Leverage generic ObjectManagerDecorator
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
Labels: Improvement

#9355 Relax assertion to include null as possible outcome
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
Labels: Bug

#9359 Add native types to console classes
  lib/Doctrine/ORM/Tools/Console/Command/AbstractEntityManagerCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/CollectionRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/EntityRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/InfoCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/CreateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/DropCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/ConnectionFromManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/HelperSetManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/SingleManagerProvider.php
  lib/Doctrine/ORM/Tools/Console/Helper/EntityManagerHelper.php
  lib/Doctrine/ORM/Tools/Console/MetadataFilter.php
  psalm-baseline.xml
Labels: BC Break

#9356 Remove the `composer/package-versions-deprecated` package
  UPGRADE.md
  composer.json
  lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php
  tests/Doctrine/Tests/ORM/Tools/Console/ConsoleRunnerTest.php
Labels: Improvement

#9353 Add native types to `AbstractHydrator` and child classes
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/HydrationException.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ScalarHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/SingleScalarHydrator.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ArrayHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/CustomHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/HydrationTestCase.php
  tests/Doctrine/Tests/ORM/Hydration/ResultSetMappingTest.php
Labels: BC Break

#9325 Use `EntityManagerInterface` in type declarations
  UPGRADE.md
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Event/LifecycleEventArgs.php
  lib/Doctrine/ORM/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/ORM/Event/PostFlushEventArgs.php
  lib/Doctrine/ORM/Event/PreFlushEventArgs.php
  lib/Doctrine/ORM/Id/AbstractIdGenerator.php
  lib/Doctrine/ORM/Id/AssignedGenerator.php
  lib/Doctrine/ORM/Id/BigIntegerIdentityGenerator.php
  lib/Doctrine/ORM/Id/IdentityGenerator.php
  lib/Doctrine/ORM/Id/SequenceGenerator.php
  lib/Doctrine/ORM/Id/TableGenerator.php
  lib/Doctrine/ORM/Id/UuidGenerator.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/FilterCollection.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/EventListener/CacheMetadataListener.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheFactoryTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultEntityHydratorTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/AbstractCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/NonStrictReadWriteCachedCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/ReadOnlyCachedCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/ReadWriteCachedCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/AbstractEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/NonStrictReadWriteCachedEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/ReadOnlyCachedEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Functional/ManyToOneOrphanRemovalTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2415Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH5804Test.php
  tests/Doctrine/Tests/ORM/Hydration/ResultSetMappingTest.php
  tests/Doctrine/Tests/ORM/Id/AbstractIdGeneratorTest.php
  tests/Doctrine/Tests/ORM/Id/AssignedGeneratorTest.php
  tests/Doctrine/Tests/ORM/Id/SequenceGeneratorTest.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterCompositeTypeParametersTest.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterCompositeTypeSqlTest.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
  tests/Doctrine/Tests/ORM/Persisters/JoinedSubclassPersisterTest.php
  tests/Doctrine/Tests/ORM/Query/FilterCollectionTest.php
  tests/Doctrine/Tests/ORM/QueryBuilderTest.php
  tests/Doctrine/Tests/ORM/Tools/AttachEntityListenersListenerTest.php
  tests/Doctrine/Tests/ORM/Tools/ResolveTargetEntityListenerTest.php
  tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Improvement, Deprecation

#9368 Fix doc blocks on ID generators
  lib/Doctrine/ORM/Id/AbstractIdGenerator.php
  lib/Doctrine/ORM/Id/BigIntegerIdentityGenerator.php
  psalm-baseline.xml
Labels: Documentation

#9358 Remove `Configuration::ensureProductionSettings()`
  UPGRADE.md
  lib/Doctrine/ORM/Cache/Exception/MetadataCacheNotConfigured.php
  lib/Doctrine/ORM/Cache/Exception/MetadataCacheUsesNonPersistentCache.php
  lib/Doctrine/ORM/Cache/Exception/QueryCacheNotConfigured.php
  lib/Doctrine/ORM/Cache/Exception/QueryCacheUsesNonPersistentCache.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Exception/ProxyClassesAlwaysRegenerating.php
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
Labels: BC Break

#9357 Add detach as of list cascade-all operations
  docs/en/reference/xml-mapping.rst
Labels: Documentation

#9373 Support enum cases as parameters
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Query/ParameterTypeInferer.php
  phpcs.xml.dist
  psalm.xml
  tests/Doctrine/Tests/Models/Enums/AccessLevel.php
  tests/Doctrine/Tests/Models/Enums/City.php
  tests/Doctrine/Tests/Models/Enums/UserStatus.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Query/ParameterTypeInfererTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: New Feature

#9385 PHPStan 1.4.0
  composer.json
  phpstan-baseline.neon
Labels: Static Analysis

#9386 Corrected ORM version and added missing dependency
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#9384 Allow using Enum from different namespace than Entity
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Missing Tests, Bug

#9382 Expose enumType to DBAL to make native DB Enum possible
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Tools/SchemaToolTest.php
Labels: Bug

#9311 Accessing private properties and methods from the same class is forbidden
  docs/en/cookbook/accessing-private-properties-of-the-same-class-from-different-instance.rst
  docs/en/reference/architecture.rst
Labels: Documentation

#9367 Remove `AbstractIdGenerator::generate()` and add native types to ID generators
  UPGRADE.md
  lib/Doctrine/ORM/Id/AbstractIdGenerator.php
  lib/Doctrine/ORM/Id/AssignedGenerator.php
  lib/Doctrine/ORM/Id/BigIntegerIdentityGenerator.php
  lib/Doctrine/ORM/Id/IdentityGenerator.php
  lib/Doctrine/ORM/Id/SequenceGenerator.php
  psalm.xml
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2415Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH5804Test.php
  tests/Doctrine/Tests/ORM/Id/AbstractIdGeneratorTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: BC Break

#9393 Update baselines for DBAL 3.3
  composer.json
  psalm-baseline.xml
Labels: Static Analysis

#9398 Fix type on loadCacheEntry
  lib/Doctrine/ORM/Cache/EntityHydrator.php
Labels: Static Analysis

#9397 Deprecate MultiGetRegion
  UPGRADE.md
  lib/Doctrine/ORM/Cache/MultiGetRegion.php
  psalm.xml
Labels: Deprecation

#9403 Remove MultiGetRegion and add native types to Region implementations
  UPGRADE.md
  lib/Doctrine/ORM/Cache/ConcurrentRegion.php
  lib/Doctrine/ORM/Cache/MultiGetRegion.php
  lib/Doctrine/ORM/Cache/Region.php
  lib/Doctrine/ORM/Cache/Region/DefaultRegion.php
  lib/Doctrine/ORM/Cache/Region/FileLockRegion.php
  lib/Doctrine/ORM/Cache/Region/UpdateTimestampCache.php
  lib/Doctrine/ORM/Cache/TimestampRegion.php
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/Mocks/CacheRegionMock.php
  tests/Doctrine/Tests/Mocks/ConcurrentRegionMock.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/ReadWriteCachedCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersisterTest.php
Labels: BC Break

#9396 Add native types to EntityHydrator
  lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php
  lib/Doctrine/ORM/Cache/EntityHydrator.php
  tests/Doctrine/Tests/ORM/Cache/DefaultEntityHydratorTest.php
Labels: BC Break

#9401 Fix types on CacheLogger implementations
  lib/Doctrine/ORM/Cache/Logging/CacheLoggerChain.php
  lib/Doctrine/ORM/Cache/Logging/StatisticsCacheLogger.php
Labels: Static Analysis

#9413 Remove check for `getSQLResultCasing()`
  tests/Doctrine/Tests/ORM/PersistentCollectionTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Improvement

#9410 Allow DiscriminatorColumn with length=0
  lib/Doctrine/ORM/Mapping/DiscriminatorColumn.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php
Labels: Bug

#9392 Remove old cache accessors and mutators from query classes
  UPGRADE.md
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/Exception/InvalidResultCacheDriver.php
  lib/Doctrine/ORM/Query.php
  phpcs.xml.dist
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
  tests/Doctrine/Tests/ORM/Functional/HydrationCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/NativeQueryTest.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: BC Break

#9418 Switch tests to the middleware logging system
  composer.json
  tests/Doctrine/Tests/DbalExtensions/Connection.php
  tests/Doctrine/Tests/DbalExtensions/LegacySqlLogger.php
  tests/Doctrine/Tests/DbalExtensions/QueryLog.php
  tests/Doctrine/Tests/DbalExtensions/SqlLogger.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/ClassTableInheritanceSecondTest.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/FlushEventTest.php
  tests/Doctrine/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Doctrine/Tests/ORM/Functional/Locking/LockTest.php
  tests/Doctrine/Tests/ORM/Functional/ManyToManyBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToManyBidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneEagerLoadingTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneInverseSideLoadAfterDqlQueryTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryBuilderParenthesisTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1163Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1193Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1595Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC168Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC211Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2214Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2346Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC258Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC345Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC371Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC422Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC425Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC444Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC599Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC719Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC812Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC837Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7012Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7829Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8217Test.php
  tests/Doctrine/Tests/ORM/Performance/SecondLevelCacheTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Test Suite

#9419 Fix support for PHP 8.1 enums in embedded classes
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  phpcs.xml.dist
  psalm-baseline.xml
  tests/Doctrine/Tests/Models/Enums/Product.php
  tests/Doctrine/Tests/Models/Enums/Quantity.php
  tests/Doctrine/Tests/Models/Enums/Unit.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: Bug

#9422 Remove DBAL 2 compatible SQL logging
  tests/Doctrine/Tests/DbalExtensions/Connection.php
  tests/Doctrine/Tests/DbalExtensions/LegacySqlLogger.php
  tests/Doctrine/Tests/DbalExtensions/QueryLog.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2214Test.php
Labels: Test Suite

#9423 Introduce `assertQueryCount()`
  tests/Doctrine/Tests/DbalExtensions/QueryLog.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/ExtraLazyCollectionTest.php
  tests/Doctrine/Tests/ORM/Functional/HydrationCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneEagerLoadingTest.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheCompositePrimaryKeyTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheCompositePrimaryKeyWithAssociationsTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheConcurrentTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheCriteriaTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheExtraLazyCollectionTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheJoinTableInheritanceTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheManyToManyTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheManyToOneTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheOneToManyTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheOneToOneTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheSingleTableInheritanceTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1301Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1400Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2346Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2350Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2494Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2862Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6217Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7829Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8217Test.php
  tests/Doctrine/Tests/ORM/Performance/SecondLevelCacheTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Test Suite

#9425 Ignore PHPUnit result cache everywhere
  .gitignore
Labels: Test Suite

#9438 Psalm 4.19.0, PHPStan 1.4.3
  composer.json
  lib/Doctrine/ORM/PersistentCollection.php
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#9440 Added php 8.1 to CI
  .github/workflows/continuous-integration.yml
  tests/Doctrine/Tests/Models/ReadonlyProperties/Author.php
  tests/Doctrine/Tests/Models/ReadonlyProperties/Book.php
  tests/Doctrine/Tests/Models/ReadonlyProperties/SimpleBook.php
Labels: CI

#9428 Removing the deprecated Named (Native) Queries in Metadata/EntityRepository
  UPGRADE.md
  docs/en/reference/annotations-reference.rst
  docs/en/reference/native-sql.rst
  docs/en/reference/php-mapping.rst
  doctrine-mapping.xsd
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Exception/NamedNativeQueryNotFound.php
  lib/Doctrine/ORM/Exception/NamedQueryNotFound.php
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/NamedNativeQueries.php
  lib/Doctrine/ORM/Mapping/NamedNativeQuery.php
  lib/Doctrine/ORM/Mapping/NamedQueries.php
  lib/Doctrine/ORM/Mapping/NamedQuery.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  phpcs.xml.dist
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Doctrine/Tests/Models/CMS/CmsAddress.php
  tests/Doctrine/Tests/Models/CMS/CmsUser.php
  tests/Doctrine/Tests/Models/Company/CompanyContract.php
  tests/Doctrine/Tests/Models/Company/CompanyFlexContract.php
  tests/Doctrine/Tests/Models/Company/CompanyPerson.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/NativeQueryTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1404Test.php
  tests/Doctrine/Tests/ORM/Hydration/ResultSetMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.CMS.CmsAddress.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.CMS.CmsUser.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Company.CompanyPerson.dcm.xml
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.User.dcm.xml
Labels: BC Break

#9442 Adapt test logic to PHP and SQLite II
  tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
Labels: Test Suite

#9390 Introduce __unserialize behaviour in docs
  docs/en/reference/architecture.rst
Labels: Documentation

#9443 Introduce `DoctrineSetup` as a replacement for `Setup`
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Tools/DoctrineSetup.php
  lib/Doctrine/ORM/Tools/Setup.php
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Performance/EntityManagerFactory.php
  tests/Doctrine/Tests/Mocks/EntityManagerMock.php
  tests/Doctrine/Tests/ORM/Functional/Locking/LockAgentWorker.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/Tools/DoctrineSetupTest.php
  tests/Doctrine/Tests/ORM/Tools/SetupTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Improvement, Deprecation

#9446 Remove trailing underscore
  docs/en/reference/query-builder.rst
Labels: Documentation

#9448 Document the new `DoctrineSetup` class
  docs/en/reference/advanced-configuration.rst
  docs/en/reference/configuration.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#9447 Remove deprecated Setup class
  UPGRADE.md
  docs/en/reference/configuration.rst
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Tools/Setup.php
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Tools/SetupTest.php
Labels: BC Break

#9451 Streamline cache creation in tests
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Test Suite

#9450 Add more native types to entity manager implementations
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
Labels: BC Break

#9453 Support enums in findBy() calls
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: Improvement
