Repository doctrine/orm, pull requests merged in 2022-02, with the labels that each got.

#9456 Remove support for Doctrine Cache
  UPGRADE.md
  composer.json
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC742Test.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/ORM/Tools/DoctrineSetupTest.php
Labels: BC Break

#9452 Check requirements for metadata drivers
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  tests/Doctrine/Tests/ORM/Tools/SetupTest.php
Labels: Bug

#9457 PDO is not a required extension
  composer.json
Labels: Bug

#9459 Check requirements for metadata drivers
  lib/Doctrine/ORM/Tools/DoctrineSetup.php
  tests/Doctrine/Tests/ORM/Tools/DoctrineSetupTest.php
Labels: Bug

#9471 Remove ability to clear the UoW partially
  UPGRADE.md
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Event/OnClearEventArgs.php
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/ReadOnlyTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC117Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2106Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2409Test.php
  tests/Doctrine/Tests/ORM/ORMInvalidArgumentExceptionTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: BC Break

#9470 Run Postgres 14 and MariaDB 10.6 in CI
  .github/workflows/continuous-integration.yml
Labels: CI

#9472 Skip tests related to PersistentObject if that class is missing
  tests/Doctrine/Tests/Models/PersistentObject/PersistentCollectionContent.php
  tests/Doctrine/Tests/Models/PersistentObject/PersistentCollectionHolder.php
  tests/Doctrine/Tests/Models/PersistentObject/PersistentEntity.php
  tests/Doctrine/Tests/ORM/Functional/PersistentCollectionTest.php
  tests/Doctrine/Tests/ORM/Functional/PersistentObjectTest.php
Labels: Test Suite

#9475 Deprecate methods removed in 3.0
  UPGRADE.md
  lib/Doctrine/ORM/Event/OnClearEventArgs.php
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  psalm.xml
Labels: Deprecation

#9481 Rename `DoctrineSetup` to `ORMSetup`
  UPGRADE.md
  docs/en/reference/advanced-configuration.rst
  docs/en/reference/configuration.rst
  docs/en/tutorials/getting-started.rst
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/ORMSetup.php
  lib/Doctrine/ORM/Tools/Setup.php
  tests/Doctrine/Performance/EntityManagerFactory.php
  tests/Doctrine/Tests/Mocks/EntityManagerMock.php
  tests/Doctrine/Tests/ORM/Functional/Locking/LockAgentWorker.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/ORMSetupTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Improvement

#9479 Remove useless catches
  tests/Doctrine/Tests/ORM/Functional/OneToManyUnidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC117Test.php
  tests/Doctrine/Tests/ORM/Query/CustomTreeWalkersJoinTest.php
  tests/Doctrine/Tests/ORM/Query/CustomTreeWalkersTest.php
  tests/Doctrine/Tests/ORM/Query/DeleteSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Query/UpdateSqlGenerationTest.php
Labels: Test Suite

#9466 Fix types on persisters
  lib/Doctrine/ORM/Cache/Persister/CachedPersister.php
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Collection/CachedCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Collection/ReadWriteCachedCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersister.php
  lib/Doctrine/ORM/Persisters/Collection/CollectionPersister.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Performance/Mock/NonLoadingPersister.php
  tests/Doctrine/Tests/Mocks/EntityPersisterMock.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/AbstractCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Collection/ReadWriteCachedCollectionPersisterTest.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/AbstractEntityPersisterTest.php
  tests/Doctrine/Tests/ORM/Functional/ExtraLazyCollectionTest.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterCompositeTypeParametersTest.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterCompositeTypeSqlTest.php
  tests/Doctrine/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
  tests/Doctrine/Tests/ORM/Persisters/JoinedSubclassPersisterTest.php
  tests/Doctrine/Tests/ORM/Proxy/ProxyFactoryTest.php
Labels: Deprecation, Static Analysis, Test Suite

#9480 Modernize `strpos()` calls
  composer.json
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/DefaultNamingStrategy.php
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Query/Lexer.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/QueryExpressionVisitor.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  tests/Doctrine/Tests/ORM/Functional/ManyToOneOrphanRemovalTest.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/DBAL483Test.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/DDC214Test.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/PostgreSqlSchemaToolTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7875Test.php
  tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Improvement

#9485 Remove ability to flush the EM partially
  UPGRADE.md
  docs/en/reference/unitofwork.rst
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: BC Break

#9482 Run tests with stricter error handling
  ci/github/phpunit/mysqli.xml
  ci/github/phpunit/pdo_mysql.xml
  ci/github/phpunit/pdo_pgsql.xml
  ci/github/phpunit/sqlite.xml
  phpunit.xml.dist
Labels: Test Suite

#9487 Fix `#[DiscriminatorMap]` params
  docs/en/reference/attributes-reference.rst
Labels: Documentation

#9491 PHPStan 1.4.6, Psalm 4.20.0
  composer.json
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9489 Avoid calling `merge()`
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
Labels: Test Suite

#9488 Remove ability to merge detached entities
  UPGRADE.md
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Mapping/Reflection/ReflectionPropertiesGetter.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/DetachedEntityTest.php
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeCompositeToOneKeyTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeSharedEntitiesTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeVersionedManyToOneTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC117Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1276Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1383Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1392Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1509Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1594Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1734Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2230Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2409Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2645Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3699Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC501Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC518Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC729Test.php
  tests/Doctrine/Tests/ORM/Mapping/Reflection/ReflectionPropertiesGetterTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: BC Break

#9474 Fix types on EntityRepository
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/LazyCriteriaCollection.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9492 Fix types on QueryBuilder
  lib/Doctrine/ORM/Query/Expr/Join.php
  lib/Doctrine/ORM/Query/Parameter.php
  lib/Doctrine/ORM/QueryBuilder.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2090Test.php
  tests/Doctrine/Tests/ORM/QueryBuilderTest.php
Labels: Static Analysis

#9493 Added "false" value to $columnPrefix type declaration.
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
Labels: Static Analysis

#9498 Remove various deprecated methods and properties
  lib/Doctrine/ORM/Mapping/Builder/FieldBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  lib/Doctrine/ORM/Query/AST/IndexBy.php
  psalm-baseline.xml
Labels: BC Break

#9490 Add native types to QueryBuilder
  lib/Doctrine/ORM/Query/Expr/Join.php
  lib/Doctrine/ORM/Query/Parameter.php
  lib/Doctrine/ORM/Query/ParameterTypeInferer.php
  lib/Doctrine/ORM/QueryBuilder.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/QueryBuilderTest.php
Labels: BC Break

#9500 Remove quoting methods from ClassMetadata
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  psalm-baseline.xml
Labels: BC Break

#9504 Fix AbstractQuery::setParameter phpdoc
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Static Analysis

#9501 Constructor-Argument "options" has the same type as the associated property.
  lib/Doctrine/ORM/Mapping/Index.php
Labels: Static Analysis

#9507 Fix types on caches
  lib/Doctrine/ORM/Cache.php
  lib/Doctrine/ORM/Cache/AssociationCacheEntry.php
  lib/Doctrine/ORM/Cache/CacheException.php
  lib/Doctrine/ORM/Cache/CacheFactory.php
  lib/Doctrine/ORM/Cache/CacheKey.php
  lib/Doctrine/ORM/Cache/CollectionCacheEntry.php
  lib/Doctrine/ORM/Cache/CollectionCacheKey.php
  lib/Doctrine/ORM/Cache/CollectionHydrator.php
  lib/Doctrine/ORM/Cache/DefaultCache.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/EntityCacheEntry.php
  lib/Doctrine/ORM/Cache/EntityCacheKey.php
  lib/Doctrine/ORM/Cache/Logging/CacheLogger.php
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Cache/QueryCacheEntry.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Cache/TimestampCacheEntry.php
  lib/Doctrine/ORM/Cache/TimestampRegion.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Cache/AbstractRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheFactoryTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCollectionHydratorTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/FileLockRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/MultiGetRegionTest.php
Labels: Deprecation, Static Analysis

#9511 Replace `TreeWalkerChainIterator` with a generator
  UPGRADE.md
  lib/Doctrine/ORM/Query/TreeWalkerChain.php
  lib/Doctrine/ORM/Query/TreeWalkerChainIterator.php
  psalm-baseline.xml
Labels: Improvement, Deprecation

#9513 Fix syntax typo in attributes reference in documentation
  docs/en/reference/attributes-reference.rst
Labels: Documentation

#9512 Document deprecation of `AbstractCollectionPersister` helpers
  UPGRADE.md
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
Labels: Deprecation

#9520 Remove `TreeWalkerChainIterator`
  UPGRADE.md
  lib/Doctrine/ORM/Query/TreeWalkerChainIterator.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: BC Break

#9515 Add native types to EntityRepository
  lib/Doctrine/ORM/EntityRepository.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Repository/DefaultRepositoryFactoryTest.php
Labels: BC Break

#9523 Bring `FilterCollection` to a "clean" state after hash computation
  lib/Doctrine/ORM/Query/FilterCollection.php
  phpstan-baseline.neon
  tests/Doctrine/Tests/ORM/Query/FilterCollectionTest.php
Labels: Bug

#9525 Fix more types on EntityRepository and FilterCollection
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Query/FilterCollection.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Query/FilterCollectionTest.php
  tests/Doctrine/Tests/ORM/Repository/DefaultRepositoryFactoryTest.php
Labels: Static Analysis

#9508 Add native types to caches
  UPGRADE.md
  lib/Doctrine/ORM/Cache.php
  lib/Doctrine/ORM/Cache/AssociationCacheEntry.php
  lib/Doctrine/ORM/Cache/CacheConfiguration.php
  lib/Doctrine/ORM/Cache/CacheException.php
  lib/Doctrine/ORM/Cache/CacheFactory.php
  lib/Doctrine/ORM/Cache/CacheKey.php
  lib/Doctrine/ORM/Cache/CollectionCacheEntry.php
  lib/Doctrine/ORM/Cache/CollectionCacheKey.php
  lib/Doctrine/ORM/Cache/CollectionHydrator.php
  lib/Doctrine/ORM/Cache/DefaultCache.php
  lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
  lib/Doctrine/ORM/Cache/DefaultCollectionHydrator.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/EntityCacheEntry.php
  lib/Doctrine/ORM/Cache/EntityCacheKey.php
  lib/Doctrine/ORM/Cache/Lock.php
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Cache/QueryCache.php
  lib/Doctrine/ORM/Cache/QueryCacheEntry.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Cache/QueryCacheValidator.php
  lib/Doctrine/ORM/Cache/Region/DefaultRegion.php
  lib/Doctrine/ORM/Cache/Region/FileLockRegion.php
  lib/Doctrine/ORM/Cache/RegionsConfiguration.php
  lib/Doctrine/ORM/Cache/TimestampCacheEntry.php
  lib/Doctrine/ORM/Cache/TimestampCacheKey.php
  lib/Doctrine/ORM/Cache/TimestampQueryCacheValidator.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Cache/AbstractRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/CacheConfigTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheFactoryTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCacheTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultCollectionHydratorTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Cache/DefaultRegionTest.php
  tests/Doctrine/Tests/ORM/Cache/FileLockRegionTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheAbstractTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheConcurrentTest.php
Labels: BC Break

#9535 Leverage the `Stringable` interface
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/ORMInvalidArgumentExceptionTest.php
Labels: Improvement

#9539 Drop minor version number
  .github/workflows/continuous-integration.yml
Labels: CI

#9537 Make error message suggestion accurate
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php
Labels: Missing Tests, Bug

#9524 Add native types to SQLFilter
  lib/Doctrine/ORM/Query/Filter/SQLFilter.php
  lib/Doctrine/ORM/Query/FilterCollection.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/SQLFilterTest.php
  tests/Doctrine/Tests/ORM/Query/FilterCollectionTest.php
Labels: BC Break

#9532 Un-deprecate the current proxy mechanism
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Proxy/Proxy.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  psalm-baseline.xml
Labels: Deprecation

#9541 Improve templating
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php
  lib/Doctrine/ORM/Mapping/Driver/RepeatableAttributeCollection.php
  lib/Doctrine/ORM/Repository/RepositoryFactory.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeReaderTest.php
Labels: Static Analysis

#9527 Document QueryComponent array shape
  lib/Doctrine/ORM/Query/AST/Functions/IdentityFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/SizeFunction.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Query/TreeWalker.php
  lib/Doctrine/ORM/Query/TreeWalkerAdapter.php
  lib/Doctrine/ORM/Query/TreeWalkerChain.php
  lib/Doctrine/ORM/Tools/Pagination/CountOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9546 Update baselines for Lexer 1.2.3
  composer.json
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#9549 Leverage Lexer's Token type
  composer.json
  lib/Doctrine/ORM/Query/Parser.php
  psalm-baseline.xml
Labels: Static Analysis
