Repository doctrine/orm, pull requests merged in 2022-11, with the labels that each got.

#10040 Add lockMode to EntityManager#refresh()
  docs/en/reference/transactions-and-concurrency.rst
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/UnitOfWork.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/Locking/LockTest.php
Labels: New Feature

#10197 Backport `NonProxyLoadingEntityManager::refresh()` signature change
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
Labels: Test Suite

#10205 Avoid references to annotations
  lib/Doctrine/ORM/Mapping/AssociationOverride.php
  lib/Doctrine/ORM/Mapping/AssociationOverrides.php
  lib/Doctrine/ORM/Mapping/AttributeOverride.php
  lib/Doctrine/ORM/Mapping/AttributeOverrides.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/EntityListeners.php
  lib/Doctrine/ORM/Mapping/MappingException.php
Labels: Improvement, Documentation

#10204 Rename internal methods
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php
  psalm.xml
  tests/Doctrine/Tests/ORM/Mapping/AttributeReaderTest.php
Labels: Deprecation

#10206 Use a more accurate name for $annotationName
  lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php
Labels: Improvement

#10210 Migrate Cache namespace to php 8
  lib/Doctrine/ORM/Cache/AssociationCacheEntry.php
  lib/Doctrine/ORM/Cache/CacheKey.php
  lib/Doctrine/ORM/Cache/CollectionCacheEntry.php
  lib/Doctrine/ORM/Cache/CollectionCacheKey.php
  lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
  lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/EntityCacheEntry.php
  lib/Doctrine/ORM/Cache/EntityCacheKey.php
  lib/Doctrine/ORM/Cache/Persister/Entity/NonStrictReadWriteCachedEntityPersister.php
  lib/Doctrine/ORM/Cache/QueryCacheEntry.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Cache/Region/DefaultRegion.php
  lib/Doctrine/ORM/Cache/Region/FileLockRegion.php
  lib/Doctrine/ORM/Cache/TimestampCacheEntry.php
  lib/Doctrine/ORM/Cache/TimestampCacheKey.php
  lib/Doctrine/ORM/Cache/TimestampQueryCacheValidator.php
  lib/Doctrine/ORM/Mapping/AttributeOverrides.php
  psalm-baseline.xml
  tests/Doctrine/Tests/Mocks/CacheKeyMock.php
  tests/Doctrine/Tests/ORM/Cache/DefaultQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheQueryCacheTest.php
Labels: Improvement

#10199 refactor: use list type in SchemaTool
  lib/Doctrine/ORM/Tools/SchemaTool.php
Labels: Static Analysis

#10202 Allow "Expr\Func" as condition in join in PHPDoc
  lib/Doctrine/ORM/Query/Expr/Join.php
  lib/Doctrine/ORM/QueryBuilder.php
  tests/Doctrine/Tests/ORM/QueryBuilderTest.php
Labels: Static Analysis

#10213 Psalm 4.30.0, PHPStan 1.9.2
  composer.json
  lib/Doctrine/ORM/Query/Expr/Base.php
  psalm-baseline.xml
Labels: Static Analysis

#10212 Add a constructor to `CacheKey`
  UPGRADE.md
  lib/Doctrine/ORM/Cache/CacheKey.php
  lib/Doctrine/ORM/Cache/CollectionCacheKey.php
  lib/Doctrine/ORM/Cache/EntityCacheKey.php
  lib/Doctrine/ORM/Cache/QueryCacheKey.php
  lib/Doctrine/ORM/Cache/TimestampCacheKey.php
  psalm.xml
  tests/Doctrine/Tests/Mocks/CacheKeyMock.php
  tests/Doctrine/Tests/ORM/Cache/CacheKeyTest.php
Labels: Deprecation

#10218 Ignore PropertyNotSetInConstructor
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#10231 Make the code easier to statically analyse
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Query/Expr.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
Labels: Static Analysis

#10238 Use more precise phpdoc
  lib/Doctrine/ORM/Query.php
Labels: Static Analysis

#10242 Solve some PHPStan baseline errors
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#10243 Migrate persisters to PHP 8 syntax
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/CachedPersisterContext.php
  lib/Doctrine/ORM/Persisters/Entity/SingleTablePersister.php
  lib/Doctrine/ORM/Persisters/PersisterException.php
  lib/Doctrine/ORM/Persisters/SqlExpressionVisitor.php
  lib/Doctrine/ORM/Persisters/SqlValueVisitor.php
  phpstan-baseline.neon
Labels: BC Break, Static Analysis

#10247 Fix types for Paginator
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  psalm-baseline.xml
Labels: Static Analysis

#10248 Psalm 5 fixes
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/Export/Driver/PhpExporter.php
  lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#10261 Bump Psalm to 5.0.0 and fix errors for Symfony 6.2
  composer.json
  lib/Doctrine/ORM/Tools/Console/Command/AbstractEntityManagerCommand.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ClearCacheEntityRegionCommandTest.php
Labels: Static Analysis, Test Suite
