Repository doctrine/orm, pull requests merged in 2022-07, with the labels that each got.

#9870 [GH-9807] Fix: initialize potentially empty collections at the hydration complete
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9807Test.php
Labels: Bug

#9876 Change parent classes in some events
  UPGRADE.md
  lib/Doctrine/ORM/Event/OnClearEventArgs.php
  lib/Doctrine/ORM/Event/OnFlushEventArgs.php
  lib/Doctrine/ORM/Event/PostFlushEventArgs.php
  lib/Doctrine/ORM/Event/PreFlushEventArgs.php
  lib/Doctrine/ORM/Tools/DebugUnitOfWorkListener.php
  tests/Doctrine/Tests/ORM/Functional/FlushEventTest.php
  tests/Doctrine/Tests/ORM/Functional/PostFlushEventTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2790Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3160Test.php
Labels: Deprecation

#9880 Fix typo in AbstractQuery
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Documentation

#9887 PHPStan 1.8.0
  composer.json
Labels: Static Analysis

#9895 Avoid SQL assertions
  tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneEagerLoadingTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6823Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7012Test.php
Labels: Test Suite

#9851 Migrate more code to PHP8
  lib/Doctrine/ORM/Tools/AttachEntityListenersListener.php
  lib/Doctrine/ORM/Tools/DebugUnitOfWorkListener.php
  lib/Doctrine/ORM/Tools/ResolveTargetEntityListener.php
  lib/Doctrine/ORM/Utility/IdentifierFlattener.php
Labels: BC Break

#9906 Deprecate `LifecycleEventArgs`
  UPGRADE.md
  docs/en/cookbook/strategy-cookbook-introduction.rst
  docs/en/reference/events.rst
  lib/Doctrine/ORM/Event/LifecycleEventArgs.php
  lib/Doctrine/ORM/Event/PreUpdateEventArgs.php
  psalm.xml
  tests/Doctrine/Tests/Models/Company/CompanyFlexUltraContractListener.php
  tests/Doctrine/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Doctrine/Tests/ORM/Functional/PostLoadEventTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2602Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3033Test.php
  tests/Doctrine/Tests/ORM/Internal/HydrationCompleteHandlerTest.php
Labels: Deprecation

#9907 Add tests for SQL output feature
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/AbstractCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/CreateCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/DropCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/Models/Keyboard.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/UpdateCommandTest.php
Labels: Test Suite

#9900 Migrate part of the tools namespace to PHP8 syntax
  lib/Doctrine/ORM/LazyCriteriaCollection.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Tools/Console/Command/MappingDescribeCommand.php
  lib/Doctrine/ORM/Tools/Console/MetadataFilter.php
  lib/Doctrine/ORM/Tools/Event/GenerateSchemaEventArgs.php
  lib/Doctrine/ORM/Tools/Event/GenerateSchemaTableEventArgs.php
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/Tools/ToolsException.php
Labels: BC Break

#9903 schema tool: remove useless text from --dump-sql output
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/CreateCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/DropCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/CreateCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/DropCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/UpdateCommandTest.php
Labels: Bug

#9924 Adjust casing of `SQLitePlatform` for DBAL 4
  tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
  tests/Doctrine/Tests/ORM/Functional/SchemaTool/DDC214Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1695Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC933Test.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/AbstractCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/ValidateSchemaCommandTest.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Bug

#9923 Add native types to QuoteStrategy classes
  lib/Doctrine/ORM/Mapping/AnsiQuoteStrategy.php
  lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php
  lib/Doctrine/ORM/Mapping/QuoteStrategy.php
Labels: BC Break, Static Analysis

#9922 Widen types for DiscriminatorMap
  lib/Doctrine/ORM/Internal/Hydration/HydrationException.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/DiscriminatorMap.php
  lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
  psalm-baseline.xml
Labels: Static Analysis

#9927 GH9335: Fix for bug with objects as foreign keys
  lib/Doctrine/ORM/Utility/IdentifierFlattener.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9335Test.php
Labels: Bug

#9793 Update IdentifierFlattener.php
  lib/Doctrine/ORM/Utility/IdentifierFlattener.php
Labels: Bug

#9930 Simplify `LanguageRecognitionTest`
  tests/Doctrine/Tests/ORM/Query/LanguageRecognitionTest.php
Labels: Test Suite

#9932 Add helper function `TreeWalkerAdapter::getMetadataForDqlAlias()`
  lib/Doctrine/ORM/Query/TreeWalkerAdapter.php
  lib/Doctrine/ORM/Tools/Pagination/CountWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  lib/Doctrine/ORM/Tools/Pagination/WhereInWalker.php
Labels: Improvement, Static Analysis

#9551 Split TreeWalker and SqlWalker
  UPGRADE.md
  lib/Doctrine/ORM/Query/QueryException.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Query/TreeWalker.php
  lib/Doctrine/ORM/Query/TreeWalkerAdapter.php
  lib/Doctrine/ORM/Query/TreeWalkerChain.php
  lib/Doctrine/ORM/Tools/Pagination/CountOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/CountWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  lib/Doctrine/ORM/Tools/Pagination/WhereInWalker.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/Mocks/NullSqlWalker.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC736Test.php
  tests/Doctrine/Tests/ORM/Query/CustomTreeWalkersTest.php
  tests/Doctrine/Tests/ORM/Query/TreeWalkerAdapterTest.php
Labels: BC Break

#9937 Use a more precise phpdoc for ClassMetadataInfo::versionField than mixed
  lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Static Analysis

#9938 Stop passing event manager to constructor
  tests/Doctrine/Tests/Mocks/EntityManagerMock.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Test Suite

#9941 Psalm 4.25.0, PHPStan 1.8.2
  composer.json
  psalm-baseline.xml
Labels: Static Analysis

#9943 Update branch info in README and .doctrine-project.json
  .doctrine-project.json
  README.md
Labels: Documentation
