Repository doctrine/orm, pull requests merged in 2023-12, with the labels that each got.

#11076 Fix JSON mapping linting against subset of builtin types
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11072/GH11072EntityAdvanced.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11072/GH11072EntityBasic.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11072/GH11072Test.php
Labels: Bug

#11104 Fix method name in code example
  docs/en/cookbook/resolve-target-entity-listener.rst
Labels: Documentation

#7963 Improve docs: INSTANCE OF needs class metadata as parameter value
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation

#11115 Fix: Typo
  lib/Doctrine/ORM/EntityManager.php
Labels: Improvement

#11122 Fix enum mapping validation
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/EntityStatus.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/GH11037Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/InvalidEntityWithTypedEnum.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/StringEntityStatus.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/ValidEntityWithTypedEnum.php
Labels: Bug

#11130 Allow to skip property type validation
  lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10661/GH10661Test.php
Labels: Improvement

#11134 Mention in the limitations that private field names cannot be reused
  docs/en/reference/limitations-and-known-issues.rst
Labels: Documentation
