Repository doctrine/orm, pull requests merged in 2023-07, with the labels that each got.

#10812 Remove lone dash
  docs/en/reference/query-builder.rst
Labels: Documentation

#10785 Add a safeguard against multiple objects competing for the same identity map entry
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/ProxiesLikeEntitiesTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1238Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7869Test.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Improvement

#10815 Introduce new workflow to test docs
  .github/workflows/documentation.yml
  docs/en/index.rst
  docs/en/reference/architecture.rst
  docs/en/reference/basic-mapping.rst
  docs/en/reference/configuration.rst
  docs/en/reference/dql-doctrine-query-language.rst
  docs/en/reference/improving-performance.rst
  docs/en/reference/inheritance-mapping.rst
  docs/en/reference/installation.rst
  docs/en/reference/limitations-and-known-issues.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation, CI

#10813 Let XML driver treat <id> field attributes same as regular <field> tag
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
Labels: Bug

#10806 Fix enum change set recomputation on single entity
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
Labels: Bug

#10819 Fix cloning entities when using lazy-ghost proxies
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Proxy/ProxyFactoryTest.php
Labels: Bug

#10735 Make it possible to have non-NULLable self-referencing associations when using application-provided IDs
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  tests/Doctrine/Tests/ORM/Functional/GH7877Test.php
Labels: Improvement

#10828 Match namespace in XML file with namespace in XSD file
  docs/en/reference/events.rst
  docs/en/reference/second-level-cache.rst
  docs/en/reference/xml-mapping.rst
  docs/en/tutorials/composite-primary-keys.rst
  docs/en/tutorials/extra-lazy-associations.rst
  docs/en/tutorials/getting-started.rst
  docs/en/tutorials/working-with-indexed-associations.rst
Labels: Documentation

#10799 Improve and add test to set to-one and to-many associations with reference objects
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
Labels: Test Suite

#10824 Add dummy title to the sidebar before checking docs
  .github/workflows/documentation.yml
  docs/en/sidebar.rst
Labels: CI

#10842 PHPStan 1.10.25, Psalm 5.13.1
  composer.json
  psalm-baseline.xml
Labels: Static Analysis

#10843 Declare compatibility with DBAL 4
  composer.json
Labels: Improvement

#10847 Remove toc
  docs/en/index.rst
  docs/en/toc.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#10848 Use properties instead of getters to read property/class names via reflection
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/ReflectionBasedDriver.php
  lib/Doctrine/ORM/Mapping/Reflection/ReflectionPropertiesGetter.php
  lib/Doctrine/ORM/Mapping/ReflectionEmbeddedProperty.php
  lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
Labels: Improvement

#10853 Remove outdated comment
  lib/Doctrine/ORM/EntityManager.php
Labels: Documentation

#10855 fix: use platform options instead of deprecated custom options
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Tools/SchemaToolTest.php
Labels: Bug

#10537 Introduce FilterCollection#restore method
  docs/en/reference/filters.rst
  lib/Doctrine/ORM/Query/FilterCollection.php
  tests/Doctrine/Tests/ORM/Query/FilterCollectionTest.php
Labels: New Feature
