Repository doctrine/orm, pull requests merged in 2023-05, with the labels that each got.

#10646 Migrate basic entity persister to the object API of association mapping
  lib/Doctrine/ORM/Mapping/AssociationMapping.php
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  lib/Doctrine/ORM/Utility/PersisterHelper.php
  phpstan.neon
  psalm-baseline.xml
Labels: Improvement

#10667 Throw on invalid one to one
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php
Labels: BC Break

#10668 Added doc for the fields parameter of the UniqueConstraint attribute
  docs/en/reference/attributes-reference.rst
Labels: Documentation

#10674 Bump version numbers in the README
  README.md
Labels: Documentation

#10671 Fix attribute ManyToMany mapping
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/Fixtures/AttributeEntityWithNestedJoinColumns.php
Labels: Bug

#10679 Upgrade to Psalm 5.11.0
  composer.json
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#10684 Support unserializing 2.14 ParserResult instances
  lib/Doctrine/ORM/Query/ParserResult.php
  tests/Doctrine/Tests/ORM/Functional/ParserResultSerializationTest.php
  tests/Doctrine/Tests/ORM/Functional/ParserResults/single_select_2_14_3.txt
  tests/Doctrine/Tests/ORM/Functional/ParserResults/single_select_2_15_0.txt
Labels: Bug

#10686 Documentation typo
  docs/en/tutorials/getting-started-database.rst
Labels: Documentation

#10687 Make indexBy/orderBy easier to understand for SA
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Collection/NonStrictReadWriteCachedCollectionPersister.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Mapping/AssociationMapping.php
  lib/Doctrine/ORM/Mapping/ToManyAssociationMapping.php
  lib/Doctrine/ORM/Mapping/ToManyAssociationMappingImplementation.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/MappingDriverTestCase.php
Labels: Static Analysis

#10455 Make Annotations/Attribute mapping drivers report fields for the classes where they are declared
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  lib/Doctrine/ORM/Mapping/Driver/ReflectionBasedDriver.php
  lib/Doctrine/ORM/ORMSetup.php
  tests/Doctrine/Tests/DoctrineTestCase.php
  tests/Doctrine/Tests/Models/Company/CompanyFlexContract.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
  tests/Doctrine/Tests/ORM/Functional/MergeProxiesTest.php
  tests/Doctrine/Tests/ORM/Functional/ReadonlyPropertiesTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC719Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10450Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10454Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH5998Test.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Improvement, Deprecation

#10688 Introduce method to get to the owning side
  lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Query/AST/Functions/SizeFunction.php
  lib/Doctrine/ORM/Query/SqlWalker.php
Labels: Improvement

#10486 Fix to-many collections left in dirty state after entities are removed by the UoW
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/ManyToManyEventTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Bug

#10666 Create `ReflectionReadonlyProperty` from their declaring class so their value can be set
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10049/GH10049Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10049/ReadOnlyPropertyInheritor.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10049/ReadOnlyPropertyOwner.php
Labels: Bug

#10700 fix wrong phpdoc
  lib/Doctrine/ORM/Tools/SchemaTool.php
Labels: Static Analysis

#10701 Introduce convenience methods to narrow types
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php
  phpstan.neon
  psalm-baseline.xml
Labels: Static Analysis

#10721 Narrow return types for `AbstractQuery::getSingleScalarResult()`
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Static Analysis

#10722 Fix and improve functional test cases expecting `NonUniqueResultException` from `AbstractQuery::getSingleScalarResult()`
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
Labels: Test Suite

#10724 Temporarily allow `symfony/console` 7
  composer.json
Labels: Improvement

#10728 Declare options property
  lib/Doctrine/ORM/Mapping/JoinTableMapping.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  tests/Doctrine/Tests/ORM/Mapping/JoinTableMappingTest.php
Labels: Bug

#10730 Migrate to the object API of Join{Column,Table}Mapping
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Mapping/AnsiQuoteStrategy.php
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php
  lib/Doctrine/ORM/Mapping/JoinTableMapping.php
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Collection/OneToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Persisters/Entity/SingleTablePersister.php
  lib/Doctrine/ORM/Query/AST/Functions/IdentityFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/SizeFunction.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/Pagination/CountOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  lib/Doctrine/ORM/UnitOfWork.php
  lib/Doctrine/ORM/Utility/IdentifierFlattener.php
  lib/Doctrine/ORM/Utility/PersisterHelper.php
  tests/Doctrine/Tests/ORM/Mapping/AttributeDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Doctrine/Tests/ORM/Mapping/MappingDriverTestCase.php
Labels: Improvement
