Repository doctrine/orm, pull requests merged in 2023-01, with the labels that each got.

#10359 PHPStan 1.9.5
  composer.json
  lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php
  phpstan-baseline.neon
  phpstan-persistence2.neon
  psalm-baseline.xml
Labels: Static Analysis

#10363 Docs: Deleting duplicate mapping example
  docs/en/tutorials/composite-primary-keys.rst
Labels: Documentation

#10364 Docs: Moving *attributes* mapping to first position
  docs/en/tutorials/composite-primary-keys.rst
Labels: Documentation

#10367 Migrate files with the least changes to PHP 8
  lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
  lib/Doctrine/ORM/EntityRepository.php
  lib/Doctrine/ORM/Id/AssignedGenerator.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Mapping/ChainTypedFieldMapper.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php
  lib/Doctrine/ORM/Query/Filter/SQLFilter.php
Labels: Static Analysis

#10365 Address new behavior of $firstResult
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/SqlWalker.php
Labels: Static Analysis

#10372 Use the same type as in the DBAL
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  psalm-baseline.xml
Labels: Static Analysis

#10375 Remove deprecated methods and classes
  UPGRADE.md
  lib/Doctrine/ORM/Event/LifecycleEventArgs.php
  lib/Doctrine/ORM/Event/OnClearEventArgs.php
  lib/Doctrine/ORM/Event/OnFlushEventArgs.php
  lib/Doctrine/ORM/Event/PostFlushEventArgs.php
  lib/Doctrine/ORM/Event/PostLoadEventArgs.php
  lib/Doctrine/ORM/Event/PostPersistEventArgs.php
  lib/Doctrine/ORM/Event/PostRemoveEventArgs.php
  lib/Doctrine/ORM/Event/PostUpdateEventArgs.php
  lib/Doctrine/ORM/Event/PreFlushEventArgs.php
  lib/Doctrine/ORM/Event/PrePersistEventArgs.php
  lib/Doctrine/ORM/Event/PreRemoveEventArgs.php
  lib/Doctrine/ORM/Event/PreUpdateEventArgs.php
  psalm.xml
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2996Test.php
Labels: BC Break

#10382 PHPStan 1.9.8, Psalm 5.4.0
  composer.json
  psalm-baseline.xml
Labels: Static Analysis

#10381 Use more precise types for class strings
  lib/Doctrine/ORM/Mapping/MappingException.php
  psalm-baseline.xml
Labels: Static Analysis

#10380 Migrate exceptions to PHP 8 syntax
  lib/Doctrine/ORM/Mapping/MappingException.php
  lib/Doctrine/ORM/Query/QueryException.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  psalm-baseline.xml
Labels: BC Break

#10399 Fix DDL example for Mapped Superclasses
  docs/en/reference/inheritance-mapping.rst
Labels: Documentation

#10390 Use more accurate phpdoc for OptimisticLockException
  lib/Doctrine/ORM/OptimisticLockException.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#10394 Write down what "transient" means
  docs/en/reference/architecture.rst
Labels: Documentation

#10396 Document the meanings of 'inherited' and 'declared' in field mapping information
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Documentation

#10397 Factor out logic that tracks mapping inheritance
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
Labels: Improvement

#10393 Place a warning about the uses of traits in the documentation
  docs/en/reference/inheritance-mapping.rst
  docs/en/reference/limitations-and-known-issues.rst
Labels: Documentation

#10406 Test with a stable PHPUnit
  composer.json
Labels: Test Suite

#10412 Adding link to Attributes reference
  docs/en/reference/improving-performance.rst
Labels: Documentation

#10403 Reuse association mapping array shape
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
Labels: Static Analysis

#10418 Use correct type for FieldMapping#unique
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Static Analysis

#10424 Fixup GH8127 test case
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8127Test.php
Labels: Test Suite

#10423 Add deprecations for "table per class" inheritance
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/InheritanceType.php
  psalm.xml
Labels: Deprecation

#10428 Fix version number in UPGRADE.md
  UPGRADE.md
Labels: Documentation

#10430 Use FieldMapping array shape even more
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  psalm-baseline.xml
Labels: Static Analysis

#10429 Review the documentation regarding entity inheritance
  docs/en/reference/inheritance-mapping.rst
Labels: Documentation

#10436 Update Psalm baseline
  psalm-baseline.xml
Labels: Static Analysis

#10426 Slight docblock improvements for `CM::parentClasses`
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Documentation

#10433 Make sure tests from #7837 are actually run
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php
Labels: Test Suite

#10441 Use the right property
  tests/Doctrine/Tests/ORM/Functional/OneToOneBidirectionalAssociationTest.php
Labels: Test Suite

#10156 Identity map cannot contains null value
  lib/Doctrine/ORM/UnitOfWork.php
  psalm-baseline.xml
Labels: Static Analysis

#10442 Add embedded class mapping array shape
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  psalm.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php
Labels: Static Analysis

#10443 Replace hardcoded name with `Command::getName()` in output message from `UpdateCommand`
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/CommandTestCase.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/UpdateCommandTest.php
Labels: Bug

#10434 Avoid wasting Opcache memory with Paginator queries
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7820Test.php
Labels: Bug

#10445 Psalm 5.5.0
  composer.json
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#10448 Migrate ParserResult to PHP 8 syntax
  lib/Doctrine/ORM/Query/ParserResult.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Query/ParserResultTest.php
Labels: BC Break

#10431 Deprecate undeclared entity inheritance
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  tests/Doctrine/Tests/Models/DDC1590/DDC1590Entity.php
  tests/Doctrine/Tests/Models/DDC2372/DDC2372User.php
  tests/Doctrine/Tests/Models/DDC5934/DDC5934BaseContract.php
  tests/Doctrine/Tests/Models/Forum/ForumAdministrator.php
  tests/Doctrine/Tests/ORM/Mapping/BasicInheritanceMappingTest.php
Labels: Deprecation

#10465 Remove commented-out code sections
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  tests/Doctrine/Tests/ORM/Mapping/BasicInheritanceMappingTest.php
Labels: Code Style

#10464 Fix some tests that were missed in #10431
  tests/Doctrine/Tests/Models/DDC5934/DDC5934BaseContract.php
  tests/Doctrine/Tests/ORM/Mapping/php/Doctrine.Tests.Models.DDC5934.DDC5934BaseContract.php
  tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC5934.DDC5934BaseContract.dcm.xml
Labels: Test Suite

#10468 Psalm 5.6.0, PHPStan 1.9.14
  composer.json
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis

#10453 Add regression test for a to-many relationship on a base class & mapped superclass in the hierarchy
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9516Test.php
Labels: Test Suite

#10477 Remove underscore prefix on private variables
  lib/Doctrine/ORM/Id/SequenceGenerator.php
  lib/Doctrine/ORM/Id/TableGenerator.php
  lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/IterableResult.php
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/Exec/MultiTableDeleteExecutor.php
  lib/Doctrine/ORM/Query/Exec/MultiTableUpdateExecutor.php
  lib/Doctrine/ORM/Query/ParserResult.php
  lib/Doctrine/ORM/QueryBuilder.php
  lib/Doctrine/ORM/Tools/Export/Driver/AnnotationExporter.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  psalm-baseline.xml
Labels: Code Style

#10478 Move psalm types to ClassMetadata
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/UnitOfWork.php
Labels: Static Analysis

#10476 Hunt down invalid doc blocks
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis
