Repository doctrine/orm, pull requests merged in 2023-08, with the labels that each got.

#10547 Compute the commit order (inserts/deletes) on the entity level
  UPGRADE.md
  docs/en/reference/events.rst
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Internal/CommitOrder/Edge.php
  lib/Doctrine/ORM/Internal/CommitOrder/Vertex.php
  lib/Doctrine/ORM/Internal/CommitOrder/VertexState.php
  lib/Doctrine/ORM/Internal/CommitOrderCalculator.php
  lib/Doctrine/ORM/Internal/TopologicalSort.php
  lib/Doctrine/ORM/Internal/TopologicalSort/CycleDetectedException.php
  lib/Doctrine/ORM/UnitOfWork.php
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/Functional/OneToOneSelfReferentialAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10348Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10531Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10532Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10566Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6499OneToManyRelationshipTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6499OneToOneRelationshipTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH6499Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7006Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7180Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9192Test.php
  tests/Doctrine/Tests/ORM/Internal/TopologicalSortTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Improvement

#10727 Revert "Allow symfony/console 7"
  composer.json
Labels: Improvement

#10862 Update branch metadata
  .doctrine-project.json
Labels: Documentation

#10866 Add an UPGRADE notice about the potential changes in commit order
  UPGRADE.md
Labels: Documentation

#9301 Fix UnitOfWork->originalEntityData is missing not-modified collections after computeChangeSet
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/Models/Issue9300/Issue9300Child.php
  tests/Doctrine/Tests/Models/Issue9300/Issue9300Parent.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/Issue9300Test.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Bug

#10865 Add possibility to set reportFieldsWhereDeclared in ORMSetup
  docs/en/reference/advanced-configuration.rst
  lib/Doctrine/ORM/ORMSetup.php
Labels: Bug

#10878 Turn identity map collisions from exception to deprecation notice
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Bug, Deprecation

#10887 Add note about not-enabling lazy-ghosts
  UPGRADE.md
Labels: Documentation

#10884 Fix broken changeset computation for entities loaded through fetch=EAGER + using inheritance
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10880Test.php
Labels: Bug, Regression

#10883 Document more clearly that the insert order is an implementation detail
  docs/en/reference/working-with-objects.rst
Labels: Documentation

#10881 Use a dedicated exception for the check added in #10785
  lib/Doctrine/ORM/Exception/EntityIdentityCollisionException.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Bug

#10870 Fix return type of `getSingleScalarResult`
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Static Analysis

#10895 PHPStan 1.10.28, Psalm 5.14.1
  composer.json
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php
  lib/Doctrine/ORM/Tools/EntityGenerator.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  psalm-baseline.xml
Labels: Static Analysis

#10907 Add back throws annotation to getSingleScalarResult
  lib/Doctrine/ORM/AbstractQuery.php
Labels: Static Analysis

#10910 Remove PHPUnit polyfills
  tests/Doctrine/Tests/DoctrineTestCase.php
  tests/Doctrine/Tests/ORM/Cache/CacheConfigTest.php
  tests/Doctrine/Tests/ORM/Cache/CacheKeyTest.php
  tests/Doctrine/Tests/ORM/Cache/CacheLoggerChainTest.php
  tests/Doctrine/Tests/ORM/Cache/StatisticsCacheLoggerTest.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC4024Test.php
  tests/Doctrine/Tests/ORM/Tools/Console/ConsoleRunnerTest.php
  tests/Doctrine/Tests/OrmTestCase.php
Labels: Test Suite

#10918 Add space before backquote
  docs/en/cookbook/implementing-the-notify-changetracking-policy.rst
  docs/en/reference/change-tracking-policies.rst
  docs/en/reference/dql-doctrine-query-language.rst
  docs/en/reference/partial-objects.rst
  docs/en/reference/unitofwork.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#10919 Support Symfony 7 by adding return types conditionally
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/CollectionRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/EntityRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryRegionCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ClearCache/ResultCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ConvertMappingCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/EnsureProductionSettingsCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateEntitiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateProxiesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/GenerateRepositoriesCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/InfoCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php
  lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
  lib/Doctrine/ORM/Tools/Console/CommandCompatibility.php
  lib/Doctrine/ORM/Tools/Console/Helper/EntityManagerHelper.php
  phpcs.xml.dist
  psalm.xml
Labels: Improvement

#10923 basic-mapping: fix new-line rendered in output
  docs/en/reference/basic-mapping.rst
Labels: Documentation
