Repository doctrine/orm, pull requests merged in 2023-10, with the labels that each got.

#10968 Reject ID collisions in identity map unconditionally
  UPGRADE.md
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: BC Break

#10971 Restore job with --prefer-lowest
  .github/workflows/continuous-integration.yml
  composer.json
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
Labels: CI

#10972 update actions/checkout to v4
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/phpbench.yml
  .github/workflows/static-analysis.yml
Labels: CI

#10969 Use lazy ghosts unconditionally
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  composer.json
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Proxy/InternalProxy.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/TestUtil.php
Labels: BC Break

#10963 Test against php 8.3
  .github/workflows/continuous-integration.yml
Labels: CI

#10974 Remove partial object expression usage
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
Labels: Improvement

#10975 Change EntityPersister return type
  UPGRADE.md
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/Mocks/EntityPersisterMock.php
  tests/Doctrine/Tests/ORM/Cache/Persister/Entity/EntityPersisterTestCase.php
Labels: BC Break

#10980 Don't assert that BIGINTs are stored as strings
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3634Test.php
Labels: Test Suite

#10984 Allow VarExporter 7
  composer.json
Labels: Improvement

#10987 Deprecate EntityManager*::getPartialReference()
  UPGRADE.md
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  psalm.xml
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
Labels: Deprecation

#10332 Drop doctrine/lexer 2
  composer.json
  lib/Doctrine/ORM/Query/Lexer.php
Labels: Improvement

#10990 Allow creating mocks of the `Query` class
  lib/Doctrine/ORM/NativeQuery.php
  lib/Doctrine/ORM/Query.php
Labels: Improvement

#8931 Deprecate reliance on non-optimal defaults
  UPGRADE.md
  docs/en/reference/basic-mapping.rst
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  phpstan-dbal2.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: Deprecation

#10985 Remove partial syntax in DQL
  UPGRADE.md
  docs/en/index.rst
  docs/en/reference/dql-doctrine-query-language.rst
  docs/en/reference/partial-objects.rst
  docs/en/sidebar.rst
  lib/Doctrine/ORM/Cache/DefaultQueryCache.php
  lib/Doctrine/ORM/Cache/Exception/FeatureNotImplemented.php
  lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/EntityManagerInterface.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/AST/PartialObjectExpression.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/QueryException.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Query/TokenType.php
  lib/Doctrine/ORM/UnitOfWork.php
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Performance/Hydration/MixedQueryFetchJoinPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Hydration/SimpleQueryPartialObjectHydrationPerformanceBench.php
  tests/Doctrine/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/BasicFunctionalTest.php
  tests/Doctrine/Tests/ORM/Functional/DefaultValuesTest.php
  tests/Doctrine/Tests/ORM/Functional/OneToOneUnidirectionalAssociationTest.php
  tests/Doctrine/Tests/ORM/Functional/PostLoadEventTest.php
  tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheQueryCacheTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC1041Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC163Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2519Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8443Test.php
  tests/Doctrine/Tests/ORM/Functional/ValueObjectsTest.php
  tests/Doctrine/Tests/ORM/Query/LanguageRecognitionTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
Labels: BC Break

#10964 Updated order of mapping attribute parameters
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/Index.php
  lib/Doctrine/ORM/Mapping/OneToMany.php
  lib/Doctrine/ORM/Mapping/OneToOne.php
Labels: BC Break

#11001 Remove schema visitors
  lib/Doctrine/ORM/Tools/SchemaTool.php
  psalm.xml
Labels: Improvement, BC Break

#11006 Remove redundant check
  lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php
Labels: Improvement

#11009 Implement proxy name resolver
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Cache/DefaultCache.php
  lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php
  lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Collection/ReadOnlyCachedCollectionPersister.php
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Cache/Persister/Entity/ReadOnlyCachedEntityPersister.php
  lib/Doctrine/ORM/EntityManager.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Proxy/DefaultProxyClassNameResolver.php
  phpcs.xml.dist
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/PostLoadEventTest.php
  tests/Doctrine/Tests/ORM/Functional/ReferenceProxyTest.php
Labels: Improvement

#11000 Copy Debug class from doctrine/common
  lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
  lib/Doctrine/ORM/Tools/Debug.php
  phpcs.xml.dist
  psalm-baseline.xml
  psalm.xml
  tests/Doctrine/Tests/ORM/Tools/DebugTest.php
  tests/Doctrine/Tests/ORM/Tools/TestAsset/ChildClass.php
  tests/Doctrine/Tests/ORM/Tools/TestAsset/ChildWithSameAttributesClass.php
  tests/Doctrine/Tests/ORM/Tools/TestAsset/ParentClass.php
Labels: Improvement

#11012 Use native return type declarations in Debug class
  lib/Doctrine/ORM/Tools/Debug.php
Labels: Static Analysis

#10998 Sever ties to common
  UPGRADE.md
  composer.json
  lib/Doctrine/ORM/Proxy/Autoloader.php
  lib/Doctrine/ORM/Proxy/NotAProxyClass.php
  psalm-baseline.xml
  tests/Doctrine/Tests/Proxy/AutoloaderTest.php
Labels: BC Break

#11007 Address split of doctrine/common
  docs/en/reference/architecture.rst
Labels: Documentation

#11015 Make phpdoc accurate
  lib/Doctrine/ORM/Query/AST/ConditionalFactor.php
  lib/Doctrine/ORM/Query/AST/ConditionalPrimary.php
  lib/Doctrine/ORM/Query/AST/ConditionalTerm.php
  lib/Doctrine/ORM/Query/AST/HavingClause.php
  lib/Doctrine/ORM/Query/AST/Join.php
  lib/Doctrine/ORM/Query/AST/Phase2OptimizableConditional.php
  lib/Doctrine/ORM/Query/AST/WhenClause.php
  lib/Doctrine/ORM/Query/AST/WhereClause.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/Pagination/WhereInWalker.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Bug

#11013 Enforce native type declarations
  lib/Doctrine/ORM/Event/PreUpdateEventArgs.php
  lib/Doctrine/ORM/Exception/EntityIdentityCollisionException.php
  lib/Doctrine/ORM/Internal/TopologicalSort.php
  lib/Doctrine/ORM/Internal/TopologicalSort/CycleDetectedException.php
  lib/Doctrine/ORM/Mapping/AssociationMapping.php
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/ORMInvalidArgumentException.php
  lib/Doctrine/ORM/Persisters/Entity/CachedPersisterContext.php
  lib/Doctrine/ORM/Persisters/PersisterException.php
  lib/Doctrine/ORM/Persisters/SqlValueVisitor.php
  lib/Doctrine/ORM/Proxy/DefaultProxyClassNameResolver.php
  lib/Doctrine/ORM/Proxy/ProxyFactory.php
  lib/Doctrine/ORM/Query/AST/ArithmeticExpression.php
  lib/Doctrine/ORM/Query/AST/BetweenExpression.php
  lib/Doctrine/ORM/Query/AST/CollectionMemberExpression.php
  lib/Doctrine/ORM/Query/AST/ComparisonExpression.php
  lib/Doctrine/ORM/Query/AST/ConditionalFactor.php
  lib/Doctrine/ORM/Query/AST/ConditionalPrimary.php
  lib/Doctrine/ORM/Query/AST/DeleteStatement.php
  lib/Doctrine/ORM/Query/AST/EmptyCollectionComparisonExpression.php
  lib/Doctrine/ORM/Query/AST/ExistsExpression.php
  lib/Doctrine/ORM/Query/AST/Functions/IdentityFunction.php
  lib/Doctrine/ORM/Query/AST/Functions/SizeFunction.php
  lib/Doctrine/ORM/Query/AST/HavingClause.php
  lib/Doctrine/ORM/Query/AST/IdentificationVariableDeclaration.php
  lib/Doctrine/ORM/Query/AST/InstanceOfExpression.php
  lib/Doctrine/ORM/Query/AST/Join.php
  lib/Doctrine/ORM/Query/AST/JoinAssociationDeclaration.php
  lib/Doctrine/ORM/Query/AST/JoinVariableDeclaration.php
  lib/Doctrine/ORM/Query/AST/LikeExpression.php
  lib/Doctrine/ORM/Query/AST/QuantifiedExpression.php
  lib/Doctrine/ORM/Query/AST/SelectStatement.php
  lib/Doctrine/ORM/Query/AST/SimpleCaseExpression.php
  lib/Doctrine/ORM/Query/AST/SimpleSelectClause.php
  lib/Doctrine/ORM/Query/AST/SimpleSelectExpression.php
  lib/Doctrine/ORM/Query/AST/Subselect.php
  lib/Doctrine/ORM/Query/AST/SubselectIdentificationVariableDeclaration.php
  lib/Doctrine/ORM/Query/AST/UpdateItem.php
  lib/Doctrine/ORM/Query/AST/UpdateStatement.php
  lib/Doctrine/ORM/Query/AST/WhenClause.php
  lib/Doctrine/ORM/Query/AST/WhereClause.php
  lib/Doctrine/ORM/Query/Exec/SingleTableDeleteUpdateExecutor.php
  lib/Doctrine/ORM/Query/Expr.php
  lib/Doctrine/ORM/Query/Expr/Base.php
  lib/Doctrine/ORM/Query/Expr/Func.php
  lib/Doctrine/ORM/Query/Parser.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php
  lib/Doctrine/ORM/UnitOfWork.php
  phpcs.xml.dist
  phpstan-baseline.neon
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Query/CustomTreeWalkersTest.php
Labels: BC Break
