Repository doctrine/orm, pull requests merged in 2023-04, with the labels that each got.

#10609 Extract discriminator column mapping into its own DTO
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/DiscriminatorColumnMapping.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Persisters/Entity/SingleTablePersister.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataBuilderTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Doctrine/Tests/ORM/Mapping/DiscriminatorColumnMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/MappingDriverTestCase.php
Labels: BC Break

#10599 fix(persistent-collection): check association is not nullable before using it as an array
  lib/Doctrine/ORM/PersistentCollection.php
  psalm-baseline.xml
Labels: Improvement

#10612 Extract embedded class mapping into its own DTO
  lib/Doctrine/ORM/Mapping/Builder/ClassMetadataBuilder.php
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/EmbeddedClassMapping.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataBuilderTest.php
  tests/Doctrine/Tests/ORM/Mapping/DiscriminatorColumnMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/EmbeddedClassMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/FieldMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
Labels: Improvement, BC Break

#10519 Deprecate overriding associations not inherited from a mapped superclass
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
  tests/Doctrine/Tests/ORM/Mapping/BasicInheritanceMappingTest.php
Labels: Deprecation

#10587 Handle null comparisons in `ManyToManyPersister`
  lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/SqlValueVisitor.php
  tests/Doctrine/Tests/Models/GH7717/GH7717Child.php
  tests/Doctrine/Tests/Models/GH7717/GH7717Parent.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7717Test.php
Labels: Bug

#10620 fix typo in HydrationCompleteHandler doc
  lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php
Labels: Documentation

#10617 Use Rector to migrate to the object API of FieldMapping
  lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Mapping/AnsiQuoteStrategy.php
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php
  lib/Doctrine/ORM/Persisters/Entity/AbstractEntityInheritancePersister.php
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Persisters/Entity/SingleTablePersister.php
  lib/Doctrine/ORM/Query/AST/Functions/IdentityFunction.php
  lib/Doctrine/ORM/Query/Exec/MultiTableUpdateExecutor.php
  lib/Doctrine/ORM/Query/ResultSetMappingBuilder.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php
  lib/Doctrine/ORM/Tools/SchemaTool.php
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  lib/Doctrine/ORM/UnitOfWork.php
  lib/Doctrine/ORM/Utility/PersisterHelper.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/DatabaseDriverTest.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
  tests/Doctrine/Tests/ORM/Mapping/BasicInheritanceMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataBuilderTest.php
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Mapping/MappingDriverTestCase.php
  tests/Doctrine/Tests/ORM/Tools/SchemaToolTest.php
Labels: Improvement

#10632 Run tests on SQLite with foreign keys enabled
  tests/Doctrine/Tests/TestUtil.php
Labels: Test Suite

#10642 fix syntax array association on partial index documentation
  docs/en/reference/attributes-reference.rst
Labels: Documentation

#10644 Become strict about notices and warnings
  phpunit.xml.dist
Labels: Test Suite

#10641 Move $(sourceToTarget|targetToSource)KeyColumns down
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  lib/Doctrine/ORM/Mapping/ManyToOneAssociationMapping.php
  lib/Doctrine/ORM/Mapping/OneToOneOwningSideMapping.php
  lib/Doctrine/ORM/Mapping/ToOneAssociationMapping.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  tests/Doctrine/Tests/ORM/Mapping/ManyToOneAssociationMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/OneToOneOwningSideMappingTest.php
  tests/Doctrine/Tests/ORM/Mapping/ToOneAssociationMappingTest.php
Labels: Improvement

#10650 Improve named constructors' phpdoc
  lib/Doctrine/ORM/Mapping/JoinTableMapping.php
  lib/Doctrine/ORM/Mapping/ManyToManyOwningSideMapping.php
  lib/Doctrine/ORM/Mapping/OneToManyAssociationMapping.php
  psalm-baseline.xml
Labels: Improvement

#10655 PHPStan 1.10.14
  composer.json
Labels: Static Analysis

#10654 Deprecate usage of `@JoinColumn` on the inverse side of one-to-one associations
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Labels: Deprecation
