Repository doctrine/orm, pull requests merged in 2023-02, with the labels that each got.

#10489 Fix forgotten exception throws
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/EntityManager.php
  tests/Doctrine/Tests/ORM/ConfigurationTest.php
  tests/Doctrine/Tests/ORM/Functional/NewOperatorTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryTest.php
  tests/Doctrine/Tests/ORM/Query/ParserTest.php
Labels: Bug

#10490 Fix invalid phpdocs missing null
  lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php
  lib/Doctrine/ORM/Mapping/Table.php
  lib/Doctrine/ORM/Mapping/UniqueConstraint.php
Labels: Static Analysis

#10493 Make all data providers static
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
  tests/Doctrine/Tests/ORM/Decorator/EntityManagerDecoratorTest.php
  tests/Doctrine/Tests/ORM/EntityManagerTest.php
  tests/Doctrine/Tests/ORM/Functional/EnumTest.php
  tests/Doctrine/Tests/ORM/Functional/NewOperatorTest.php
  tests/Doctrine/Tests/ORM/Functional/PaginationTest.php
  tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/DDC2825Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH10387Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH7875Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH8127Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH9230Test.php
  tests/Doctrine/Tests/ORM/Functional/ValueObjectsTest.php
  tests/Doctrine/Tests/ORM/Hydration/ArrayHydratorTest.php
  tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
  tests/Doctrine/Tests/ORM/Id/AssignedGeneratorTest.php
  tests/Doctrine/Tests/ORM/Internal/HydrationCompleteHandlerTest.php
  tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php
  tests/Doctrine/Tests/ORM/Mapping/ReflectionEmbeddedPropertyTest.php
  tests/Doctrine/Tests/ORM/ORMInvalidArgumentExceptionTest.php
  tests/Doctrine/Tests/ORM/Query/ExprTest.php
  tests/Doctrine/Tests/ORM/Query/LanguageRecognitionTest.php
  tests/Doctrine/Tests/ORM/Query/LexerTest.php
  tests/Doctrine/Tests/ORM/Query/ParameterTypeInfererTest.php
  tests/Doctrine/Tests/ORM/Query/ParserTest.php
  tests/Doctrine/Tests/ORM/Query/QueryExpressionVisitorTest.php
  tests/Doctrine/Tests/ORM/Query/QueryTest.php
  tests/Doctrine/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Doctrine/Tests/ORM/Query/SqlWalkerTest.php
  tests/Doctrine/Tests/ORM/Tools/Console/Command/SchemaTool/UpdateCommandTest.php
  tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
  tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php
  tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
Labels: Test Suite

#10496 Migrate database driver to PHP 8 syntax
  lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php
Labels: BC Break

#10420 Fix #9095 by re-applying #9096
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php
Labels: Bug

#10501 Remove calls to `withConsecutive()`
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/PaginatorTest.php
Labels: Test Suite

#10497 Migrate more classes to PHP 8 syntax
  lib/Doctrine/ORM/Event/OnClassMetadataNotFoundEventArgs.php
  lib/Doctrine/ORM/PersistentCollection.php
  lib/Doctrine/ORM/Query/Printer.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  psalm-baseline.xml
Labels: BC Break

#10500 Stop relying on underscores to indicate property visibility
  lib/Doctrine/ORM/AbstractQuery.php
  lib/Doctrine/ORM/Configuration.php
  lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
  lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php
  lib/Doctrine/ORM/NativeQuery.php
  lib/Doctrine/ORM/Query.php
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  lib/Doctrine/ORM/Query/Exec/MultiTableDeleteExecutor.php
  lib/Doctrine/ORM/Query/Exec/MultiTableUpdateExecutor.php
  lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php
  lib/Doctrine/ORM/Query/Exec/SingleTableDeleteUpdateExecutor.php
  phpcs.xml.dist
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/AbstractQueryTest.php
Labels: BC Break

#10503 Migrate ClassMetadata to PHP 8 syntax
  lib/Doctrine/ORM/Mapping/ClassMetadata.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: BC Break

#10133 Clarify difference between transactional() methods of Connection and EntityManager
  docs/en/reference/transactions-and-concurrency.rst
Labels: Documentation

#10507 Baseline Psalm errors for DBAL 3.6
  psalm-baseline.xml
Labels: Static Analysis

#10463 Make missing inheritance declaration a failure
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  tests/Doctrine/Tests/ORM/Mapping/BasicInheritanceMappingTest.php
Labels: BC Break

#10480 Run tests with ext-pgsql
  .github/workflows/continuous-integration.yml
  ci/github/phpunit/pgsql.xml
Labels: CI

#10509 Migrate the rest of the source code to PHP 8 syntax
  lib/Doctrine/ORM/Mapping/DefaultEntityListenerResolver.php
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  lib/Doctrine/ORM/OptimisticLockException.php
  lib/Doctrine/ORM/Query/AST/PathExpression.php
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
  lib/Doctrine/ORM/UnitOfWork.php
  psalm-baseline.xml
Labels: BC Break

#10516 fix: use executeStatement in SchemaTool
  lib/Doctrine/ORM/Tools/SchemaTool.php
Labels: Bug

#8797 Avoid unnecessary information in query hints to improve query cache hit ratio
  lib/Doctrine/ORM/Tools/Pagination/Paginator.php
  lib/Doctrine/ORM/Tools/Pagination/WhereInWalker.php
  tests/Doctrine/Tests/ORM/Functional/PaginationTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/WhereInWalkerTest.php
  tests/Doctrine/Tests/OrmFunctionalTestCase.php
Labels: Bug

#10526 fix typo in faq.rst
  docs/en/reference/faq.rst
Labels: Documentation

#10529 Correct use of PHP attribute
  docs/en/cookbook/working-with-datetime.rst
Labels: Documentation

#10534 [Documentation] consistency order for docblock in association mapping
  docs/en/reference/association-mapping.rst
Labels: Documentation

#10540 Mark SqlWalker methods as not deprecated
  lib/Doctrine/ORM/Query/SqlWalker.php
Labels: Static Analysis

#10541 Bump dev tools
  composer.json
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: Static Analysis, Code Style

#10542 Stabilize DBAL version constraint
  composer.json
Labels: Improvement

#10544 Make data providers static
  tests/Doctrine/Tests/ORM/Tools/Pagination/RootTypeWalkerTest.php
  tests/Doctrine/Tests/ORM/Tools/Pagination/WhereInWalkerTest.php
Labels: Test Suite

#10545 Make data providers static
  tests/Doctrine/Tests/ORM/Mapping/BasicInheritanceMappingTest.php
Labels: Test Suite

#10546 Ignore the cache dir of PHPUnit 10
  .gitignore
Labels: Test Suite
