Repository doctrine/orm, pull requests merged in 2023-11, with the labels that each got.

#11027 Make serialized SQL executors forward compatible
  UPGRADE.md
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  lib/Doctrine/ORM/Query/Exec/MultiTableDeleteExecutor.php
  lib/Doctrine/ORM/Query/Exec/MultiTableUpdateExecutor.php
  lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php
  lib/Doctrine/ORM/Query/Exec/SingleTableDeleteUpdateExecutor.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/ParserResultSerializationTest.php
  tests/Doctrine/Tests/ORM/Functional/ParserResults/single_select_2_17_0.txt
Labels: Deprecation

#11048 Restore backward compatibility with previous format
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Functional/ParserResultSerializationTest.php
Labels: Bug

#11044 Recommend SEQUENCE until doctrine/dbal 4 is released
  UPGRADE.md
  docs/en/reference/basic-mapping.rst
  lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
  psalm-baseline.xml
  tests/Doctrine/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
Labels: Improvement

#11056 Deprecate annotation classes for named queries
  UPGRADE.md
  lib/Doctrine/ORM/Mapping/NamedNativeQueries.php
  lib/Doctrine/ORM/Mapping/NamedNativeQuery.php
  lib/Doctrine/ORM/Mapping/NamedQueries.php
  lib/Doctrine/ORM/Mapping/NamedQuery.php
  psalm.xml
Labels: Deprecation

#10986 Drop support for unserializing old serialization formats
  lib/Doctrine/ORM/Query/ParserResult.php
  tests/Doctrine/Tests/ORM/Functional/ParserResults/single_select_2_14_3.txt
  tests/Doctrine/Tests/ORM/Functional/ParserResults/single_select_2_15_0.txt
Labels: Improvement

#11061 Fix calls to removed lock methods
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Utility/LockSqlHelper.php
  phpstan-dbal3.neon
  psalm.xml
  tests/Doctrine/Tests/ORM/Functional/Locking/LockTest.php
Labels: Bug

#11059 Prepare 2.17.0
  .doctrine-project.json
Labels: Documentation

#11039 Adds metadata field type and enumType validation against Entity property type
  lib/Doctrine/ORM/Tools/SchemaValidator.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/GH11037Test.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/IntEntityStatus.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/InvalidEntityWithTypedEnum.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/StringEntityStatus.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11037/ValidEntityWithTypedEnum.php
Labels: Bug

#11065 AbstractSqlExecutor::__sleep should return property names
  lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php
  tests/Doctrine/Tests/ORM/Functional/ParserResultSerializationTest.php
Labels: Bug

#11085 XmlDriver: remove dead code
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
  phpstan-baseline.neon
Labels: Improvement

#11095 PHPStan 5.16.0, Symfony 7.0
  composer.json
  psalm-baseline.xml
Labels: Static Analysis
