Repository doctrine/orm, pull requests merged in 2024-12, with the labels that each got.

#11753 Run static analysis checks on PHP 8.4
  .gitattributes
  .github/workflows/static-analysis.yml
  phpstan-baseline.neon
  phpstan-params.neon
  tests/Tests/Models/Enums/FaultySwitch.php
Labels: CI

#11756 Upgrade to PHPStan 2
  composer.json
  phpstan-baseline.neon
  phpstan-dbal2.neon
  phpstan-params.neon
  phpstan-persistence2.neon
  src/Cache/DefaultQueryCache.php
  src/Cache/Persister/Entity/AbstractEntityPersister.php
  src/Mapping/ClassMetadataFactory.php
  src/Mapping/DefaultTypedFieldMapper.php
  src/Mapping/Driver/AttributeDriver.php
  src/Tools/Console/Command/ClearCache/QueryCommand.php
  src/Tools/SchemaTool.php
Labels: Static Analysis

#11757 Order result
  tests/Tests/ORM/Functional/QueryDqlFunctionTest.php
Labels: Test Suite

#11752 Provide XSD for phpcs file
  phpcs.xml.dist
Labels: Improvement

#11730 Remove legacy implementation of the DQL -> SQL transformation
  UPGRADE.md
  psalm-baseline.xml
  src/Query.php
  src/Query/Parser.php
  src/Query/SqlWalker.php
  tests/Tests/ORM/Functional/PaginationTest.php
  tests/Tests/ORM/Functional/ParserResultSerializationTest.php
Labels: BC Break

#11760 Run SA checks with PHP 8.4
  .github/workflows/static-analysis.yml
Labels: CI

#11613 Add missing generated option to documentation
  docs/en/reference/basic-mapping.rst
Labels: Documentation

#11770 Fix docs examples for mappings overrides
  docs/en/tutorials/override-field-association-mappings-in-subclasses.rst
Labels: Documentation

#11768 Check hint value before considering instance read-only
  src/UnitOfWork.php
  tests/Tests/ORM/Functional/ReadOnlyTest.php
Labels: Bug

#11776 Respect referencedColumnName defaults in custom naming strategies
  src/Mapping/JoinColumnMapping.php
  src/Mapping/JoinColumnProperties.php
  src/Mapping/ManyToManyOwningSideMapping.php
  src/Mapping/ToOneOwningSideMapping.php
  tests/Tests/ORM/Mapping/MappingDriverTestCase.php
  tests/Tests/ORM/Mapping/NamingStrategy/CustomPascalNamingStrategy.php
  tests/Tests/ORM/Mapping/NamingStrategyTest.php
  tests/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.BlogPost.dcm.xml
  tests/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.BlogPostComment.dcm.xml
Labels: Improvement
