Repository doctrine/orm, pull requests merged in 2024-08, with the labels that each got.

#11550 DQL custom functions: document TypedExpression
  docs/en/cookbook/dql-user-defined-functions.rst
Labels: Documentation

#11576 Re: Re: Add support for using nested DTOs
  docs/en/reference/dql-doctrine-query-language.rst
  psalm-baseline.xml
  src/Internal/Hydration/AbstractHydrator.php
  src/Internal/Hydration/ArrayHydrator.php
  src/Internal/Hydration/ObjectHydrator.php
  src/Query/Parser.php
  src/Query/ResultSetMapping.php
  src/Query/SqlWalker.php
  tests/Tests/Models/CMS/CmsAddressDTO.php
  tests/Tests/Models/CMS/CmsUserDTO.php
  tests/Tests/Models/DDC6573/DDC6573Currency.php
  tests/Tests/Models/DDC6573/DDC6573Item.php
  tests/Tests/Models/DDC6573/DDC6573Money.php
  tests/Tests/ORM/Functional/NewOperatorTest.php
  tests/Tests/ORM/Functional/Ticket/DDC6573Test.php
  tests/Tests/ORM/Hydration/ResultSetMappingTest.php
Labels: New Feature

#11109 Original entity data resolves inverse 1-1 joins
  src/Persisters/Entity/BasicEntityPersister.php
  tests/Tests/Models/OneToOneInverseSideWithAssociativeIdLoad/InverseSide.php
  tests/Tests/Models/OneToOneInverseSideWithAssociativeIdLoad/InverseSideIdTarget.php
  tests/Tests/Models/OneToOneInverseSideWithAssociativeIdLoad/OwningSide.php
  tests/Tests/ORM/Functional/OneToOneInverseSideWithAssociativeIdLoadAfterDqlQueryTest.php
Labels: Bug

#11579 Precise EntityRepository::count return type
  src/EntityRepository.php
  src/Persisters/Entity/BasicEntityPersister.php
  src/Persisters/Entity/EntityPersister.php
Labels: Static Analysis

#11585 PHPStan 1.12
  composer.json
Labels: Static Analysis
