Repository doctrine/orm, pull requests merged in 2024-10, with the labels that each got.

#11618 unclosed `]` in attributes-reference.rst
  docs/en/reference/attributes-reference.rst
Labels: Documentation

#11619 add nested new in EBNF documentation
  docs/en/reference/dql-doctrine-query-language.rst
  src/Query/Parser.php
Labels: Documentation

#11621 EntityGenerator lifecycle callbacks
  src/Tools/EntityGenerator.php
  tests/Tests/ORM/Tools/EntityGeneratorTest.php
Labels: Bug

#11625 Make nullable parameters explicit in generated entities
  src/Tools/EntityGenerator.php
Labels: Bug

#11627 Replace custom directives with native option
  .github/workflows/documentation.yml
  docs/en/sidebar.rst
Labels: Documentation, CI

#11631 Add CI job for PHP 8.4
  .github/workflows/continuous-integration.yml
  tests/Tests/TestInit.php
Labels: CI

#11628 Prepare PHP 8.4 support: Prevent property hooks from being used
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Mapping/ClassMetadataInfo.php
Labels: Improvement

#11636 Add upgrade note about property hooks
  UPGRADE.md
Labels: Documentation

#11635 PHPStan 1.12.6
  composer.json
Labels: Static Analysis

#11639 Let PHPStan detect deprecated usages
  composer.json
  phpstan-dbal2.neon
  phpstan-persistence2.neon
  src/AbstractQuery.php
  src/Cache/Region.php
  src/Cache/Region/DefaultRegion.php
  src/Configuration.php
  src/Decorator/EntityManagerDecorator.php
  src/EntityManager.php
  src/Event/PostLoadEventArgs.php
  src/Event/PostPersistEventArgs.php
  src/Event/PostRemoveEventArgs.php
  src/Event/PostUpdateEventArgs.php
  src/Event/PrePersistEventArgs.php
  src/Event/PreRemoveEventArgs.php
  src/Event/PreUpdateEventArgs.php
  src/Exception/ORMException.php
  src/Id/AbstractIdGenerator.php
  src/Internal/CriteriaOrderings.php
  src/Mapping/Builder/ClassMetadataBuilder.php
  src/Mapping/ClassMetadataFactory.php
  src/Mapping/ClassMetadataInfo.php
  src/Mapping/DefaultQuoteStrategy.php
  src/Mapping/Driver/AttributeDriver.php
  src/Mapping/Driver/SimplifiedYamlDriver.php
  src/Mapping/Driver/XmlDriver.php
  src/Mapping/MappingAttribute.php
  src/Persisters/Entity/JoinedSubclassPersister.php
  src/Proxy/ProxyFactory.php
  src/Query.php
  src/Query/AST/InListExpression.php
  src/Query/AST/InSubselectExpression.php
  src/Query/AST/IndexBy.php
  src/Query/Exec/AbstractSqlExecutor.php
  src/Query/Lexer.php
  src/Query/ParameterTypeInferer.php
  src/Query/Parser.php
  src/Query/TreeWalkerAdapter.php
  src/QueryBuilder.php
  src/Tools/Console/Command/ClearCache/QueryCommand.php
  src/Tools/Console/Command/ClearCache/ResultCommand.php
  src/Tools/Console/ConsoleRunner.php
  src/Tools/Export/Driver/AnnotationExporter.php
  src/Tools/Export/Driver/PhpExporter.php
  src/Tools/Export/Driver/XmlExporter.php
  src/Tools/Export/Driver/YamlExporter.php
  src/Tools/Pagination/LimitSubqueryWalker.php
  src/Tools/SchemaTool.php
Labels: Static Analysis

#11640 Stop recommending vendor-prefixed PHPDoc
  docs/en/reference/metadata-drivers.rst
Labels: Documentation

#11644 Remove a misleading comment
  src/Query/Exec/SingleTableDeleteUpdateExecutor.php
Labels: Documentation

#11641 Deprecate the `\Doctrine\ORM\Query\Parser::setCustomOutputTreeWalker()` method
  UPGRADE.md
  src/Query/Parser.php
  tests/Tests/ORM/Query/LanguageRecognitionTest.php
Labels: Deprecation

#11643 Remove vendor prefix of PHPDoc referencing class-string
  psalm-baseline.xml
  src/Cache/AssociationCacheEntry.php
  src/Cache/CollectionCacheKey.php
  src/Cache/EntityCacheEntry.php
  src/Cache/EntityCacheKey.php
  src/Cache/Persister/Collection/AbstractCollectionPersister.php
  src/Configuration.php
  src/Decorator/EntityManagerDecorator.php
  src/EntityManager.php
  src/EntityManagerInterface.php
  src/EntityRepository.php
  src/Internal/Hydration/ObjectHydrator.php
  src/Mapping/Builder/ClassMetadataBuilder.php
  src/Mapping/ClassMetadataFactory.php
  src/Mapping/ClassMetadataInfo.php
  src/Mapping/DefaultEntityListenerResolver.php
  src/Mapping/Driver/AnnotationDriver.php
  src/Mapping/Driver/AttributeDriver.php
  src/Mapping/Driver/DatabaseDriver.php
  src/Mapping/Driver/XmlDriver.php
  src/Mapping/Driver/YamlDriver.php
  src/Mapping/Entity.php
  src/Mapping/MappedSuperclass.php
  src/Mapping/Reflection/ReflectionPropertiesGetter.php
  src/Query/Parser.php
  src/Query/ResultSetMapping.php
  src/Query/ResultSetMappingBuilder.php
  src/Query/TreeWalkerChain.php
  src/Query/TreeWalkerChainIterator.php
  src/Tools/Console/Command/MappingDescribeCommand.php
  src/Tools/ConvertDoctrine1Schema.php
  src/Tools/EntityRepositoryGenerator.php
  src/Tools/Pagination/Paginator.php
  src/UnitOfWork.php
  tests/StaticAnalysis/Mapping/class-metadata-constructor.php
  tests/StaticAnalysis/get-metadata.php
  tests/Tests/ORM/Functional/DatabaseDriverTestCase.php
  tests/Tests/ORM/Functional/PostLoadEventTest.php
  tests/Tests/ORM/Functional/Ticket/DDC1884Test.php
  tests/Tests/ORM/Mapping/AnnotationDriverTest.php
  tests/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Tests/ORM/Mapping/MappingDriverTestCase.php
  tests/Tests/ORM/Repository/DefaultRepositoryFactoryTest.php
  tests/Tests/PHPUnitCompatibility/MockBuilderCompatibilityTools.php
  tests/Tests/TestUtil.php
Labels: Static Analysis

#11646 Run risky code in finally block
  src/EntityManager.php
  src/UnitOfWork.php
  tests/Tests/ORM/EntityManagerTest.php
  tests/Tests/ORM/UnitOfWorkTest.php
Labels: Bug

#11657 Support for DBAL 4.2 EnumType in SchemaTool
  src/Tools/SchemaTool.php
Labels: Improvement

#11663 Update branch metadata
  .doctrine-project.json
Labels: CI

#11575 Allow named Arguments to be passed to Dto
  docs/en/reference/dql-doctrine-query-language.rst
  src/Exception/DuplicateFieldException.php
  src/Exception/NoMatchingPropertyException.php
  src/Internal/Hydration/AbstractHydrator.php
  src/Query/Parser.php
  src/Query/ResultSetMapping.php
  src/Query/SqlWalker.php
  src/Query/TokenType.php
  tests/Tests/Models/CMS/CmsAddressDTONamedArgs.php
  tests/Tests/Models/CMS/CmsUserDTONamedArgs.php
  tests/Tests/Models/CMS/CmsUserDTOVariadicArg.php
  tests/Tests/ORM/Functional/NewOperatorTest.php
  tests/Tests/ORM/Hydration/ResultSetMappingTest.php
Labels: New Feature

#11666 Auto-detect values for EnumType columns
  psalm-baseline.xml
  src/Mapping/ClassMetadata.php
  src/Mapping/DefaultTypedFieldMapper.php
  tests/Tests/Models/Enums/CardNativeEnum.php
  tests/Tests/Models/Enums/TypedCardNativeEnum.php
  tests/Tests/ORM/Functional/EnumTest.php
Labels: New Feature

#11670 Drop support for DBAL 4.1
  composer.json
  src/Mapping/ClassMetadata.php
  src/Mapping/DefaultTypedFieldMapper.php
  tests/Tests/ORM/Functional/EnumTest.php
Labels: Improvement

#11672 Update branch metadata
  .doctrine-project.json
Labels: Documentation

#11674 Drop DBAL 2 compat code
  tests/Tests/ORM/Functional/Ticket/GH10747Test.php
Labels: Test Suite

#11675 Remove more DBAL 3 compat code
  tests/Tests/ORM/Functional/SQLFilterTest.php
  tests/Tests/ORM/Functional/Ticket/GH7869Test.php
  tests/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Tests/ORM/PersistentCollectionTest.php
  tests/Tests/ORM/Proxy/ProxyFactoryTest.php
  tests/Tests/OrmFunctionalTestCase.php
  tests/Tests/OrmTestCase.php
Labels: Test Suite

#11673 Update README
  README.md
Labels: Documentation

#11677 Psalm 5.26.1
  composer.json
  psalm-baseline.xml
Labels: Static Analysis

#11678 Close stale pull requests
  .github/workflows/stale.yml
Labels: CI

#11667 Experiment with literalinclude
  docs/en/tutorials/working-with-indexed-associations.rst
  docs/en/tutorials/working-with-indexed-associations/Market-annotations.php
  docs/en/tutorials/working-with-indexed-associations/Market.php
  docs/en/tutorials/working-with-indexed-associations/market.xml
  docs/en/tutorials/working-with-indexed-associations/market.yaml
Labels: Documentation

#11681 Tell dependabot to target 2.20.x
  .github/dependabot.yml
Labels: CI

#11453 Allow classname in 'value' attribute of xml discriminator-mapping field
  doctrine-mapping.xsd
  tests/Tests/Models/Customer/CustomerType.php
  tests/Tests/Models/Customer/ExternalCustomer.php
  tests/Tests/Models/Customer/InternalCustomer.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Customer.CustomerType.dcm.xml
Labels: Bug, Stale

#11035 Make `PersistentCollection::first()` "extra" lazy
  docs/en/tutorials/extra-lazy-associations.rst
  src/PersistentCollection.php
  tests/Tests/ORM/Functional/ExtraLazyCollectionTest.php
Labels: New Feature

#11693 UPGRADE: mention `SqlWalker` deprecations in 3.3
  UPGRADE.md
Labels: Documentation

#11694 BUG: When changing SQLFilter parameter, resulting SQL query is not generated correctly
  src/Persisters/Entity/BasicEntityPersister.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/ChangeFiltersTest.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/CompanySQLFilter.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Order.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/User.php
Labels: Bug

#11344 Change the lock mode in the "Aggregate Fields" cookbook (aggregate-fields.rst) article.
  docs/en/cookbook/aggregate-fields.rst
Labels: Documentation

#11697 Run tests against PostgreSQL 17
  .github/workflows/continuous-integration.yml
Labels: CI
