Repository doctrine/orm, pull requests merged in 2024-02, with the labels that each got.

#11205 Run Rector on the source code
  src/Exception/EntityIdentityCollisionException.php
  src/Internal/Hydration/ObjectHydrator.php
  src/Internal/TopologicalSort/CycleDetectedException.php
  src/Mapping/AssociationMapping.php
  src/Mapping/ClassMetadata.php
  src/ORMSetup.php
  src/PersistentCollection.php
  src/Persisters/Entity/SingleTablePersister.php
  src/Proxy/Autoloader.php
  src/Proxy/DefaultProxyClassNameResolver.php
  src/Proxy/ProxyFactory.php
  src/Tools/Debug.php
  src/Tools/Pagination/Paginator.php
  src/Tools/SchemaValidator.php
  src/UnitOfWork.php
Labels: Improvement

#11207 Update branches in README
  README.md
Labels: Documentation

#11210 Switch back to stable dependencies
  composer.json
Labels: CI

#11211 Deprecate array access
  UPGRADE.md
  src/Mapping/ArrayAccessImplementation.php
  src/Persisters/Entity/JoinedSubclassPersister.php
  src/Query/ResultSetMappingBuilder.php
  src/Tools/SchemaValidator.php
  src/UnitOfWork.php
  tests/Tests/ORM/Functional/Ticket/GH11135Test.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Tests/ORM/Mapping/XmlMappingDriverTest.php
Labels: Deprecation

#11215 Remove array access
  UPGRADE.md
  src/Mapping/ArrayAccessImplementation.php
  src/Mapping/AssociationMapping.php
  src/Mapping/DiscriminatorColumnMapping.php
  src/Mapping/EmbeddedClassMapping.php
  src/Mapping/FieldMapping.php
  src/Mapping/JoinColumnMapping.php
  src/Mapping/JoinTableMapping.php
  tests/Tests/ORM/Mapping/AssociationMappingTest.php
Labels: BC Break

#11218 DoctrineSetup was renamed to ORMSetup
  UPGRADE.md
Labels: Documentation

#11219 Bump dependencies in the "getting started" docs page
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#11220 Point link to correct upgrade guide
  docs/en/index.rst
Labels: Documentation

#11222 Update README.md
  README.md
Labels: Documentation

#11221 Update version ORM from 2 to 3 in docs
  docs/en/index.rst
Labels: Documentation

#11228 Add TokenType class
  UPGRADE.md
  docs/en/cookbook/dql-user-defined-functions.rst
  docs/en/reference/dql-doctrine-query-language.rst
  psalm-baseline.xml
  src/Query/AST/Functions/AbsFunction.php
  src/Query/AST/Functions/BitAndFunction.php
  src/Query/AST/Functions/BitOrFunction.php
  src/Query/AST/Functions/ConcatFunction.php
  src/Query/AST/Functions/CurrentDateFunction.php
  src/Query/AST/Functions/CurrentTimeFunction.php
  src/Query/AST/Functions/CurrentTimestampFunction.php
  src/Query/AST/Functions/DateAddFunction.php
  src/Query/AST/Functions/DateDiffFunction.php
  src/Query/AST/Functions/IdentityFunction.php
  src/Query/AST/Functions/LengthFunction.php
  src/Query/AST/Functions/LocateFunction.php
  src/Query/AST/Functions/LowerFunction.php
  src/Query/AST/Functions/ModFunction.php
  src/Query/AST/Functions/SizeFunction.php
  src/Query/AST/Functions/SqrtFunction.php
  src/Query/AST/Functions/SubstringFunction.php
  src/Query/AST/Functions/TrimFunction.php
  src/Query/AST/Functions/UpperFunction.php
  src/Query/Lexer.php
  src/Query/Parser.php
  src/Query/TokenType.php
  tests/Tests/ORM/Functional/CustomFunctionsTest.php
  tests/Tests/ORM/Functional/Ticket/GH7286Test.php
  tests/Tests/ORM/Query/LexerTest.php
  tests/Tests/ORM/Query/ParserTest.php
  tests/Tests/ORM/Query/SelectSqlGenerationTest.php
  tests/Tests/ORM/Query/TreeWalkerAdapterTest.php
Labels: Improvement, Deprecation

#11234 Remove references to deprecated constants from Lexer
  src/Query/Lexer.php
Labels: Improvement

#11242 fix: support array-type arg in QB variadic calls
  src/Query/Expr/Base.php
  tests/Tests/ORM/QueryBuilderTest.php
Labels: Bug

#11252 Make docs valid according to guides 0.3.3
  .github/workflows/documentation.yml
  docs/en/reference/basic-mapping.rst
  docs/en/reference/events.rst
  docs/en/reference/faq.rst
  docs/en/reference/inheritance-mapping.rst
  docs/en/sidebar.rst
Labels: Documentation

#11260 Throw if a variadic parameter contains unexpected named arguments
  psalm-baseline.xml
  src/Internal/NoUnknownNamedArguments.php
  src/QueryBuilder.php
  tests/Tests/ORM/QueryBuilderTest.php
Labels: Improvement

#11261 Validate more variadic parameters
  src/Mapping/ChainTypedFieldMapper.php
  src/Query/Expr.php
Labels: Improvement

#11257 [Documentation] Adding link to Postgres upgrade article
  UPGRADE.md
Labels: Documentation

#11266 More valid docs
  docs/en/cookbook/implementing-arrayaccess-for-domain-objects.rst
  docs/en/cookbook/implementing-the-notify-changetracking-policy.rst
  docs/en/reference/installation.rst
  docs/en/sidebar.rst
Labels: Documentation

#11269 docs: recommend safer way to disable logging
  docs/en/reference/batch-processing.rst
Labels: Documentation

#11270 Treat '0' as a legitimate trim char
  psalm-baseline.xml
  src/Query/AST/Functions/TrimFunction.php
  tests/Tests/ORM/Query/LanguageRecognitionTest.php
Labels: Bug

#11275 Account for inversedBy being a non-falsy-string or null
  src/Internal/Hydration/ObjectHydrator.php
  src/Mapping/Builder/ClassMetadataBuilder.php
  src/Persisters/Entity/BasicEntityPersister.php
  src/Tools/SchemaValidator.php
  src/UnitOfWork.php
Labels: Static Analysis

#11272 Improve static analysis on AttachEntityListenersListener
  src/Tools/AttachEntityListenersListener.php
Labels: Static Analysis

#11281 Fix StaticAnalysis folder reference
  .github/workflows/static-analysis.yml
Labels: CI

#11276 Remove implicit casts in FileLock.php
  src/Cache/Region/FileLockRegion.php
Labels: Static Analysis

#11226 Be less restrictive in DiscriminatorColumnMapping phpdoc
  src/Mapping/ClassMetadata.php
  src/Mapping/DiscriminatorColumnMapping.php
Labels: Static Analysis

#11287 Allow (Array)ParameterType in QueryBuilder
  src/QueryBuilder.php
  tests/Tests/ORM/Functional/QueryParameterTest.php
Labels: Bug, BC Break

#11293 Remove wrong annotation about return type
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Mapping/ClassMetadataInfo.php
Labels: Bug, Static Analysis

#11294 Translate comment into code and annotations
  UPGRADE.md
  psalm-baseline.xml
  src/Mapping/ClassMetadata.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
Labels: Deprecation

#11305 Remove extra word
  src/Mapping/ClassMetadataFactory.php
Labels: Improvement

#11298 Fix sqlWalker::walkSimpleArithmeticExpression phpdoc
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Query/SqlWalker.php
Labels: Static Analysis

#11309 Deprecate invalid method call
  UPGRADE.md
  src/Mapping/ClassMetadataInfo.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
Labels: Deprecation

#11308 Throw a full-fledged exception on invalid call
  UPGRADE.md
  src/Mapping/ClassMetadata.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
Labels: Bug

#11315 Address deprecations from Collection 2.2
  phpcs.xml.dist
  phpstan-persistence2.neon
  src/Cache/Persister/Entity/AbstractEntityPersister.php
  src/Internal/CriteriaOrderings.php
  src/Mapping/Driver/XmlDriver.php
  src/PersistentCollection.php
  src/Persisters/Collection/ManyToManyPersister.php
  src/Persisters/Entity/BasicEntityPersister.php
  src/QueryBuilder.php
  tests/Tests/ORM/Functional/ManyToManyBasicAssociationTest.php
  tests/Tests/ORM/Functional/Ticket/GH7767Test.php
  tests/Tests/ORM/Functional/Ticket/GH7836Test.php
  tests/Tests/ORM/QueryBuilderTest.php
Labels: Bug

#11306 Disallow passing null to ClassMetadata::fullyQualifiedClassName()
  UPGRADE.md
  psalm-baseline.xml
  src/Mapping/ClassMetadata.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
Labels: BC Break

#11320 PHPStan 1.10.59
  composer.json
  phpstan-baseline.neon
  src/Mapping/DefaultTypedFieldMapper.php
Labels: Static Analysis
