Repository doctrine/orm, pull requests merged in 2024-03, with the labels that each got.

#11324 Remove PHP 7 workarounds
  phpcs.xml.dist
  src/Internal/CriteriaOrderings.php
  src/Mapping/Driver/XmlDriver.php
Labels: Code Style

#11325 Bump Doctrine Collections to 2.2
  composer.json
  src/Cache/Persister/Entity/AbstractEntityPersister.php
  src/Internal/CriteriaOrderings.php
  src/PersistentCollection.php
  src/Persisters/Collection/ManyToManyPersister.php
  src/Persisters/Entity/BasicEntityPersister.php
  src/QueryBuilder.php
Labels: Improvement

#11326 Psalm 5.22.2
  composer.json
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#11332 Refator array_map into simple loop for performance.
  src/UnitOfWork.php
Labels: Improvement

#11330 Use class from persistence package
  UPGRADE.md
  composer.json
  src/Mapping/ClassMetadata.php
  src/Mapping/ReflectionEmbeddedProperty.php
  src/Mapping/ReflectionEnumProperty.php
Labels: Deprecation

#11314 Fix SchemaTool::getSchemaFromMetadata() uniqueConstraint without a predefined name
  src/Tools/SchemaTool.php
  tests/Tests/ORM/Tools/SchemaToolTest.php
Labels: Bug

#11336 Bump CI workflows
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#11335 Prepare releases 2.19 and 3.1
  .doctrine-project.json
  README.md
Labels: Documentation

#11334 Remove ReflectionEnumProperty
  UPGRADE.md
  psalm-baseline.xml
  src/Mapping/ReflectionEnumProperty.php
Labels: BC Break

#11347 Remove guides-specific markup
  .github/workflows/documentation.yml
  docs/en/reference/installation.rst
  docs/en/sidebar.rst
Labels: Documentation, CI

#11354 Deprecate --complete option of orm:schema-tool:update
  UPGRADE.md
  src/Tools/Console/Command/SchemaTool/UpdateCommand.php
Labels: Deprecation

#11090 [2.17.x] Failed getting entity with fetch eager property
  src/UnitOfWork.php
  tests/Tests/Models/AbstractFetchEager/AbstractRemoteControl.php
  tests/Tests/Models/AbstractFetchEager/MobileRemoteControl.php
  tests/Tests/Models/AbstractFetchEager/User.php
  tests/Tests/ORM/Functional/AbstractFetchEagerTest.php
Labels: Bug

#11363 Merge 2.19.x up into 3.1.x
  .github/workflows/documentation.yml
  docs/en/reference/installation.rst
  docs/en/sidebar.rst
  src/UnitOfWork.php
  tests/Tests/Models/AbstractFetchEager/AbstractRemoteControl.php
  tests/Tests/Models/AbstractFetchEager/MobileRemoteControl.php
  tests/Tests/Models/AbstractFetchEager/User.php
  tests/Tests/ORM/Functional/AbstractFetchEagerTest.php
Labels: Bug

#11357 Deprecate obsolete and unnecessary properties from Table attribute (#11351)
  UPGRADE.md
  src/Mapping/Table.php
  tests/Tests/ORM/Mapping/TableMappingTest.php
Labels: Deprecation

#11356 Remove --complete option of orm:schema-tool:update
  UPGRADE.md
  src/Tools/Console/Command/SchemaTool/UpdateCommand.php
Labels: BC Break

#11353 Remove obsolete and unnecessary properties from `Table` attribute (#11351)
  UPGRADE.md
  src/Mapping/Table.php
  tests/Tests/ORM/Mapping/TableMappingTest.php
Labels: BC Break

#11289 Do not use batch loading for collections with composite identifier
  src/UnitOfWork.php
  tests/Tests/Models/EagerFetchedCompositeOneToMany/RootEntity.php
  tests/Tests/Models/EagerFetchedCompositeOneToMany/SecondLevel.php
  tests/Tests/ORM/Functional/EagerFetchOneToManyWithCompositeKeyTest.php
Labels: Failing Test, Bug

#11380 [GH-11185] Bugfix: do not use collection batch loading for indexBy association
  src/UnitOfWork.php
  tests/Tests/ORM/Functional/Ticket/GH11149/EagerProduct.php
  tests/Tests/ORM/Functional/Ticket/GH11149/EagerProductTranslation.php
  tests/Tests/ORM/Functional/Ticket/GH11149/GH11149Test.php
  tests/Tests/ORM/Functional/Ticket/GH11149/Locale.php
Labels: Bug

#11384 [Documentation] Removing "Doctrine Mapping Types" ...
  docs/en/reference/basic-mapping.rst
Labels: Documentation

#11387 Fixed proxy initialization for EnumReflectionProperty
  src/Proxy/ProxyFactory.php
  tests/Tests/ORM/Functional/Ticket/GH11386/GH11386EntityCart.php
  tests/Tests/ORM/Functional/Ticket/GH11386/GH11386EntityCustomer.php
  tests/Tests/ORM/Functional/Ticket/GH11386/GH11386EnumType.php
  tests/Tests/ORM/Functional/Ticket/GH11386/GH11386Test.php
Labels: Bug

#11391 Remove unused variable
  tests/Tests/ORM/Proxy/ProxyFactoryTest.php
Labels: Test Suite

#11393 Set column length explicitly
  tests/Tests/ORM/Functional/Ticket/GH11149/Locale.php
Labels: Test Suite

#11372 [Documentation] Query Result Formats
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation

#11389 Fix psalm errors: remove override of template type
  psalm-baseline.xml
  src/LazyCriteriaCollection.php
  src/PersistentCollection.php
Labels: Static Analysis

#11403 [Documentation] Merging "Query Result Formats" with "Hydration Modes"
  docs/en/reference/dql-doctrine-query-language.rst
Labels: Documentation

#11399 SchemaValidator: Changing mapping of BIGINT to string|int
  src/Tools/SchemaValidator.php
  tests/Tests/ORM/Tools/SchemaValidatorTest.php
Labels: Bug
