Repository doctrine/orm, pull requests merged in 2024-01, with the labels that each got.

#11142 Remove inheritance
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH11072/GH11072EntityAdvanced.php
Labels: Test Suite

#11146 Mention that ``postRemove`` may still see removed entities in in-memory collections
  docs/en/reference/events.rst
Labels: Documentation

#11082 Do not defer eager collection loading when in iteration context
  lib/Doctrine/ORM/UnitOfWork.php
  tests/Doctrine/Tests/ORM/Functional/EagerFetchCollectionTest.php
Labels: Bug

#11162 Remove redundant tags
  doctrine-mapping.xsd
Labels: Bug

#11171 Make Doctrine\Tests\ORM\Internal\Node autoloadable
  tests/Doctrine/Tests/ORM/Internal/Node.php
  tests/Doctrine/Tests/ORM/Internal/TopologicalSortTest.php
Labels: Test Suite

#11178 Remove references to JIRA
  SECURITY.md
  docs/en/reference/security.rst
  lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
Labels: Documentation

#11179 Modernize code in documentation
  docs/en/cookbook/aggregate-fields.rst
  docs/en/cookbook/resolve-target-entity-listener.rst
Labels: Documentation

#11181 Look for lib remnants in hidden files
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/phpbench.yml
  .github/workflows/static-analysis.yml
  .gitignore
Labels: CI

#11180 Allow doctrine/lexer 3
  composer.json
  src/Query/Lexer.php
Labels: Improvement

#11176 Throw exception when trying to use non-backed enum types
  lib/Doctrine/ORM/Mapping/DefaultTypedFieldMapper.php
  lib/Doctrine/ORM/Mapping/MappingException.php
  tests/Doctrine/Tests/Models/Enums/FaultySwitch.php
  tests/Doctrine/Tests/Models/Enums/SwitchStatus.php
  tests/Doctrine/Tests/ORM/Mapping/TypedEnumFieldMapperTest.php
Labels: Improvement

#11186 Update branches in README
  README.md
Labels: Documentation

#11165 Allow XML validation to be disabled but keep it enabled by default.
  UPGRADE.md
  src/Mapping/Driver/SimplifiedXmlDriver.php
  src/Mapping/Driver/XmlDriver.php
  src/ORMSetup.php
  tests/Tests/Models/InvalidXml.php
  tests/Tests/ORM/Mapping/XmlMappingDriverTest.php
  tests/Tests/ORM/Mapping/invalid_xml/Doctrine.Tests.Models.InvalidXml.dcm.xml
  tests/Tests/ORM/ORMSetupTest.php
Labels: Deprecation

#11187 Remove XML validation disabling deprecation.
  lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
Labels: Deprecation

#11191 Ignore deprecations handled in next major
  psalm.xml
Labels: Test Suite

#11195 Use a more specific type for getSqlStatements()
  psalm-baseline.xml
  src/Query/Exec/AbstractSqlExecutor.php
  src/Query/Exec/MultiTableUpdateExecutor.php
Labels: Improvement

#11197 Cover limit/offset values in `LimitSubqueryOutputWalkerTest`
  tests/Doctrine/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
Labels: Test Suite

#11198 Fix calls to removed lock methods (#11061)
  lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
  lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php
  lib/Doctrine/ORM/Query/SqlWalker.php
  lib/Doctrine/ORM/Utility/LockSqlHelper.php
  phpstan-dbal2.neon
  phpstan-persistence2.neon
  phpstan.neon
  psalm.xml
  tests/Doctrine/Tests/ORM/Functional/Locking/LockTest.php
Labels: Improvement
