Repository doctrine/orm, pull requests merged in 2024-05, with the labels that each got.

#11439 Setup Dependabot
  .github/dependabot.yml
Labels: CI

#11425 Discriminator value could be an integer
  src/Query/SqlWalker.php
  tests/Tests/ORM/Functional/Ticket/GH11341Test.php
Labels: Bug

#11456 Using an integer as discriminator value with ORM v3
  src/Query/SqlWalker.php
  tests/Tests/ORM/Functional/Ticket/GH11341Test.php
Labels: Bug

#11462 Fix return type of `Query::getLockMode()` for DBAL 4
  src/Query.php
  tests/Tests/ORM/Query/QueryTest.php
Labels: Bug

#11465 Test with actual lock modes
  tests/Tests/ORM/Cache/Persister/Entity/EntityPersisterTestCase.php
Labels: Test Suite

#11464 Fix failed merge
  src/UnitOfWork.php
Labels: Bug

#11466 PHPStan 1.11.1
  composer.json
Labels: Static Analysis

#11468 Deprecate SequenceGenerator implementing Serializable
  UPGRADE.md
  src/Id/SequenceGenerator.php
Labels: Deprecation

#11469 Remove Serializable implementation
  UPGRADE.md
  psalm-baseline.xml
  src/Id/SequenceGenerator.php
Labels: BC Break

#11470 Deprecate the NotSupported exception
  UPGRADE.md
  src/Exception/NotSupported.php
Labels: Deprecation

#11471 Remove `NotSupported`
  UPGRADE.md
  src/Exception/NotSupported.php
Labels: BC Break

#11472 Remove readonly modifier from EntityManager
  src/EntityManager.php
  tests/Tests/ORM/EntityManagerTest.php
Labels: Improvement

#11460 docs: update EntityManager#transactional to EntityManager#wrapInTransaction
  docs/en/reference/transactions-and-concurrency.rst
Labels: Documentation

#11445 Consider usage of setFetchMode when checking for simultaneous usage of fetch-mode EAGER and WITH condition
  src/Query/SqlWalker.php
  tests/Tests/ORM/Functional/EagerFetchCollectionTest.php
Labels: Bug
