Repository doctrine/orm, pull requests merged in 2024-06, with the labels that each got.

#11475 Fix cloning entities
  psalm-baseline.xml
  src/Proxy/ProxyFactory.php
  tests/Tests/Models/ECommerce/ECommerceProduct2.php
  tests/Tests/ORM/Functional/ProxiesLikeEntitiesTest.php
  tests/Tests/ORM/Functional/ReferenceProxyTest.php
Labels: Bug

#11489 Replace assertion with exception
  src/Query/Parser.php
  tests/Tests/ORM/Functional/Ticket/GH11487Test.php
Labels: Bug

#11493 fix(docs): use string value in `addAttribute`
  docs/en/tutorials/composite-primary-keys.rst
Labels: Documentation

#11490 ci: maintained and stable mariadb version (lts)
  .github/workflows/continuous-integration.yml
Labels: CI

#11194 Skip joined entity creation for empty relation (#10889)
  src/Internal/Hydration/ObjectHydrator.php
  tests/Tests/ORM/Functional/Ticket/GH10889Test.php
Labels: Bug

#11501 Fix OneToManyPersister::deleteEntityCollection missing discriminator column/value. (GH-11500)
  src/Persisters/Collection/OneToManyPersister.php
  tests/Tests/ORM/Functional/Ticket/GH11500Test.php
Labels: Bug

#11504 Fix upgrade guide for 2.20
  UPGRADE.md
Labels: Documentation

#11509 Remove unneeded CS rule
  phpcs.xml.dist
  src/Mapping/InverseJoinColumn.php
Labels: Improvement

#11511 Add the proper void return type on the __load method of proxies
  src/Proxy/ProxyFactory.php
Labels: Bug

#11510 Add missing type declaration
  psalm-baseline.xml
  src/Mapping/Driver/XmlDriver.php
Labels: BC Break

#11512 Deprecate DatabaseDriver
  UPGRADE.md
  src/Mapping/Driver/DatabaseDriver.php
Labels: Deprecation

#11506 [2.19.x] Fetching entities with Composite Key Relations and null values
  src/UnitOfWork.php
  tests/Tests/Models/CompositeKeyRelations/CustomerClass.php
  tests/Tests/Models/CompositeKeyRelations/InvoiceClass.php
  tests/Tests/ORM/Functional/CompositeKeyRelationsTest.php
  tests/Tests/OrmFunctionalTestCase.php
Labels: Bug

#11517 Fix deprecated array access usage
  src/Persisters/Collection/OneToManyPersister.php
Labels: Improvement

#11519 Remove DatabaseDriver
  UPGRADE.md
  psalm-baseline.xml
  psalm.xml
  src/Mapping/Driver/DatabaseDriver.php
  tests/Tests/ORM/Functional/DatabaseDriverTest.php
  tests/Tests/ORM/Functional/DatabaseDriverTestCase.php
  tests/Tests/ORM/Functional/Ticket/DDC2387Test.php
  tests/Tests/ORM/Functional/Ticket/GH7684Test.php
Labels: BC Break

#11526 doc: Use modern array syntax in getting started
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#11534 working-with-objects.rst: added missing white space
  docs/en/reference/working-with-objects.rst
Labels: Documentation
