Repository doctrine/orm, pull requests merged in 2024-11, with the labels that each got.

#11716 Add `isEmpty()` method to the Extra Lazy Associations tutorial
  docs/en/tutorials/extra-lazy-associations.rst
Labels: Documentation

#9760 [GH-3519] Deprecate passing the same class with different discriminator values.
  UPGRADE.md
  src/Mapping/ClassMetadata.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
Labels: Deprecation

#11719 Ignore deprecation about StaticReflectionService
  psalm.xml
Labels: Static Analysis

#11709 Fix `Events::onFlush` and `PostFlush()` documentation: events are always raised
  src/Events.php
Labels: Documentation

#11556 [Docs] unitofwork.rst: php => PHP
  docs/en/reference/unitofwork.rst
Labels: Documentation, Stale

#11729 Drop support for Persistence 3
  composer.json
  phpcs.xml.dist
  psalm-baseline.xml
  psalm.xml
  src/Mapping/ClassMetadata.php
  src/Mapping/ClassMetadataFactory.php
  src/Mapping/Driver/LoadMappingFileImplementation.php
  src/Mapping/Driver/XmlDriver.php
  src/Mapping/GetReflectionClassImplementation.php
  src/Tools/SchemaValidator.php
  tests/Tests/ORM/Functional/Ticket/DDC2359Test.php
  tests/Tests/ORM/Functional/Ticket/DDC3103Test.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Tests/ORM/Mapping/FieldBuilderTest.php
  tests/Tests/ORM/Mapping/XmlMappingDriverTest.php
Labels: Improvement

#11732 Raise PHPStan level to 7
  phpstan-baseline.neon
  phpstan-dbal2.neon
  phpstan-params.neon
  phpstan-persistence2.neon
Labels: Static Analysis
