Repository doctrine/orm, pull requests merged in 2024-04, with the labels that each got.

#11407 Fix templated phpdoc return type
  phpstan-baseline.neon
  psalm-baseline.xml
  src/EntityManagerInterface.php
Labels: Static Analysis

#11413 docs: update PHP version in doc
  docs/en/reference/architecture.rst
  docs/en/tutorials/getting-started.rst
Labels: Documentation

#11420 fix(docs): typo
  docs/en/cookbook/validation-of-entities.rst
Labels: Documentation

#11422 Bugfix: respect orderBy for fetch EAGER mode
  src/UnitOfWork.php
  tests/Tests/ORM/Functional/Ticket/GH11163Test.php
Labels: Bug

#11101 fix: always cleanup in `AbstractHydrator::toIterable()`
  src/Internal/Hydration/AbstractHydrator.php
  tests/Tests/ORM/Hydration/AbstractHydratorTest.php
Labels: Bug

#11426 Update association-mapping.rst
  docs/en/reference/association-mapping.rst
Labels: Documentation

#11428 Prevent creation of new MANAGED entity instance by reloading REMOVED entity from database
  src/UnitOfWork.php
  tests/Tests/ORM/Functional/Ticket/GH6123Test.php
  tests/Tests/ORM/UnitOfWorkTest.php
Labels: Bug

#11430 Fix deprecation layer of Doctrine\ORM\ORMException
  src/ORMException.php
  tests/Tests/ORM/Functional/Ticket/GH6123Test.php
Labels: Bug
