Repository doctrine/orm, pull requests merged in 2025-03, with the labels that each got.

#11825 FIX - nested dto's doesn't have arguments in good order and Dto with only objects bug
  src/Internal/Hydration/AbstractHydrator.php
  src/Query/AST/NewObjectExpression.php
  src/Query/Parser.php
  src/Query/ResultSetMapping.php
  src/Query/SqlWalker.php
  tests/Tests/Models/CMS/CmsAddressDTO.php
  tests/Tests/Models/CMS/CmsDumbDTO.php
  tests/Tests/ORM/Functional/NewOperatorTest.php
Labels: Bug

#11873 Bugfix: Missed a spot using getUnderlyingReflector
  src/Tools/SchemaValidator.php
Labels: Bug

#11877 Iso phpunit config
  .github/workflows/continuous-integration.yml
  ci/github/phpunit/mysqli.xml
  ci/github/phpunit/pdo_mysql.xml
  ci/github/phpunit/pdo_pgsql.xml
  ci/github/phpunit/pdo_sqlite.xml
  ci/github/phpunit/pgsql.xml
  ci/github/phpunit/sqlite3.xml
  phpunit.xml.dist
Labels: CI

#11881 Upgrade to doctrine/coding-standard 13
  composer.json
  src/Mapping/ClassMetadataInfo.php
  tests/Tests/Mocks/ConnectionMock.php
  tests/Tests/ORM/Mapping/Reflection/ReflectionPropertiesGetterTest.php
  tests/Tests/OrmFunctionalTestCase.php
Labels: Code Style

#11885 Avoid triple stars
  docs/en/reference/advanced-configuration.rst
Labels: Documentation

#11894 Fix URL's in xml-mapping.rst
  docs/en/reference/events.rst
  docs/en/reference/second-level-cache.rst
  docs/en/reference/xml-mapping.rst
  docs/en/tutorials/composite-primary-keys.rst
  docs/en/tutorials/extra-lazy-associations.rst
  docs/en/tutorials/getting-started.rst
  docs/en/tutorials/working-with-indexed-associations.rst
  docs/en/tutorials/working-with-indexed-associations/market.xml
Labels: Documentation

#11891 Add more detailed caveats for using the Collection filtering API
  docs/en/reference/working-with-associations.rst
Labels: Documentation
