Repository doctrine/orm, pull requests merged in 2025-02, with the labels that each got.

#11707 [DDC-551] fix, add filter support in oneToOne relation 2.20.x
  src/Persisters/Entity/BasicEntityPersister.php
  tests/Tests/ORM/Functional/SQLFilterTest.php
Labels: Bug

#11826 Clone query hints and parameters in `LimitSubqueryOutputWalker` constructor
  src/Tools/Pagination/LimitSubqueryOutputWalker.php
  tests/Tests/ORM/Functional/EagerFetchCollectionTest.php
  tests/Tests/ORM/Tools/Pagination/LimitSubqueryOutputWalkerTest.php
Labels: Bug

#11833 Fix DQL example with composite key
  docs/en/tutorials/composite-primary-keys.rst
Labels: Documentation

#11659 Necessary refactorings for Property hooks
  UPGRADE.md
  phpstan-baseline.neon
  src/Internal/Hydration/ObjectHydrator.php
  src/Mapping/ClassMetadata.php
  src/Mapping/ClassMetadataFactory.php
  src/Mapping/FieldMapping.php
  src/Mapping/LegacyReflectionFields.php
  src/Mapping/PropertyAccessors/EmbeddablePropertyAccessor.php
  src/Mapping/PropertyAccessors/EnumPropertyAccessor.php
  src/Mapping/PropertyAccessors/ObjectCastPropertyAccessor.php
  src/Mapping/PropertyAccessors/PropertyAccessor.php
  src/Mapping/PropertyAccessors/PropertyAccessorFactory.php
  src/Mapping/PropertyAccessors/RawValuePropertyAccessor.php
  src/Mapping/PropertyAccessors/ReadonlyAccessor.php
  src/Mapping/PropertyAccessors/TypedNoDefaultPropertyAccessor.php
  src/PersistentCollection.php
  src/Persisters/Entity/BasicEntityPersister.php
  src/Persisters/Entity/JoinedSubclassPersister.php
  src/Proxy/ProxyFactory.php
  src/Tools/SchemaValidator.php
  src/UnitOfWork.php
  tests/Tests/Models/PropertyHooks/User.php
  tests/Tests/ORM/Functional/EnumTest.php
  tests/Tests/ORM/Functional/Ticket/DDC168Test.php
  tests/Tests/ORM/Functional/ValueObjectsTest.php
  tests/Tests/ORM/Mapping/ClassMetadataLoadEventTest.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Tests/ORM/Mapping/PropertyAccessors/EnumPropertyAccessorTest.php
  tests/Tests/ORM/Mapping/PropertyAccessors/ObjectCastPropertyAccessorTest.php
  tests/Tests/ORM/Mapping/PropertyAccessors/RawValuePropertyAccessorTest.php
  tests/Tests/ORM/Mapping/PropertyAccessors/ReadOnlyAccessorTest.php
  tests/Tests/ORM/Mapping/PropertyAccessors/TypedNoDefaultPropertyAccessorTest.php
Labels: Improvement
