Repository doctrine/orm, pull requests merged in 2025-08, with the labels that each got.

#11934 Fix JoinedSubclassPersister when multiple entities are inserted
  src/Persisters/Entity/BasicEntityPersister.php
  src/Persisters/Entity/JoinedSubclassPersister.php
Labels: Bug

#12095 Performance optimization in `ScalarColumnHydrator::hydrateAllData()`
  src/Internal/Hydration/ScalarColumnHydrator.php
Labels: Improvement

#12126 Deprecate specifying nullable on primary key columns
  UPGRADE.md
  src/Mapping/Builder/AssociationBuilder.php
  src/Mapping/Builder/ManyToManyAssociationBuilder.php
  src/Mapping/JoinTableMapping.php
  src/Mapping/ManyToManyOwningSideMapping.php
  src/Mapping/ToOneOwningSideMapping.php
  tests/Tests/Models/DDC3579/DDC3579Admin.php
  tests/Tests/Models/DDC3579/DDC3579User.php
  tests/Tests/Models/GH10334/GH10334Foo.php
  tests/Tests/Models/OneToOneInverseSideWithAssociativeIdLoad/InverseSide.php
  tests/Tests/ORM/Functional/Ticket/DDC1209Test.php
  tests/Tests/ORM/Functional/Ticket/DDC1225Test.php
  tests/Tests/ORM/Functional/Ticket/DDC2084Test.php
  tests/Tests/ORM/Functional/Ticket/DDC2575Test.php
  tests/Tests/ORM/Mapping/ClassMetadataBuilderTest.php
  tests/Tests/ORM/Mapping/JoinTableMappingTest.php
  tests/Tests/ORM/Mapping/ManyToManyOwningSideMappingTest.php
  tests/Tests/ORM/Mapping/ManyToOneAssociationMappingTest.php
  tests/Tests/ORM/Mapping/MappingDriverTestCase.php
  tests/Tests/ORM/Mapping/OneToOneOwningSideMappingTest.php
  tests/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.User.dcm.xml
Labels: Deprecation

#12135 Add missing assertion in test
  tests/Tests/ORM/Mapping/OneToOneOwningSideMappingTest.php
Labels: Test Suite

#12134 PHPCS 3.13.2
  composer.json
Labels: Code Style

#12137 Forbid nullable on columns that are part of a primary key
  UPGRADE.md
  src/Mapping/ManyToManyOwningSideMapping.php
  src/Mapping/MappingException.php
  src/Mapping/ToOneOwningSideMapping.php
  tests/Tests/ORM/Mapping/ManyToManyOwningSideMappingTest.php
  tests/Tests/ORM/Mapping/ManyToOneAssociationMappingTest.php
  tests/Tests/ORM/Mapping/MappingDriverTestCase.php
  tests/Tests/ORM/Mapping/OneToOneOwningSideMappingTest.php
  tests/Tests/ORM/Tools/SchemaValidatorTest.php
Labels: BC Break

#12142 Prefer non-deprecated AbstractAsset API
  phpstan-baseline.neon
  phpstan-dbal3.neon
  src/Mapping/Driver/DatabaseDriver.php
  src/Tools/SchemaTool.php
Labels: Bug

#12146 PHPUnit 11
  .github/workflows/continuous-integration.yml
  composer.json
  tests/Tests/ORM/Functional/EagerFetchOneToManyWithCompositeKeyTest.php
  tests/Tests/ORM/Functional/QueryCacheTest.php
  tests/Tests/ORM/Functional/Ticket/DDC3042Test.php
  tests/Tests/ORM/Functional/Ticket/GH10049/GH10049Test.php
  tests/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Tests/ORM/Mapping/DefaultQuoteStrategyTest.php
  tests/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
  tests/Tests/ORM/Persisters/ManyToManyPersisterTest.php
  tests/Tests/ORM/Query/ParserResultTest.php
  tests/Tests/ORM/Query/QueryTest.php
  tests/Tests/ORM/Repository/DefaultRepositoryFactoryTest.php
  tests/Tests/ORM/Tools/Pagination/PaginatorTest.php
  tests/Tests/ORM/UnitOfWorkTest.php
  tests/Tests/OrmFunctionalTestCase.php
  tests/Tests/OrmTestCase.php
Labels: Test Suite
