Repository doctrine/orm, pull requests merged in 2025-06, with the labels that each got.

#11973 Add constructor argument
  src/Query/AST/NewObjectExpression.php
Labels: Improvement

#11996 Remove deprecated configuration methods
  UPGRADE.md
  src/Configuration.php
Labels: BC Break

#11999 Drop checks on PHP_VERSION_ID
  docs/en/reference/advanced-configuration.rst
  src/Configuration.php
  src/Mapping/ClassMetadataFactory.php
  src/Mapping/PropertyAccessors/ObjectCastPropertyAccessor.php
  src/Mapping/PropertyAccessors/PropertyAccessorFactory.php
  src/Mapping/PropertyAccessors/RawValuePropertyAccessor.php
  src/Proxy/ProxyFactory.php
  tests/Tests/ORM/Functional/PropertyHooksTest.php
  tests/Tests/ORM/Functional/Ticket/GH11072/GH11072Test.php
  tests/Tests/ORM/Mapping/PropertyAccessors/ObjectCastPropertyAccessorTest.php
  tests/Tests/ORM/Mapping/PropertyAccessors/RawValuePropertyAccessorTest.php
  tests/Tests/OrmFunctionalTestCase.php
Labels: Improvement

#11781 Detect DBAL's number type
  src/Mapping/DefaultTypedFieldMapper.php
  tests/Tests/Models/TypedProperties/UserTyped.php
  tests/Tests/ORM/Mapping/ClassMetadataTest.php
  tests/Tests/ORM/Mapping/TypedFieldMapperTest.php
Labels: New Feature

#12005 Deprecate not using native lazy objects on PHP 8.4+
  UPGRADE.md
  src/Configuration.php
  tests/Tests/ORM/ConfigurationTest.php
Labels: Deprecation

#12012 Revert "add capability to use allfields sql notation"
  UPGRADE.md
  docs/en/reference/dql-doctrine-query-language.rst
  phpstan-baseline.neon
  src/Query/AST/AllFieldsExpression.php
  src/Query/AST/NewObjectExpression.php
  src/Query/Parser.php
  src/Query/SqlWalker.php
  tests/Tests/Models/CMS/CmsDumbVariadicDTO.php
  tests/Tests/ORM/Functional/NewOperatorTest.php
Labels: BC Break

#11988 Add index mapping to column
  docs/en/reference/attributes-reference.rst
  docs/en/reference/php-mapping.rst
  docs/en/reference/xml-mapping.rst
  doctrine-mapping.xsd
  src/Mapping/Builder/FieldBuilder.php
  src/Mapping/ClassMetadata.php
  src/Mapping/Column.php
  src/Mapping/Driver/AttributeDriver.php
  src/Mapping/Driver/XmlDriver.php
  src/Mapping/FieldMapping.php
  src/Tools/SchemaTool.php
  tests/Tests/ORM/Functional/Ticket/GH11982Test.php
  tests/Tests/ORM/Mapping/MappingDriverTestCase.php
  tests/Tests/ORM/Mapping/XmlMappingDriverTest.php
  tests/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.User.dcm.xml
Labels: New Feature

#12020 Deprecate more proxies-related methods or calls
  UPGRADE.md
  docs/en/reference/tools.rst
  src/Configuration.php
  src/EntityManager.php
  src/ORMSetup.php
  src/Proxy/ProxyFactory.php
  src/Tools/Console/Command/GenerateProxiesCommand.php
  tests/Tests/ORM/ConfigurationTest.php
  tests/Tests/TestUtil.php
Labels: Deprecation

#12022 Provide upgrade path to new ORMSetup::create* signature
  UPGRADE.md
  docs/en/reference/configuration.rst
  docs/en/tutorials/getting-started.rst
  src/EntityManager.php
  src/ORMSetup.php
  tests/Tests/ORM/ORMSetupTest.php
Labels: Deprecation

#12031 Clean the handling of proxy initialization in the UnitOfWork
  src/UnitOfWork.php
Labels: Improvement

#12033 Remove wrong assertion
  phpstan-baseline.neon
  src/UnitOfWork.php
Labels: Static Analysis

#12030 Rework tests and benchmarks to work with lazy objects
  tests/Performance/LazyLoading/ProxyInitializationTimeBench.php
  tests/Tests/ORM/Functional/ProxiesLikeEntitiesTest.php
  tests/Tests/ORM/Functional/Ticket/GH10808Test.php
Labels: Test Suite

#12036 Deprecate proxy autoloader and class name resolver
  src/Proxy/Autoloader.php
  src/Proxy/DefaultProxyClassNameResolver.php
  tests/Tests/Proxy/AutoloaderTest.php
Labels: Deprecation

#12029 Remove the possibility to use userland proxies
  .github/workflows/continuous-integration.yml
  .github/workflows/phpbench.yml
  UPGRADE.md
  composer.json
  docs/en/reference/advanced-configuration.rst
  docs/en/reference/tools.rst
  phpcs.xml.dist
  phpstan-baseline.neon
  src/AbstractQuery.php
  src/Cache/DefaultCache.php
  src/Cache/DefaultEntityHydrator.php
  src/Cache/Persister/Collection/AbstractCollectionPersister.php
  src/Cache/Persister/Collection/ReadOnlyCachedCollectionPersister.php
  src/Cache/Persister/Entity/AbstractEntityPersister.php
  src/Cache/Persister/Entity/ReadOnlyCachedEntityPersister.php
  src/Configuration.php
  src/EntityManager.php
  src/Mapping/ClassMetadataFactory.php
  src/Mapping/PropertyAccessors/RawValuePropertyAccessor.php
  src/ORMInvalidArgumentException.php
  src/ORMSetup.php
  src/Persisters/Entity/BasicEntityPersister.php
  src/Proxy/Autoloader.php
  src/Proxy/DefaultProxyClassNameResolver.php
  src/Proxy/InternalProxy.php
  src/Proxy/NotAProxyClass.php
  src/Proxy/ProxyFactory.php
  src/Tools/Console/Command/GenerateProxiesCommand.php
  src/Tools/Console/ConsoleRunner.php
  src/Tools/Debug.php
  src/UnitOfWork.php
  tests/.gitignore
  tests/Performance/EntityManagerFactory.php
  tests/Performance/Mock/NonProxyLoadingEntityManager.php
  tests/Tests/Mocks/EntityManagerMock.php
  tests/Tests/ORM/ConfigurationTest.php
  tests/Tests/ORM/Functional/Locking/LockAgentWorker.php
  tests/Tests/ORM/Functional/PostLoadEventTest.php
  tests/Tests/ORM/Functional/PropertyHooksTest.php
  tests/Tests/ORM/Functional/ProxiesLikeEntitiesTest.php
  tests/Tests/ORM/Functional/ReferenceProxyTest.php
  tests/Tests/ORM/Functional/Ticket/GH11149/GH11149Test.php
  tests/Tests/ORM/Hydration/ObjectHydratorTest.php
  tests/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Tests/ORM/ORMSetupTest.php
  tests/Tests/ORM/Proxy/ProxyFactoryTest.php
  tests/Tests/ORM/Tools/Console/ConsoleRunnerTest.php
  tests/Tests/ORM/UnitOfWorkTest.php
  tests/Tests/OrmFunctionalTestCase.php
  tests/Tests/OrmTestCase.php
  tests/Tests/Proxy/AutoloaderTest.php
  tests/Tests/TestUtil.php
Labels: BC Break

#11978 #11977 implemented batching of `INSERT` operations in `UnitOfWork#executeInserts()` so that `EntityPersister#executeInserts()` calls are reduced
  src/Internal/UnitOfWork/InsertBatch.php
  src/UnitOfWork.php
  tests/Tests/Mocks/EntityPersisterMock.php
  tests/Tests/ORM/Internal/UnitOfWork/InsertBatchTest.php
  tests/Tests/ORM/UnitOfWorkTest.php
Labels: Improvement

#12037 Add console completion for entityName param of orm:mapping:describe c…
  src/Tools/Console/Command/MappingDescribeCommand.php
  tests/Tests/ORM/Tools/Console/Command/MappingDescribeCommandTest.php
Labels: Improvement

#12043 Only throw PHP 8.4 requirement exception when enabling native lazy objects.
  src/Configuration.php
Labels: Bug
