Repository doctrine/orm, pull requests merged in 2025-10, with the labels that each got.

#12182 do not call setAccessible() on PHP >= 8.1
  src/Proxy/ProxyFactory.php
  src/UnitOfWork.php
  tests/Tests/ORM/Cache/DefaultCacheTest.php
  tests/Tests/ORM/Cache/DefaultQueryCacheTest.php
  tests/Tests/ORM/Cache/FileLockRegionTest.php
  tests/Tests/ORM/Cache/Persister/Collection/ReadWriteCachedCollectionPersisterTest.php
  tests/Tests/ORM/Cache/Persister/Entity/NonStrictReadWriteCachedEntityPersisterTest.php
  tests/Tests/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersisterTest.php
  tests/Tests/ORM/Functional/PaginationTest.php
  tests/Tests/ORM/Functional/ParserResultSerializationTest.php
  tests/Tests/ORM/Functional/SQLFilterTest.php
  tests/Tests/ORM/Functional/SecondLevelCacheCountQueriesTest.php
  tests/Tests/ORM/Functional/SecondLevelCacheQueryCacheTest.php
  tests/Tests/ORM/Functional/Ticket/DDC3123Test.php
  tests/Tests/ORM/Functional/Ticket/GH7407Test.php
  tests/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
  tests/Tests/ORM/Mapping/ReflectionEmbeddedPropertyTest.php
  tests/Tests/ORM/ORMSetupTest.php
  tests/Tests/ORM/Persisters/BasicEntityPersisterTypeValueSqlTest.php
  tests/Tests/ORM/Proxy/ProxyFactoryTest.php
  tests/Tests/ORM/Tools/EntityGeneratorTest.php
Labels: Bug

#12188 Add a CI job that fails on deprecations
  .github/workflows/continuous-integration.yml
Labels: CI

#12003 Remove calls to `getMockForAbstractClass()`
  phpcs.xml.dist
  tests/Tests/ORM/AbstractQueryTest.php
  tests/Tests/ORM/Functional/QueryCacheTest.php
  tests/Tests/ORM/Hydration/AbstractHydratorTest.php
  tests/Tests/ORM/Mapping/DefaultQuoteStrategyTest.php
  tests/Tests/ORM/Query/ParserResultTest.php
Labels: Test Suite
