Repository doctrine/orm, pull requests merged in 2025-05, with the labels that each got.

#11924 prefer primary key constraints over Index::isPrimary()
  phpstan-baseline.neon
  src/Mapping/Driver/DatabaseDriver.php
Labels: Improvement

#11917 Fix the initialization of lazy-ghost proxies with postLoad listeners
  src/Proxy/ProxyFactory.php
  src/UnitOfWork.php
  tests/Tests/Models/GH11524/GH11524Entity.php
  tests/Tests/Models/GH11524/GH11524Listener.php
  tests/Tests/Models/GH11524/GH11524Relation.php
  tests/Tests/ORM/Functional/LifecycleCallbackTest.php
  tests/Tests/ORM/Functional/Ticket/DDC1690Test.php
  tests/Tests/ORM/Functional/Ticket/DDC2230Test.php
  tests/Tests/ORM/Functional/Ticket/GH11524Test.php
Labels: Bug

#11834 document how to work with generated columns
  docs/en/cookbook/generated-columns.rst
  docs/en/cookbook/generated-columns/Article.php
  docs/en/cookbook/generated-columns/Person.php
  docs/en/index.rst
  docs/en/reference/attributes-reference.rst
  docs/en/sidebar.rst
Labels: Documentation

#11932 #11931 Bug when change sql filter [Related issue #11694]
  src/Persisters/Entity/BasicEntityPersister.php
  src/Persisters/Entity/JoinedSubclassPersister.php
  src/Persisters/Entity/SingleTablePersister.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/AbstractTest.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/ChangeFiltersTest.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/Insurance.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/Order.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/Patient.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/PatientInsurance.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/Practice.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/PrimaryPatInsurance.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/SecondaryPatInsurance.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/Entity/User.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/SQLFilter/CompanySQLFilter.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/SQLFilter/PracticeContextSQLFilter.php
  tests/Tests/ORM/Functional/Ticket/SwitchContextWithFilter/SwitchContextTest.php
Labels: Bug

#11846 add capability to use allfields sql notation
  docs/en/reference/dql-doctrine-query-language.rst
  phpstan-baseline.neon
  src/Query/AST/AllFieldsExpression.php
  src/Query/AST/NewObjectExpression.php
  src/Query/Parser.php
  src/Query/SqlWalker.php
  tests/Tests/Models/CMS/CmsDumbVariadicDTO.php
  tests/Tests/ORM/Functional/NewOperatorTest.php
Labels: New Feature

#11951 insert blank line before code in code-block
  docs/en/cookbook/generated-columns.rst
Labels: Documentation
