Repository doctrine/orm, pull requests merged in 2025-07, with the labels that each got.

#12054 doc: add links to GitHub Actions on README
  README.md
Labels: Documentation

#12056 Remove branchName from unmaintained branch
  .doctrine-project.json
Labels: Documentation

#12062 Fix unhandled ParameterType case for binary PKs
  src/Persisters/Entity/BasicEntityPersister.php
  tests/Tests/Models/BinaryPrimaryKey/BinaryId.php
  tests/Tests/Models/BinaryPrimaryKey/BinaryIdType.php
  tests/Tests/Models/BinaryPrimaryKey/Category.php
  tests/Tests/ORM/Persisters/BinaryIdPersisterTest.php
Labels: Bug

#12072 Update baseline because of doctrine/dbal 4.3.0
  phpstan-baseline.neon
  phpstan-dbal3.neon
  phpstan.neon
Labels: Static Analysis

#12068 QueryBuilder: prevent misuse of DELETE with LIMIT
  src/QueryBuilder.php
  tests/Tests/ORM/QueryBuilderTest.php
Labels: Improvement

#12063 Proxy class with BackedEnum as primary key does not convert the enum
  src/Persisters/Entity/BasicEntityPersister.php
  tests/Doctrine/Tests/ORM/Functional/Ticket/GH12063.php
Labels: Bug

#12075 :book: Actualize code block to be compatible with DBAL v4, use modern PHP
  docs/en/cookbook/mysql-enums.rst
Labels: Documentation

#12078 Fix embedded classes display in orm:mapping:command output
  src/Tools/Console/Command/MappingDescribeCommand.php
Labels: Bug

#12071 Add JSON format option for orm:mapping:describe command output
  src/Tools/Console/Command/MappingDescribeCommand.php
  src/Tools/Console/Command/MappingDescribeCommandFormat.php
  tests/Tests/ORM/Tools/Console/Command/MappingDescribeCommandTest.php
Labels: New Feature

#12086 Add functional strict-locking 2nd level cache test
  tests/Tests/ORM/Functional/SecondLevelCacheCountQueriesTest.php
Labels: Test Suite
